fcat: new port
macports/macports-ports pull request #10024
Opened 2021-02-14 00:06 UTC by kamischi

#### Description

fcat is a Fortran coverage analysis tool.

###### Type(s)

- [x] enhancement

###### Tested on
macOS 11.2.1 20D74
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-02-14 00:39 UTC, kencu commented
Hey my friend, you're just about to get hit again with 10 fixes for your submission :>

Look at what Ryan did to your last three, and match him. I can't commit this again -- too hard on my ego and rep!

What kind of an animal have you got here? You're not configuring or building anything... is it a 'noarch' shell script or something? And format the Portfile like Ryan did for the last three, or he'll just do it for you again and nobody want that....

Gotta play by the rules :>

2021-02-14 00:55 UTC, kencu requested changes
as noted in comment

2021-02-14 00:56 UTC, kamischi commented
Sorry. I did not notice Ryan's commits and did not really understand your comment on the previous pull request. The animal is a perl script. I will need some time to review Ryan's changes.

2021-02-14 13:18 UTC, kamischi commented
Is there a way to become notifying email, if committers change a port i maintain?

2021-02-17 01:39 UTC, kencu approved these changes

2021-02-17 19:12 UTC, kencu commented
I didn't really approve the changes -- just wanted to get my name off this PR as a reviewer, and that seemed to be the only available option.

2021-02-18 09:34 UTC, kamischi commented
Ah. OK. That explains something, I was wondering about. I won't have time to care about this before next week. The end of the University term this week keeps me busy.

2021-02-19 17:55 UTC, kamischi commented
This is a perl script and i am not at all sure, that I have set all, what is required. I saw some packages with 'depends_lib		bin:perl:perl5' and similar. Is this required? I need some support at this stage.

2021-04-24 14:32 UTC, MarcusCalhoun-Lopez requested changes
Thank you for the submission.
There are a few issues.

* Minor: is there any way to cut down the `long_description`? I think "The FCAT tool is used for the Coverage Analysis of FORTRAN codes." is sufficient.
* Major: I do not believe the `reinplace` does what you intend. However, instead of fixing the `reinplace`, please use a patch file. The patch file would change only one line, it would be easier to understand, and it is the preferred way anyway.
* Unknown: Is the code change really necessary? My Fortran is a little rusty, but doesn't `dimension` *always* have a `(`?
* Minor: This might not be necessary, but adding `installs_libs   no` might be appropriate.
* Medium: Please install examples into `${prefix}/share/${name}/examples`.
* Minor: `configure.perl  /usr/bin/perl` does nothing and can be removed.
* Medium: In the README file, the developers suggest that we "modify the first line of the script." To accomplish this you could
  * change dependency to `depends_lib     port:perl5`,
  * patch `fcat` to start with, e.g., `#!__MACPORTS_PERL5__`, and
  * reinplace `__MACPORTS_PERL5__` with `${prefix}/bin/perl5`.

2021-04-25 20:53 UTC, merged

2021-04-25 20:55 UTC, MarcusCalhoun-Lopez commented
I hit the merge button on the wrong pull request.
My apologies.
Instead of trying to revert this comment (which I have never done), I will make the fixes in the new port.

2021-04-25 21:16 UTC, MarcusCalhoun-Lopez commented
I made a few changes to the fcat port file (https://github.com/macports/macports-ports/commit/02d4cdf91c50e40f98116084ebb0feb0e2729b0b).
Again, sorry @kamischi  for committing it before you had a chance to comment on my requests for change.

If you would like to make changes, especially the dimension patch, please request me as a reviewer, and I will be happy to look at them.

2021-04-25 22:20 UTC, kamischi commented
I am not so fast 😉, but will have a look. Don't worry, I appreciate your comments and will have a look at your changes.