xcodes: new port for a xcode installation manager
macports/macports-ports pull request #10075
Opened 2021-02-20 23:25 UTC by NSCoder

* install RobotsAndPencils/xcodes version 0.16.0
* build from source to generate architecture specific binaries (arm64)

#### Description
Add port to install `xcodes` command line tool that allows to manage Xcode installations. The port compiles from source instead of downloading the binary tarball because arm64 slices are not provided.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.1
Xcode 12.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-02-21 04:36 UTC, NSCoder commented
It seems that the azure pipelines swift tools version is not the most recent one: [pipeline logs](https://dev.azure.com/macports/macports-ports/_build/results?buildId=12509&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=08703039-49d0-5b78-7691-5b9414c62c1d&l=134). Unfortunately I'm not the maintainer of the package to downgrade the version of the package.json; is the swift tools version a hard requirement or is something we can configure on pipelines or the port?

2021-02-21 04:37 UTC, kencu commented
you have some whitespace issues, otherwise looks reasonable

2021-02-21 04:59 UTC, NSCoder commented
Thank you @kencu, it seems that those are resolved now.

2021-02-21 06:43 UTC, kencu commented
If you look at the PR in the GitHub editor you will probably be able to see the problems better:

<https://github.com/macports/macports-ports/pull/10075/commits/ada53fad10fe45d9e850a41f13b528fe55758b22>

It's usually the TAB instead of SPACES issue.

2021-02-21 15:15 UTC, mf2k requested changes
Spacing still needs fixing.

2021-02-21 15:15 UTC, mf2k commented on devel/xcodes/Portfile
> +homepage			https://github.com/RobotsAndPencils/xcodes
The GitHub portgroup will set the `homepage` to this value. So this redundant line should be removed.

2021-02-21 19:41 UTC, NSCoder commented
oh I see, for some reason I didn't think about the tab vs spaces and I was thinking more about the empty line warning at the end of the file. Thank you @kencu, @mf2k for the clarification.

2021-02-21 20:12 UTC, mf2k approved these changes

2021-02-22 03:47 UTC, NSCoder commented
@mf2k Thank you for approving the patch. It seems that it will not let me merge the change unless the azure pipelines test passes?

2021-02-22 05:02 UTC, merged