Add pngpaste @ version 0.2.3
macports/macports-ports pull request #10157
Opened 2021-03-06 05:03 UTC by telotortium

#### Description

Add pngpaste @ version 0.2.3

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.2 20D80
Xcode 12.4 12D4e

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-03-07 01:34 UTC, kurthindenburg commented
You should use the github portgroup which will make this easier. 

https://guide.macports.org/#reference.portgroup.github

2021-03-09 04:46 UTC, telotortium commented
Made a new commit with the github PortGroup

2021-03-12 12:21 UTC, harens reviewed
Hi there @telotortium. 👋 Thank you for your first contribution to MacPorts! 🥳

You've done a great job on this port. I've just left a few minor nitpicks below which are easily fixable. A lot of it boils down to things that the [GitHub PG](https://github.com/macports/macports-ports/blob/master/_resources/port1.0/group/github-1.0.tcl) already does for you, and so are not required.

I'd also recommend that the checksums should be added to the port.

```tcl
checksums           rmd160  76e0c4526d0afcc7458c4a394182c2a0e23c91ff \
                    sha256  ebbe5235c373095af1f060bc561d1c91141a4d72870547685f95d1d7d94ad480 \
                    size    4163
```

Would you be ok changing the title to something like `pngpaste: new port` in line with the [commit msg guidelines](https://trac.macports.org/wiki/CommitMessages)?

Let me know if you have any questions and I'd be happy to help. Thanks again for your contribution @telotortium!

2021-03-12 12:21 UTC, harens commented on aqua/pngpaste/Portfile
> +}
```suggestion
use_configure       no
destroot            {
    xinstall ${worksrcpath}/pngpaste ${destroot}${prefix}/bin
}
```

I think we can simplify this a bit. The default mode is `755` so it's already set, and `${destroot}${prefix}/bin` should already be created.

See https://guide.macports.org/#reference.tcl-extensions for more info.

nitpick: I also aligned the `{` to match the spacing.

2021-03-12 23:03 UTC, cjones051073 commented
Please can you also squash your commits, and also please can you make sure they follow our commit guidelines, which they currently do not do.

2021-03-12 23:04 UTC, cjones051073 commented
Ah, just saw @harens made the same comment, my mistake..

2021-03-12 23:12 UTC, cjones051073 commented
@telotortium you need to squash your commits, not keep adding new ones. If you are not sure how to do this just ask for help.

2021-03-12 23:21 UTC, cjones051073 requested changes

2021-03-12 23:21 UTC, cjones051073 commented on aqua/pngpaste/Portfile
> +master_sites        https://github.com/jcsalterego/pngpaste
Why was this resolved, when you didn’t make the change ?

2021-03-12 23:22 UTC, cjones051073 commented on aqua/pngpaste/Portfile
> +version             0.2.3
You didn’t change anything

2021-03-12 23:23 UTC, cjones051073 commented on aqua/pngpaste/Portfile
> +maintainers         telotortium
Again you resolved this without changing anything.

2021-03-12 23:26 UTC, cjones051073 approved these changes

2021-03-12 23:27 UTC, merged