libvirt, py-libvirt: update to 7.1.0
macports/macports-ports pull request #10186
Opened 2021-03-09 15:15 UTC by jrjsmrtn

#### Description

This PR updates libvirt, py-libvirt to v7.1.0, the first version to support Apple Silicon. It is based on https://github.com/macports/macports-ports/pull/10046, opened for the v7.0.0 update.

Two libvirt Meson tests related to TLS are failing. Python tests are successful.

----

```
in ~/Repositories/macports-ports/sysutils/libvirt/work/build
$ meson test
[...]
 73/111 virnettlscontexttest          FAIL            1.29s   killed by signal 6 SIGABRT
11:30:20 VIR_TEST_EXPENSIVE=1 MALLOC_PERTURB_=175 abs_builddir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/build/tests abs_top_builddir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/build abs_srcdir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/libvirt-7.1.0/tests LIBVIRT_AUTOSTART=0 G_DEBUG=fatal-warnings LC_ALL=C abs_top_srcdir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/libvirt-7.1.0 /opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/build/tests/virnettlscontexttest
----------------------------------- output -----------------------------------
stderr:
TEST: virnettlscontexttest
------------------------------------------------------------------------------

 74/111 virnettlssessiontest          FAIL            1.45s   killed by signal 6 SIGABRT
11:30:20 VIR_TEST_EXPENSIVE=1 MALLOC_PERTURB_=126 abs_builddir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/build/tests abs_top_builddir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/build abs_srcdir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/libvirt-7.1.0/tests LIBVIRT_AUTOSTART=0 G_DEBUG=fatal-warnings LC_ALL=C abs_top_srcdir=/opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/libvirt-7.1.0 /opt/local/var/macports/build/_Users_gm_Repositories_macports-ports_sysutils_libvirt/libvirt/work/build/tests/virnettlssessiontest
----------------------------------- output -----------------------------------
stderr:
TEST: virnettlssessiontest
------------------------------------------------------------------------------
[...]
```

```
in ~/Repositories/macports-ports/python/py-libvirt/work/libvirt-python-7.1.0
$ sudo python3.9 ./setup.py test
running test
/opt/local/bin/python3.9 sanitytest.py build/lib.macosx-11.2-arm64-3.9 /opt/local/share/libvirt/api/libvirt-api.xml
/opt/local/bin/python3.9 /opt/local/bin/nosetests-3.9
......
----------------------------------------------------------------------
Ran 6 tests in 0.062s

OK
```
----

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

MacPorts 2.6.4
macOS 11.2.2 20D80
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2021-03-09 15:50 UTC, mf2k requested changes

2021-03-09 15:50 UTC, mf2k commented on sysutils/libvirt/Portfile
> +set python_branch   3.9
To simplify changing python going forward, use this to set the `python_branch`. Try this untested code based on similar code from the python 1.0 portgroup. 


`set python_branch   {[string index ${python_version} 0].[string range ${python_version} 1 end]}
`

2021-03-09 16:28 UTC, mf2k commented on sysutils/libvirt/Portfile
> +set python_branch   3.9
That looks fine too.

2021-03-10 14:21 UTC, mf2k approved these changes

2021-03-11 22:28 UTC, ryandesign commented
> It is based on #10046, opened for the v7.0.0 update.

So this incorporates everything from that PR and that PR should be closed?

In future, it's less confusing if you update the existing PR rather than create a new one.

2021-03-12 10:02 UTC, jrjsmrtn commented
> It is based on #10046 <https://github.com/macports/macports-ports/pull/10046>, opened for the v7.0.0 update.
> 
> So this incorporates everything from that PR and that PR should be closed?
> 
> In future, it's less confusing if you update the existing PR rather than create a new one.
> 


OK, will do.

G.

2021-03-15 04:12 UTC, ryandesign commented
When I wrote my previous comment I had not realized that the other PR updating to 7.0.0 was submitted by someone else. I've merged that PR, hoping that this new PR would figure itself out and leave only your commit needing to be merged. Instead, a conflict has occurred. Are you able to resolve it? 

For future changes, maybe it's simpler not to submit PRs that are based on other PRs. Instead let's work to get those existing PRs merged first. Then you can submit a PR based on master as usual.

2021-03-19 08:50 UTC, merged

2021-03-27 12:40 UTC, jrjsmrtn commented
Thanks, Ryan. :-)

Re: the conflict:

At first, I only updated the version and checksums (and performed all upstream tests as I was compiling on M1). Then I was asked to change this:

```tcl
set python_version  39
set python_branch   3.9
```

to this:

```tcl
set python_version  39
set python_branch {[string index ${python_version} 0].[string range ${python_version} 1 end]}
```

I proposed this instead, as it seemed more readable/maintainable to me:

```tcl
set python_version_major 3
set python_version_minor 9
set python_version ${python_version_major}${python_version_minor}
set python_branch ${python_version_major}.${python_version_minor}
```

and it was committed as:

```tcl
set python_branch   3.9
set python_version  [string map {. {}} ${python_branch}]
```

I still don't see what the problem was with the original version, but the _requested changes_ caused the conflict. :-q

---

This brings me to: what's the purpose of those requested changes? If I may, this doesn't bring clarity to Portfiles. And we already have a couple of different definitions in Portfiles:

```sh
in ~/Repositories/macports-ports
❯ agp --nofilename '\bset\s+python_(version|branch)\s+[^\s\d\$]' | sed -e 's/^ *//g' -e 's/  */ /g' | sort | uniq

set python_branch "[string range ${pyver} 0 end-1].[string index ${pyver} end]"
set python_branch [join [split ${python.version} {}] "."]
set python_branch [join [split ${ver} {}] "."]
set python_branch [string index ${python_version} 0].[string range ${python_version} 1 end]
set python_branch [string range ${python_version} 0 end-1].[string index ${python_version} end]
set python_version [join [lrange [split ${python_branch} .] 0 1] ""]
set python_version [join [split ${python_branch} "."] ""]
set python_version [string index ${pyver} 0][string index ${pyver} end]
set python_version [string map {"." ""} ${python_branch}]
set python_version [string map {. ""} ${python_branch}]
set python_version [string map {. {}} ${python_branch}]
```

(that said, a closed PR may not be the right place for this discussion, should I move it to the mailing list or open an issue?)

2021-03-31 13:20 UTC, jrjsmrtn commented
Never mind... I was searching for something in the [https://trac.macports.org/wiki/PortfileRecipes](PortfileRecipes) and found [https://trac.macports.org/wiki/PortfileRecipes#branch](Branch versions and version segments) as the first recipe... 🙃

2021-03-31 16:28 UTC, ryandesign commented
The goal is to have a single variable that can be changed whenever the python version needs to be changed. The same applies any other time you need values that are based on some other value. Define the original value once, then compute what you need from that, so that you don't have to update it in multiple places and risk forgetting to update some of them. [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

I chose to commit something different than what was proposed here, because I preferred my version. I prefer to define a variable containing the version (e.g. "3.9") and compute the lossy representation (e.g. "39") from that, not the other way around. My way is easy (remove all periods); the other way is hard (insert periods -- where? Do all of the existing methods correctly handle upcoming python 3.10? I'll bet they don't).