astroid: new submission
macports/macports-ports pull request #10568
Opened 2021-04-03 21:44 UTC by arietis

#### Description
New port for Astroid Mail User Agent.

###### Tested on
macOS 11.2.3 20D91
Xcode 12.3 12C33

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-04-04 13:28 UTC, herbygillot commented
Looks like you missed including Boost as a dependency:
```
021-04-04T00:29:12.1238620Z CMake Error at /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
2021-04-04T00:29:12.1239690Z   Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem program_options
2021-04-04T00:29:12.1240320Z   log_setup log thread date_time system)
2021-04-04T00:29:12.1240840Z Call Stack (most recent call first):
2021-04-04T00:29:12.1241910Z   /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
2021-04-04T00:29:12.1243090Z   /opt/local/share/cmake-3.19/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
2021-04-04T00:29:12.1243770Z   CMakeLists.txt:109 (find_package)
2021-04-04T00:29:12.1244060Z
2021-04-04T00:29:12.1244280Z
2021-04-04T00:29:12.1245050Z -- Configuring incomplete, errors occurred!
2021-04-04T00:29:12.1245810Z See also "/opt/local/var/macports/build/_Users_runner_work_1_s_ports_mail_astroid/astroid/work/build/CMakeFiles/CMakeOutput.log".
2021-04-04T00:29:12.1377760Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_1_s_ports_mail_astroid/astroid/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.14" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk" /opt/local/var/macports/build/_Users_runner_work_1_s_ports_mail_astroid/astroid/work/astroid-0.15
2021-04-04T00:29:12.1380460Z Exit code: 1
2021-04-04T00:29:12.1383290Z Error: Failed to configure astroid: configure failure: command execution failed
```

2021-04-04 13:31 UTC, herbygillot commented on mail/astroid/Portfile
> +maintainers         @arietis
Normally the maintainer block would be set to your name + `openmaintainer`, indicating that others can contribute to this port as well.

```
maintainers @arietis \
            openmaintainer
```

See: https://guide.macports.org/chunked/reference.html#reference.keywords.maintainers

2021-04-05 08:14 UTC, herbygillot requested changes

2021-04-05 08:14 UTC, herbygillot commented on mail/astroid/Portfile
> +
Please add a revision field:
```
github.setup        astroidmail astroid 0.15 v
revison             0
```

The revision field is used to make changes to a port and signal to MacPorts infra to rebuild it even if the software's actual version number has not changed.

2021-04-05 08:14 UTC, herbygillot commented on mail/astroid/Portfile
> +
Ports specified in `depends_build` are understood to be components only required to build the project, and not needed afterwards.

`boost` and `protobuf3-cpp` don't fall into this category.

They are libraries, so these will be needed by `astroid` whenever `astroid` runs.

So `boost` and `protobuf3-cpp` need to move to `depends_build` - which means that not only are they needed to _build_ the software, they're also needed to _run_ the software.

2021-04-05 08:16 UTC, herbygillot commented
`astroid` looks like it's able to build now, so that's good.  Two final comments and then I think this should be good to go.

2021-04-07 23:08 UTC, herbygillot approved these changes

2021-04-07 23:08 UTC, arietis commented
@herbygillot I'm not sure if the `license` field is filled properly though. This file looks unclear to me, maybe I missed something. https://github.com/astroidmail/astroid/blob/master/LICENSE.md

2021-04-07 23:13 UTC, herbygillot commented
> @herbygillot I'm not sure if the `license` field is filled properly though. This file looks unclear to me, maybe I missed something. https://github.com/astroidmail/astroid/blob/master/LICENSE.md

The list of valid values for the Portfile license field can be found here: https://trac.macports.org/wiki/PortfileRecipes#licensekeyword

From that link, it seems like it should be something like:
```
license             GPL-3.0+ LGPL-2.1+
```

....or at least that's my take.

2021-04-08 11:09 UTC, merged