retroarch: new port
macports/macports-ports pull request #10817
Opened 2021-04-27 19:15 UTC by Tatsh

#### Description

RetroArch expects to be able to write downloaded cores and other 'system' data into the app bundle and this is not a normal thing in any other macOS app especially now with app bundle integrity checks. Because of this and because MacPorts installs with files certain permissions, this version has a patch applied that sets default directories to be in `~/Library/Application Support/RetroArch`.

This will allow downloading cores on first launch without needing extra configuration, and without writing into `~/Documents` (a fallback path).

The alternative to downloading cores is to have ports for each core. This should be encouraged when cores are stable, but they do not have to be in this package or even reference it as a dependency.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.3 20D91 x86_64
Xcode 12.5 12E262

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-04-27 23:32 UTC, ryandesign reviewed
> this version has a patch applied that sets default directories to be in `~/Library/Application Support/RetroArch`.

That sounds like a much better place to put those files than into the app bundle itself. Is there an upstream bug report about this problem? Have you suggested this change to them?

2021-04-27 23:32 UTC, ryandesign commented on emulators/retroarch/Portfile
> +        return -code error "incompatible OS X version"
10.7 and earlier are "Mac OS X" not "OS X".
```suggestion
        ui_error "${name} @${version} requires Mac OS X 10.6 or later."
        return -code error "incompatible Mac OS X version"
```

2021-04-27 23:32 UTC, ryandesign commented on emulators/retroarch/Portfile
> +}
Any messages you want to display to the user after installation should usually go in `notes`.
```suggestion
notes {
    On first run, go to "Online Updater" and choose each item beginning with "Update" (e.g. "Update Core Info Files").
}
```

2021-04-27 23:32 UTC, ryandesign commented on emulators/retroarch/files/patch-retroarch-library-dirs.diff
> ++      /* Special case for rewind_buffer_size - need to convert
This and all subsequent changes seem to be just whitespace changes and could be removed since they aren't relevant to the issue being fixed.

2021-04-28 01:22 UTC, Tatsh commented
> > this version has a patch applied that sets default directories to be in `~/Library/Application Support/RetroArch`.
> 
> That sounds like a much better place to put those files than into the app bundle itself. Is there an upstream bug report about this problem? Have you suggested this change to them?

I found this issue: https://github.com/libretro/RetroArch/issues/8641

The user can fix this in the settings UI manually without this patch. Which may be their argument. Or that `~/Documents` can be used, and is indeed sometimes used instead (I do not fully know the behaviour).

I'm providing a little convenience for first time users of RetroArch. Plus, I really dislike RetroArch putting stuff in `~/Documents` even if it's in a subdirectory.

I know that with downloads of assets like the cheat files, if the storage path is not writeable, then the download succeeds but does not extract/install the content of the download, and fails silently. It does not tell the user to use a writeable path or how to fix it.

2021-04-28 13:07 UTC, cjones051073 requested changes

2021-04-28 13:07 UTC, cjones051073 commented on emulators/retroarch/Portfile
> +long_description    ${description}
```suggestion
long_description    {*}${description}
```

2021-04-28 13:07 UTC, cjones051073 commented on emulators/retroarch/Portfile
> +if {${os.major} < 10} {
```suggestion
if {${os.platform} eq “darwin” && ${os.major} < 10} {
```

2021-04-29 10:09 UTC, cjones051073 approved these changes

2021-04-29 10:09 UTC, merged