py-Faker: Update to 8.1.2
macports/macports-ports pull request #10847
Opened 2021-04-30 16:00 UTC by judaew

Changes:
* Update to 8.1.2
* Add supports for Python 3.6
* Add py-text-unidecode depends
* Delete the test phase as it doesn't work correctly and I couldn't
  fix it

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.3 20E232 x86_64
Xcode 12.5 12E262

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-04-30 16:44 UTC, cjones051073 requested changes

2021-04-30 16:44 UTC, cjones051073 commented on python/py-Faker/Portfile
> +    ${description} Whether you need to bootstrap your database, create \
```suggestion
    {*}${description} Whether you need to bootstrap your database, create \
```

2021-04-30 16:57 UTC, judaew commented on python/py-Faker/Portfile
> +    ${description} Whether you need to bootstrap your database, create \
Done

2021-05-01 02:51 UTC, reneeotten commented
what's the issue with the test-phase? I personally do like to have tests enabled, and it presumably worked before so ideally we would fix this. Secondly, do you want to use the PY36 version - if not I would not add it just because upstream supports it... there are already 3 recent versions and soon-ish PY3.10 will be out.

2021-05-01 13:32 UTC, judaew commented
I fixed the test phase. I don't know why thousands of tests with `py.test-${python.branch}` were failing, but with `${python.bin} -m pytest` the tests succeed.

2021-05-01 13:38 UTC, judaew commented on python/py-Faker/Portfile
> +                    port:py${python.version}-ukpostcodeparser \
See https://github.com/macports/macports-ports/pull/10848

2021-05-02 21:10 UTC, cjones051073 approved these changes

2021-05-02 21:11 UTC, merged