ghostscript: update to v9.54.0
macports/macports-ports pull request #10916
Opened 2021-05-06 21:20 UTC by nickgaya

#### Description

* Update version to 9.54.0
    * Disable tesseract/leptonica (see https://trac.macports.org/ticket/62832)
* Clean up outdated patches

###### Type(s)
- [x] update

###### Tested on
macOS 10.14.6 18G9028 x86_64
Xcode 11.3.1 11C505

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-05-06 21:22 UTC, nickgaya commented on print/ghostscript/Portfile
> -patchfiles-append    patch-jpegxr_r_strip.c.diff
This patch was included in 9.54.0 so deleting it here.

2021-05-23 18:21 UTC, chrstphrchvz requested changes
I believe the patch added in 90e528935b can be dropped as well: the upstream report  https://bugs.ghostscript.com/show_bug.cgi?id=702985 was resolved by ArtifexSoftware/ghostpdl@41ef9a0bc3

2021-05-23 18:26 UTC, chrstphrchvz commented
CI build failure for `ghostscript-fonts-hiragino` is expected: https://trac.macports.org/ticket/54098

2021-05-25 09:04 UTC, nickgaya commented
@chrstphrchvz You're right, good catch.  After scrutinizing the build more closely I found several other things I had missed initially. See the updated commit message for a full list of changes and rationale.

2021-06-04 16:10 UTC, merged

2021-06-04 16:10 UTC, l2dy commented
Merged, thank you!