dbeaver-community: Update to 21.0.4
macports/macports-ports pull request #10923
Opened 2021-05-07 12:19 UTC by judaew

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.3.1 20E241 x86_64
Xcode 12.5 12E262

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-05-07 12:27 UTC, lhaeger commented
> Notifying maintainers:
> @lhaeger for port dbeaver-community.

Hi @judaew feel free to take over this port as a maintainer, I'm not using DBeaver much lately, anyway.

2021-05-07 13:38 UTC, judaew commented
Thanks, I'll add myself as a co-maintainer.

2021-05-08 11:24 UTC, reneeotten requested changes

2021-05-08 11:24 UTC, reneeotten commented on databases/dbeaver-community/Portfile
> +PortSystem          1.0
no need to duplicate this line (also, as a nitpick, the commit doen’t really “fix” the style as there wasn’t anything wrong with it before).

2021-05-09 21:27 UTC, reneeotten approved these changes

2021-05-09 21:27 UTC, merged