Fix py-mitmproxy
macports/macports-ports pull request #10972
Opened 2021-05-10 14:21 UTC by syhe

#### Description

Current versions of mitmproxy don't run because of various missing dependencies.

Since this is my first PR against MacPorts, I hope it is formatted correctly, I was a bit overwhelmed with all the guidelines.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H114 x86_64
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
  - The tests seem to be if-guarded and won't execute
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-05-10 17:07 UTC, ryandesign reviewed
Thanks for your contribution! It looks reasonable to me but we should wait for approval from the maintainers of theses ports.

2021-05-10 17:07 UTC, ryandesign commented on python/py-hpack/Portfile
>  revision            1
The revision should drop to 0 when the version is increased.
```suggestion
revision            0
```

2021-05-10 17:07 UTC, ryandesign commented on python/py-openssl/Portfile
>  revision            1
```suggestion
revision            0
```

2021-05-11 01:32 UTC, reneeotten requested changes
thanks @syhe - I quickly checked the first port (`py-h2`) and noticed that this major release has removed support for Python versions that are still listed in the Portfile. Considering that many of the other ports in this PR also update to a major release, that likely is the case for others as well. Please check and update the Portfiles accordingly.

2021-05-11 01:32 UTC, reneeotten commented on python/py-h2/Portfile
> +version             4.0.0
in this version support for PY27/PY34/PY35 has been removed (see the release [notes](http://python-hyper.org/projects/h2/en/stable/release-notes.html#api-changes-backward-incompatible)). 

So you'll need to deal with this in the Portfile and restrict these subports to their latest supported versions or, if they have no dependents, they possibly could be removed.

2021-05-11 01:32 UTC, reneeotten commented on python/py-mitmproxy/Portfile
> +    depends_lib-append      port:py${python.version}-asgiref \
`py-asgiref` has only subports for PY38/PY39, so you'll need to add a PY37 subport there as well to get `py37-mitmproxy` to build. I am not sure why `port lint` doesn't warn about this...

2021-05-26 11:28 UTC, reneeotten commented
ping @syhe - are you planning to follow through with this PR and make the required changes?

2021-05-26 13:09 UTC, syhe commented
@reneeotten Yes, sorry for not getting back to you. I intend to follow through, but it might take some time, since this isn't my top priority right now and I did remove the immediate pain for myself. That also means I'm happy with someone else taking over – but I'll eventually fix this up.

2021-08-13 12:32 UTC, reneeotten commented
ping @syhe - any news/progress here?

2021-08-28 15:19 UTC, reneeotten commented
@syhe please re-open this PR once you have resolved the outstanding issues. Closing this PR for lack of activity/progress.

2021-08-28 15:19 UTC, closed without merging