carthage: update to 0.38.0
macports/macports-ports pull request #10984
Opened 2021-05-11 23:49 UTC by elliottwilliams

#### Description

Increments the version number. Based on what was done last time: https://github.com/macports/macports-ports/commit/466abdca05982d0a983fe00b3aa0fa73ec20f0b9

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.2 20D64 arm64
Xcode 12.4 12D4e

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-05-12 07:18 UTC, cjones051073 requested changes
Your commit message does not follow our guidelines, please update it to the form

portname: description

2021-05-12 07:20 UTC, saagarjha commented
Seems to work in basic tests. Perhaps you can also knock out the lint warning while you're at it?

2021-05-14 02:03 UTC, elliottwilliams commented
Done!

2021-05-14 05:03 UTC, cjones051073 approved these changes

2021-05-14 05:11 UTC, merged