exim: attempt to fix build on 10.11 and earlier
macports/macports-ports pull request #10985
Opened 2021-05-11 23:51 UTC by chrstphrchvz

#### Description
See build failures: https://ports.macports.org/port/exim/builds

###### ~~Tested on~~

Untested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2021-05-12 07:16 UTC, cjones051073 requested changes

2021-05-12 07:16 UTC, cjones051073 commented on mail/exim/Portfile
> +legacysupport.newest_darwin_requires_legacy 15
Please add an empty line after the port group to silence the lint warnings

2021-05-15 13:37 UTC, cjones051073 approved these changes

2021-05-15 13:37 UTC, merged

2021-05-15 15:30 UTC, chrstphrchvz commented
Fails because the `-lMacportsLegacySupport` flag isn’t passed to the linker.

I notice that the `clock_gettime()` usage seems optional, so maybe the check being used (`#ifdef _POSIX_MONOTONIC_CLOCK`) does not work properly.

2021-05-15 15:35 UTC, cjones051073 commented
no, the check is fine as it just tests for the declaration in the headers, which will be found. The issue is the build system is not properly passing the linker flags, and if you do one and not the other you have problems...

2021-05-17 21:23 UTC, chrstphrchvz commented
> no, the check is fine as it just tests for the declaration in the headers, which will be found.

I meant without legacy support—that the check is not useful on macOS because its headers define `_POSIX_MONOTONIC_CLOCK` even for macOS 10.11 and earlier which lack `clock_gettime`, i.e. an upstream bug (if they intend to support older macOS).

2021-05-17 21:25 UTC, chrstphrchvz commented
> i.e. an upstream bug (if they intend to support older macOS).

…unless one argues this is a macOS bug (POSIX noncompliance)