qDMR: new port
macports/macports-ports pull request #10989
Opened 2021-05-12 11:35 UTC by hmatuschek

#### Description
Adds qDMR port.

###### Type(s)
- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 11.3.1 20E241 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-05-12 19:04 UTC, cjones051073 requested changes
Your commit message does not follow our guidelines. Please change it to match the pattern

portname: description

2021-05-12 23:32 UTC, hmatuschek commented
Thanks for the hint. Fixed the commit message. I also managed to fix the compile issues using a patch.

2021-05-13 07:07 UTC, cjones051073 approved these changes

2021-05-13 09:03 UTC, hmatuschek commented
Last push: Moved qt5-qttools to build dependencies.

2021-05-14 05:05 UTC, merged