pymol: Update to 2.5.0 and remove X11 and python27 variants
macports/macports-ports pull request #11137
Opened 2021-05-25 14:34 UTC by jwhowarth

pymol: Update to the 2.5.0 release as well as remove the deprecated X11 and python27 variants

#### Description

###### Type(s)

- [ ] bugfix
- [ x] enhancement
- [ ] security fix

###### Tested on

macOS 11.4
Xcode 12.5

###### Verification 
Have you

- [ x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ x] checked your Portfile with `port lint`?
- [ x] tried existing tests with `sudo port test`?
- [x ] tried a full install with `sudo port -vst install`?
- [ x] tested basic functionality of all binary files?

2021-05-26 00:17 UTC, reneeotten commented on science/pymol/Portfile
>  PortGroup           active_variants 1.1
please remove this PG as it is no longer used

2021-05-26 00:17 UTC, reneeotten commented on science/pymol/Portfile
>  variant python39 conflicts python27 python36 python37 python38 description {Use Python 3.9} {}
the conflict with `python27` should be removed here as this variant doesn't exist anymore

2021-05-26 00:19 UTC, reneeotten commented on science/pymol/Portfile
> +                    size    10471287
you should only update the `checksums` for the "main" `pymol` port; this is still using the same commit so the `checksums` haven't changed

2021-05-26 00:23 UTC, reneeotten commented on science/pymol/Portfile
>  }
the patchfiles should be the same now for both `pymol` and `pymol-devel` so you can remove the special case for the `pymol-devel` port. 

However, the `setup.py.diff` doesn't apply anymore (how did you build this locally?) - you should probably just use rename the `patch-devel-setup.py.diff` to `patch-setup.py.diff` and use that one instead.

2021-05-26 00:24 UTC, reneeotten commented on science/pymol/Portfile
> -                    pdb2pqr.patch \
please also remove the `pdb2pqr.patch` from the `files` directory

2021-05-26 00:24 UTC, reneeotten commented on science/pymol/Portfile
> -                    pdb2pqr.patch \
please also remove the `pdb2pqr.patch` from the `files` directory

2021-05-26 00:25 UTC, reneeotten commented on science/pymol/Portfile
> -                    pdb2pqr.patch \
please also remove the `pdb2pqr.patch` from the `files` directory

2021-05-26 00:33 UTC, reneeotten commented on science/pymol/Portfile
>      python.default_version 39
right now there is no default variant set anymore. The last two lines should be changed to:
```
} else {
    default_variants +python39
     python.default_version 39
```

2021-05-26 00:49 UTC, reneeotten requested changes
thanks for the update @jwhowarth! There are a few issue with it though and I've left some review comments below.

Also, the test don't run right now (it looks like the are not part of the download anymore) so that should either be fixed or the test phase should be removed.

2021-05-27 15:23 UTC, closed without merging

2021-05-27 15:27 UTC, jwhowarth commented
Replaced with pull request #11158