keystore-explorer: fix livecheck
macports/macports-ports pull request #11262
Opened 2021-06-07 16:54 UTC by lhaeger

###### Tested on

macOS 10.15.7 19H1217 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-06-07 17:03 UTC, reneeotten requested changes

2021-06-09 16:34 UTC, cjones051073 commented
Can you check the build failures please.

2021-06-10 16:03 UTC, lhaeger commented on security/keystore-explorer/Portfile
> +livecheck.regex         "archive/refs/tags/v${github.livecheck.regex}.tar.gz"
Using my fork is a temp detour to include a fix that came shortly after the latest release in upstream and I'll revert to upstream with the next version. Therefore livecheck shall notify me when upstream has a new release.

2021-06-10 16:40 UTC, reneeotten commented on security/keystore-explorer/Portfile
> +livecheck.regex         "archive/refs/tags/v${github.livecheck.regex}.tar.gz"
we normally prefer a patch to include the change(s) for a bugfix that cannot wait for a new release. If it's that important please request upstream to release a new version.

2021-06-10 17:56 UTC, lhaeger commented on security/keystore-explorer/Portfile
> +livecheck.regex         "archive/refs/tags/v${github.livecheck.regex}.tar.gz"
Never mind...

2021-06-10 17:56 UTC, closed without merging