doas doesn't install vidoas
macports/macports-ports pull request #11286
Opened 2021-06-09 14:43 UTC by anahata0108

We don't install a vidoas command, so instead tell the user to run a command that has a better chance of working.

2021-06-09 16:35 UTC, cjones051073 requested changes
Please can you change your commit message to follow our guidelines, i.e.

portname: description

2021-06-09 16:51 UTC, herbygillot commented
Also, what happens if `$EDITOR` isn't set?

2021-06-09 17:01 UTC, cjones051073 commented
Does this port build vidoas ? If so surely a better fix is to also install it ? Is the fact it isn’t just an oversight ?

2021-06-10 17:46 UTC, anahata0108 commented
I suppose the existence of this issue depends on whether the port is supposed to install vidoas. Is anyone able to answer that question? danchr has already been pinged, so I don't want to ping them again.

2021-06-10 18:27 UTC, cjones051073 commented
It seems the port does install `vidoas` so this MR is not required.

```
Oberon ~/Projects/MacPorts/ports > port contents doas
Port doas contains:
  /opt/local/bin/doas
  /opt/local/bin/vidoas
  /opt/local/share/doc/doas/doas.conf.dist
  /opt/local/share/doc/doas/doas.conf.sample
  /opt/local/share/man/man1/doas.1.gz
  /opt/local/share/man/man5/doas.conf.5.gz
  /opt/local/share/man/man8/vidoas.8.gz
```

2021-06-10 18:27 UTC, closed without merging

2021-06-10 18:29 UTC, anahata0108 commented
I don't think this is the correct solution. The port installs vidoas to $PREFIX/bin, whereas the message references $PREFIX/sbin. It seems appropriate to change where vidoas is installed, as it's a sysadmin tool. Thoughts?

2021-06-10 18:34 UTC, cjones051073 commented
Good point, missed the message referred to sbin.  https://github.com/macports/macports-ports/commit/e410e5e5def47e0073330055cfd9711a12d8dba7