fheroes2: new port
macports/macports-ports pull request #11307
Opened 2021-06-10 23:33 UTC by oleg-derevenetz

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.2.3 20D91 x86_64
Xcode 12.5 12E262

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ]  referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ]  tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-06-11 02:08 UTC, reneeotten requested changes
a few comments on the Portfile below. I'm not fully clear on how this package works - one still needs to obtain a demo version (or should have bought the original game) before this will run? So what does this port actually do?

2021-06-11 02:08 UTC, reneeotten commented on games/fheroes2/Portfile
> +
please add the leading `0` in front of the `644` and `755`

2021-06-11 05:57 UTC, oleg-derevenetz commented
Hi @reneeotten

> I'm not fully clear on how this package works - one still needs to obtain a demo version (or should have bought the original game) before this will run? So what does this port actually do?

This port installs game engine, which is written from scratch and licensed as GPL-2. But it still needs resource files from original game to run, so user may either download free demo version of original game using bundled script (no campaign, just one map - just to have the overall impression), or purchase original game (it is still available on GOG, for example) and copy resource files to the appropriate place.

2021-06-12 14:54 UTC, reneeotten approved these changes

2021-06-12 14:54 UTC, merged

2021-06-12 14:54 UTC, reneeotten commented
thanks @oleg-derevenetz