automake: update to 1.16.4
macports/macports-ports pull request #12082
Opened 2021-09-04 05:31 UTC by FnControlOption

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2021-09-05 04:36 UTC, jmroot requested changes
`patch-issue57329.diff` should be removed entirely since the issue has been resolved upstream.

2021-09-05 22:38 UTC, jmroot approved these changes

2021-09-06 16:24 UTC, merged

2021-09-06 23:32 UTC, jmroot commented
@herbygillot There was still about half a day to go before maintainer timeout. Please don't merge before the full time is up if the maintainer has not given approval.

2021-09-06 23:53 UTC, herbygillot commented
> @herbygillot There was still about half a day to go before maintainer timeout. Please don't merge before the full time is up if the maintainer has not given approval.

Acknowledged, my mistake.