boost: Try to fix cmake symlink creation.
macports/macports-ports pull request #12174
Opened 2021-09-09 16:58 UTC by Lord-Kamina

Should fix https://trac.macports.org/ticket/63273

#### Description

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C505

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

Note: I haven't tested this very extensively but I used a project I am part of that had no trouble finding Boost before, had been having issues since the new side-by-side boost scheme began (which is a great idea btw) and is now working again with this patch.

2021-09-11 13:52 UTC, reneeotten commented
thanks for the update/fix @Lord-Kamina ! Is this only an issue with the "boost" port or should a similar change be made in all the "boostXYZ" ports? I'll leave it to @michaelld and @mascguy to determine whether this is the preferred way of solving the issue and handle the PR.

2021-09-11 13:55 UTC, Lord-Kamina commented
It seems it's only an issue with the boost port, since that port is essentially just a shim so other things can find the real boost install.

2021-09-11 14:00 UTC, reneeotten commented
oh, yes - I keep forgetting that the "boost" port was changed in that way...

2021-09-11 14:07 UTC, mascguy commented
Looks good to me. @michaelld ?

Gregorio, thanks again for your contribution, it's much appreciated!

2021-09-12 19:54 UTC, michaelld requested changes
I'll admit that I haven't tried change yet. That said, I believe new line 61 and new line 51 do the same thing. I don't think `xinstall -d` will error or even warn if the to-be-created directory already exists, so while fixing this isn't critical I'd still prefer simpler code. This would be pretty simple to check for redundancy. Please do so & report back.

2021-09-12 19:55 UTC, michaelld commented
Other than that request, the code LGTM & makes sense.

2021-09-22 23:25 UTC, Lord-Kamina commented
> I'll admit that I haven't tried change yet. That said, I believe new line 61 and new line 51 do the same thing. I don't think `xinstall -d` will error or even warn if the to-be-created directory already exists, so while fixing this isn't critical I'd still prefer simpler code. This would be pretty simple to check for redundancy. Please do so & report back.

I haven't tried it without the initial `xinstall` (although I added the second one in a later iteration so it may be it negates the need for the former), but I was having the issue where macports would try to create symlinks on a not-yet existing folder and `ln` would fail.

2021-10-08 14:32 UTC, mascguy commented
FYI, I'll test this fix locally over the next few days, once the dust settles re: yesterday's update to GIMP.

2021-10-30 15:04 UTC, merged

2021-10-30 17:28 UTC, mascguy commented
> > I'll admit that I haven't tried change yet. That said, I believe new line 61 and new line 51 do the same thing. I don't think `xinstall -d` will error or even warn if the to-be-created directory already exists, so while fixing this isn't critical I'd still prefer simpler code. This would be pretty simple to check for redundancy. Please do so & report back.
> 
> I haven't tried it without the initial `xinstall` (although I added the second one in a later iteration so it may be it negates the need for the former), but I was having the issue where macports would try to create symlinks on a not-yet existing folder and `ln` would fail.

@michaelld I'll take a closer look at this when I can find some time. But didn't want to delay this any longer, given that it's otherwise okay.

2021-10-30 17:33 UTC, mascguy commented
And Gregorio, thank you so much for your contribution!