pango-devel: Fix man page building on Tiger
macports/macports-ports pull request #12173
Opened 2021-09-09 13:42 UTC by evanmiller

#### Description

`help2man` invokes `utils/pango-view` to generate the man page, but at least on Tiger the libpango dylib can't be found during build-time ("Library not loaded / Reason: image not found" error).

Leaving as a draft until #12171 is merged since this PR relies on features introduced in Meson 0.57.0.

Also added a note about an upstream pull request.

CC @mascguy and #11948

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11 8S165 Power Macintosh
Component versions: DevToolsCore-798.0; DevToolsSupport-794.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-09-13 05:54 UTC, kencu commented
Let's please do this one in the Portfile as well, like we do all the other wacky Tiger meson DYLD_LIBRARY_PATH workarounds, for consistency and to keep any such changes isolated to Tiger only.

Perhaps someday they can all be removed if somebody fixes meson to work right on Tiger, or fixes Tiger to accept rpaths.

2021-09-13 05:55 UTC, kencu requested changes
let's please do this in the Portfile like at-spi2-core and the other meson/Tiger messes.

2021-09-13 08:45 UTC, evanmiller commented
@kencu Done

2021-09-14 06:36 UTC, kencu approved these changes

2021-09-14 06:36 UTC, merged

2021-09-14 06:36 UTC, kencu commented
thanks!