dvbcut: new port
macports/macports-ports pull request #12279
Opened 2021-09-18 12:58 UTC by mkuron

#### Description

dvbcut enables cutting MPEG2 transport streams without re-encoding anything but the first and last few frames. It was originally available at http://dvbcut.sourceforge.net, but maintenance has long been taken over by the Debian package maintainer at https://github.com/bernhardu/dvbcut-deb.

The two patches included in this port have already been merged upstream, but no release has been made since.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 arm64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-09-18 20:05 UTC, reneeotten requested changes
thanks for the submission @mkuron - a few suggestions/corrections below

2021-09-19 10:47 UTC, mkuron commented
I don't think I've ever written a Portfile from scratch, so your comments were very helpful, @reneeotten. I have updated the pull requested and squashed accordingly. The PATH environment variable i still needed -- I suspect that dvbcut's build system isn't using the canonical way to locate the Qt5 tools. Please let me know if anything else needs to be changed.

2021-09-19 15:54 UTC, reneeotten commented
@mkuron thanks for the changes, this looks good! One thing I noticed is the message:
`qt.svg: Cannot open file '/opt/local/share/dvbcut/icons/dvbcut.svg', because: No such file or directory`
when starting the program. 

Indeed, looking what/where files are installed:
```
 % port contents dvbcut
Port dvbcut contains:
  /opt/local/bin/dvbcut
  /opt/local/share/applications/dvbcut.desktop
  /opt/local/share/dvbcut/dvbcut_cs.html
  /opt/local/share/dvbcut/dvbcut_de.html
  /opt/local/share/dvbcut/dvbcut_en.html
  /opt/local/share/icons/hicolor/scalable/apps/dvbcut.svg
  /opt/local/share/man/man1/dvbcut.1.gz
  /opt/local/share/mime/packages/dvbcut.xml
```

it's true that the file doesn't exist at the expected location. So you could either copy it there or try and convince the program to look at `/opt/local/share/icons/hicolor/scalable/apps/`. Other than the error message the program does start, so it might be not that crucial...

2021-09-19 16:11 UTC, mkuron commented
@reneeotten, thanks, fixed that too. Previously the icon was missing in the "About dvbcut" window, now it's there.

2021-09-19 19:24 UTC, reneeotten approved these changes

2021-09-19 19:24 UTC, reneeotten commented
looks good, thanks @mkuron  - in it goes!

2021-09-19 19:24 UTC, merged