rpm: Fix implicit declaration errors
macports/macports-ports pull request #12695
Opened 2021-10-26 20:51 UTC by 21stcaveman

#### Description

rpm: Fix implicit declaration errors

Closes: https://trac.macports.org/ticket/62615
Closes: https://trac.macports.org/ticket/63620

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.5.2
Xcode 13.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-11-06 21:57 UTC, reneeotten requested changes
@21stcaveman this fails on the CI when trying to apply the patch(es); please check

2021-11-07 00:55 UTC, 21stcaveman commented
@reneeotten seems like I need to move this patch to post-configure. Thanks for the heads up, I have never applied a patch in post config. Any pointers on how to do that?

2021-11-07 01:02 UTC, reneeotten commented
> @reneeotten seems like I need to move this patch to post-configure. Thanks for the heads up, I have never applied a patch in post config. Any pointers on how to do that?

that sounds unlikely, doing a patch should be done in the patch phase.

It looks to me like your patchfile isn't formatted correctly (at least compared to the other ones that are present already). Most of the `git` based patches will need `patch.pre_args      -p1`, but since the other patches are likely generated using `diff -u` they don't... I haven't looked carefully, but my guess is you have to change your patch to follow the formatting conventions of the ones that are already present as they all have to be applied with the same arguments to `patch`.

2021-11-07 01:40 UTC, 21stcaveman commented
> ... my guess is you have to change your patch to follow the formatting conventions of the ones that are already present as they all have to be applied with the same arguments to `patch`.

I have done that, and verified that the patch can be applied afterwards. However, problem is, most of the files this patch needs to change, only appear after the 'configure' command is run. For example, there is no db_server_svc.c file under db3 directory, until after the configuration stage.

2021-11-07 02:05 UTC, 21stcaveman commented
Ok, I think I figured out how to do the patch in post-configure... let's see how this goes.

2021-11-07 02:34 UTC, reneeotten commented
> > ... my guess is you have to change your patch to follow the formatting conventions of the ones that are already present as they all have to be applied with the same arguments to `patch`.
> 
> I have done that, and verified that the patch can be applied afterwards. 

?However, problem is, most of the files this patch needs to change, only appear after the 'configure' command is run. For example, there is no db_server_svc.c file under db3 directory, until after the configuration stage.

well... files typically do not appear out of thin air with `configure` command, so they should be somewhere already... In general patching should happen in the patch phase and not later.

2021-11-07 06:29 UTC, 21stcaveman commented
As fair as that is, and I completely agree that stuff do not appear out of thin air, I can not find those files in the build directory before configure is complete (trying `find . -regex "*db_server_svc*"` returns nothing)
I honestly don't have the time to research that further at this point (as rpm is now installed and works for me), and see where those files come from to apply the patch to the source. I am happy to leave this here, in the hope that someone can pick it up from here and apply it appropriately.

2021-11-07 14:07 UTC, reneeotten commented
I am not saying that patching after the configure phase cannot be done per se, if it's needed sure - better to have a port building by doing so than not. So let's keep the PR open and see if there is an interested party to investigate this further; otherwise we can still merge this as an interim solution.

2021-11-07 14:26 UTC, reneeotten commented
@21stcaveman oh, I see this port is also outdated and the current upstream version is 4.17.0. I wouldn't be surprised if upstream has fixed these issues already and therefore updating the port first would be probably a better. Is that something you're interested in attempting?

2021-11-07 17:13 UTC, 21stcaveman commented
Sounds good. I have no spare cycles at the moment, might give upgrading the port a shot when I have some spare time.

2021-11-07 17:28 UTC, reneeotten commented
> Sounds good. I have no spare cycles at the moment, might give upgrading the port a shot when I have some spare time.

okay, if it's a simple update that works out-of-the-box I might just try to do so

2021-12-25 17:05 UTC, reneeotten commented
okay, it doesn't look like anyone has a better solution for this and a simple update didn't work out-of-the box for me. I am sure this isn't the "correct" fix to the problem as I mentioned earlier in this PR but also am not going to work on it myself, so let's merge this so that the port at least can build again.

2021-12-25 17:07 UTC, merged