py-pandas: re-enable parallel builds
macports/macports-ports pull request #12725
Opened 2021-10-29 18:22 UTC by mascguy

#### Description

Re-enable parallel builds for `py-pandas`.

Based on the Git blame, it was disabled way back for v1.0.2, on 3/16/2020: https://github.com/macports/macports-ports/commit/cb7ee2787abef02a17e742c4225dd9eb3a9353f9

###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.12.6 16G2136
Xcode 9.2 9C40b

macOS 10.13.6 17G14019
Xcode 10.1 10B61

macOS 10.14.6 18G103
Xcode 11.3.1 11C505

macOS 10.15.6 19G2021
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-10-29 18:48 UTC, mascguy commented
Andrew/Renee, thus far, I've tested parallel builds against four macOS releases: 10.12, 10.13, 10.14, and 10.15.

Are you folks aware of any upstream issues that might cause an issue, in the latest releases?

2021-10-29 19:25 UTC, mascguy commented
Updated the commit to only enable parallel build for latest release.

As for open upstream issues, I did find one. But the item relates to "build_ext;" is that applicable to us...?

[30873 - Parallel build_ext might fail due to file collisions](https://github.com/pandas-dev/pandas/issues/30873)

2021-10-29 20:03 UTC, reneeotten requested changes
@mascguy I didn't make the change to disable parallel builds. But, we've seen for other Python ports (intermittent) issues with parallels builds that are hard to troubleshoot, and the errors are not always at build-time. Are you using `pandas` yourself - it might build correctly now (or for the few times you tried), but did you put it to test for any calculations/analysis as often things fails at runtime. 

So unless @stromnov wants to re-enable parallel builds I would be in favor of leaving it off. It's working fine right now and a build takes ~15 minutes, so enabling it again with the chances of getting hard-to-debug errors for a few minutes less build-time is not worth the trouble IMHO.

2021-10-29 22:49 UTC, mascguy commented
Without a more intimate understanding of the various interactions, I can't speak to the potential runtime failures. Though it's interesting that these ports can build successfully, whilst still having unforeseen issues that only appear at runtime?

As for build times, bear in mind that each of these take 20+ minutes - and sometimes close to 30 - at least for the newest version. Take a gander at the builds for `py39-pandas`:

Multiply that time across all of the various subports, and - well - I'm not sure I agree that the build times are inconsequential.

Ultimately, if the build artifacts are that fragile and unpredictable when built in parallel, I suppose we may not have a choice. But it almost makes me want to dig into this a bit more, to better understand what's happening. (Whether I can realistically spend that time is another story. But it certainly has piqued my interest...)

2021-10-30 13:17 UTC, reneeotten commented
> As for build times, bear in mind that each of these take 20+ minutes - and sometimes close to 30 - at least for the newest version. Take a gander at the builds for `py39-pandas`:
> 
> https://ports.macports.org/port/py39-pandas/builds/
> 
> Multiply that time across all of the various subports, and - well - I'm not sure I agree that the build times are inconsequential.

the times there are all including building of dependencies and such, but yes sometimes it will take about 20 minutes to build the actual `pandas` subport. Most users will not install from source anyway nor install all different possible subports so if anything it's build time for the buildbots... That is indeed true, but that's what they are intended for and saving ~10-15 minutes of buildtime there for me is not a priority if the possible drawback is breakage of a package. 

I certainly agree with you that someone could/would need to investigate whether this is still an issue and if not it can be enabled again; that someone will just not be me ;)

2021-10-30 19:12 UTC, mascguy commented
> I certainly agree with you that someone could/would need to investigate whether this is still an issue and if not it can be enabled again; that someone will just not be me ;)

No worries. And since getting into the weeds on this might provide longer-term dividends for other areas - and force me to expand my knowledge of both Python in-general, as well as our MacPorts Python framework - I'll add it to my backlog.

And thanks as always for your willingness to provide feedback. I know I can be a major PITA sometimes (or most of the time? Lol), but I really appreciate your thoughts and insight!

2021-11-10 19:41 UTC, closed without merging