py-{anytree,bottlenose}: resolve conflict
macports/macports-ports pull request #12808
Opened 2021-11-04 21:19 UTC by catap

#### Description

Both ports are installed `${python.prefix}/LICENSE`.

Closes: https://trac.macports.org/ticket/63803

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2021-11-04 21:20 UTC, catap commented
@mascguy here it is!

2021-11-04 22:05 UTC, mascguy commented
Looks good to me. But my knowledge of Python is a bit light, so I'll defer to @reneeotten.

2021-11-04 22:05 UTC, mascguy approved these changes

2021-11-04 23:22 UTC, reneeotten requested changes
@catap @mascguy this doesn't look right; for example, now the files get installed in `${prefix}/Library/Frameworks/Python.framework/Versions/3.9/share/doc/py39-anytree/`, that is not where they should go. As mentioned in the guide/wiki somewhere (I think) and done in many other Python ports, the files should go in `{prefix}/share/doc/py39-anytree/`. In the `py-anytree` Portfile that is taken care of in the `post-destroot` phase already, so now the files get installed twice. 

I think in this case the easiest solution is just to remove the `data_files` line from `setup.py` with a patchfile and, if you want for`py-bottlenose` to install the files in the typical `post-destroot` phase.

2021-11-04 23:38 UTC, catap commented
@reneeotten JFYI `py-jinja` has the same wrong location of files.

Anyway, let me make it clean.

2021-11-04 23:46 UTC, reneeotten commented
> @reneeotten JFYI `py-jinja` has the same wrong location of files.

possible... I guess nobody is using that version anymore (probably `py-jinja2` is the one)

> Anyway, let me make it clean.

sure, fixing that doesn't hurt

2021-11-05 10:47 UTC, catap commented
@reneeotten I've applied all your recomendation in the last rebase. Can I ask you to re-review it?

2021-11-05 13:11 UTC, reneeotten requested changes
thanks @catap looks good, one minor formatting request left then we can merge

2021-11-05 13:11 UTC, reneeotten commented on python/py-anytree/Portfile
> +    patchfiles          patch-setup.py.diff
please align this in the same way as the rest of the Portfile (also in `py-bottlenose`)

2021-11-05 14:09 UTC, reneeotten approved these changes

2021-11-05 14:09 UTC, merged