Update neomutt to 20211029
macports/macports-ports pull request #12880
Opened 2021-11-09 21:07 UTC by rionda

#### Description

Update to 20211029.

Among other changes, the slang GUI was retired, so remove the slang variant.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [x] security fix

###### Tested on
macOS 10.15.7 19H1323 x86_64
Xcode 12.4 12D4e

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-11-09 21:25 UTC, lbschenkel requested changes
Commit message needs to follow this pattern:
```
neomutt: update to ...
```

2021-11-09 21:25 UTC, lbschenkel commented on mail/neomutt/Portfile
>  revision            1
Revision needs to be reset to 0.

2021-11-09 21:26 UTC, lbschenkel commented
Thanks for the submission. Some minor changes are required to conform to the project guidelines.

2021-11-09 21:34 UTC, rionda commented
> Commit message needs to follow this pattern:
> 
> ```
> neomutt: update to ...
> ```

I have no idea how to do that at this point. Any guidance?

2021-11-10 07:01 UTC, lbschenkel commented
> I have no idea how to do that at this point. Any guidance?

I took the liberty of fixing the branch for you.

P.S.: if you want to learn about how to do it, I suggest searching for "git interactive rebase" and reading about it. It's simpler than it sounds.

2021-11-10 07:02 UTC, lbschenkel approved these changes

2021-11-10 09:24 UTC, merged

2021-11-10 09:24 UTC, lbschenkel commented
Merged. Thank you for your contribution.