git: do not overwrite the system-wide gitconfig when adding configura…
macports/macports-ports pull request #13259
Opened 2021-12-06 08:16 UTC by herbygillot

…tion for the osxkeychain credential helper

If the gitconfig does not exist, then it will be created. But if it *does*
exist, then the file will be checked to see whether it already contains the
desired config, and if it doesn't, the configuration will be appended to the
already existing file.

Fixes: https://trac.macports.org/ticket/63953

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

2021-12-06 20:09 UTC, cjones051073 requested changes

2021-12-06 20:09 UTC, cjones051073 commented on devel/git/Portfile
> +        if { ![file exists ${system_gitconfig}] } {
You gave a conceptual bug here. When you check the currently existing file you correctly check the *installed* version directly in ${prefix}, but you cannot directly write to this file, which is what you currently do. You have to write to the version in the DESTROOT ie at ${destroot}${prefix}, and if need be first clone the currently installed version before appending to it.

2021-12-07 13:47 UTC, mascguy approved these changes

2021-12-07 13:49 UTC, mascguy commented
LGTM. And this will certainly be appreciated by users who rely on customization to the system config.

Great work Herby!

2021-12-07 13:49 UTC, merged