jove: update to 4.16.0.73
macports/macports-ports pull request #13281
Opened 2021-12-08 07:53 UTC by herbygillot

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

2021-12-09 22:21 UTC, reneeotten requested changes
@herbygillot this port is not [UsingTheRightCompiler](https://trac.macports.org/wiki/UsingTheRightCompiler). Since you're not having a `configure` phase you need to make sure yourself that this happens. Often the `makefile` PG can be very useful for this.

2021-12-10 12:23 UTC, herbygillot commented
> @herbygillot this port is not [UsingTheRightCompiler](https://trac.macports.org/wiki/UsingTheRightCompiler). Since you're not having a `configure` phase you need to make sure yourself that this happens. Often the `makefile` PG can be very useful for this.

Good points - fixed.

2021-12-10 14:18 UTC, mascguy approved these changes

2021-12-10 14:19 UTC, merged

2021-12-10 16:46 UTC, ryandesign commented
Next time please make two separate commits, one to rearrange the portfile's whitespace and the other to make the functional changes. Otherwise, it can be difficult, looking at a single combined commit, to discern what the functional changes are.