julia: update to 1.7.0
macports/macports-ports pull request #13376
Opened 2021-12-15 20:58 UTC by tramir

#### Description

###### Type(s)
Update to 1.7.0

###### Tested on

macOS 12.0.1
Xcode- none
Command line tools: 13.1

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

2021-12-15 21:35 UTC, essandess commented
This looks good to me, thank you @tramir. Would a MacPorts person please kick off the CI to make sure it builds?

2021-12-16 14:07 UTC, mascguy commented
Mircea, welcome to MacPorts, and thank you for your first contribution!

> This looks good to me, thank you @tramir. Would a MacPorts person please kick off the CI to make sure it builds?

Done.

2021-12-16 14:08 UTC, mascguy approved these changes

2021-12-16 14:42 UTC, reneeotten requested changes
please add `https://trac.macports.org/ticket/64214` to the body of the commit message so that the Trac ticket about this update will be closed automatically

2021-12-16 14:44 UTC, mascguy commented
> please add `https://trac.macports.org/ticket/64214` to the body of the commit message so that the Trac ticket about this update will be closed automatically

Mircea, you can add this as the second line of your commit message. So it should be updated to be:

```
julia: update to 1.7.0
Fixes: https://trac.macports.org/ticket/64214
```

2021-12-17 02:13 UTC, merged

2021-12-17 23:56 UTC, tramir commented
Sorry, was away for more than a day from my computer. I updated the comment, but I don't know if it'll make it into master (I'm more than a novice in terms of git/Github).