bitlbee: update to @3.6.1
macports/macports-ports pull request #14621
Opened 2022-04-19 06:49 UTC by barracuda156

#### Description

Update to @3.6.1, change master_sites to Github.

###### Type(s)

- [ ] bugfix
- [x ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

2022-04-19 13:30 UTC, reneeotten requested changes
a few comments below and I notice that GitHub thinks that there are conflicting files, so you should probably `rebase` with "master" and resolve any possible conflicts it might tell you about

2022-04-19 13:30 UTC, reneeotten commented on irc/bitlbee/Portfile
> +master_sites        https://github.com/bitlbee/bitlbee/archive/refs/tags/
if you want to do this you should instead use the [`github` PG](https://guide.macports.org/index.html#reference.portgroup.github) which will do all kinds of things for you automatically.

2022-04-19 13:30 UTC, reneeotten commented on irc/bitlbee/Portfile
> +# universal_variant   no
please don't comment out lines if not needed anymore, just remove them

2022-04-19 13:30 UTC, reneeotten commented on irc/bitlbee/Portfile
>  platforms           darwin
this is the default value for `platforms` since MacPorts v2.7 so the line can/should be removed

2022-04-19 13:59 UTC, barracuda156 commented
> a few comments below and I notice that GitHub thinks that there are conflicting files, so you should probably `rebase` with "master" and resolve any possible conflicts it might tell you about

@reneeotten The port was updated by @ryandesign some hours before and that was not yet in the master, so I did not see any changes. It looks like he used an earlier version, so it may be worth updating it still.
But I think he should decide that.

2022-04-19 14:15 UTC, barracuda156 commented
> the port is still `nomaintainer` so you can certainly feel free to update the port; you can do that in this PR. Just rebase your branch with `master`, do the update and then force-push to this PR.

@reneeotten Alright, I can do that tomorrow once back to workstation.

2022-04-19 15:21 UTC, closed without merging

2022-04-20 17:19 UTC, barracuda156 commented
@ryandesign Thank you for clarification! Surely, no need to use 3.6-1 then.