tdb: update to @1.4.6
macports/macports-ports pull request #14647
Opened 2022-04-21 01:26 UTC by barracuda156

#### Description

`tdb` has been forgotten. Update been requested here: https://trac.macports.org/ticket/45436
However there was an issue reported in the trac ticket, which may not have been fixed. Could someone take a look, please?

###### Type(s)

- [ ] bugfix
- [ x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

2022-04-21 01:33 UTC, barracuda156 commented
Hmm, the bot fails on this:
```
./configure: line 20: /opt/local/bin/python3.9: No such file or directory
```
How come it has no `python3.9`?

2022-04-21 02:51 UTC, reneeotten requested changes

2022-04-21 02:51 UTC, reneeotten commented on databases/tdb/Portfile
> +checksums           md5     10046f5068c4b25c5beabaf0378b0289 \
please remove oudated checksums`md5` and `sha1`

2022-04-21 02:52 UTC, reneeotten commented
> How come it has no `python3.9`?

because you don't declare a dependency on it?

2022-05-23 00:48 UTC, ryandesign commented
> However there was an issue reported in the trac ticket, which may not have been fixed. Could someone take a look, please?

You can see by trying to run one of the installed programs that the problem reported in the ticket still exists:

```
$ tdbbackup
dyld: Library not loaded: /opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports-ryandesign-fork_databases_tdb/tdb/work/tdb-1.4.6/bin/default/libtdb.dylib
  Referenced from: /opt/local/bin/tdbbackup
  Reason: image not found
Abort trap: 6
```

It's unfortunate that the developers of this software appear to have zero interest in addressing even the most basic of Mac-related build issues.

I have some further fixups to make to this port and will see if I can add a workaround for this problem.

2023-08-13 11:31 UTC, reneeotten commented
let's close this PR as it hasn't had any activity for more than a year now, and wait for @ryandesign to make the changes he mentions here

2023-08-13 11:31 UTC, closed without merging