miniupnpc: update to @2.2.3
macports/macports-ports pull request #14657
Opened 2022-04-22 03:21 UTC by barracuda156

#### Description

Update `miniupnpc` to @2.2.3

###### Type(s)

- [ ] bugfix
- [ x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10.6 (10A190)
Xcode 3.2

2022-04-22 21:00 UTC, barracuda156 commented
@mascguy @kencu These is no maintainer. If no one objects, could someone push it?

2022-04-23 02:34 UTC, barracuda156 commented
> I'm sorry I didn't see this before.
> 
> When you are building things in MacPorts using cmake, a very large amount of MacPorts configuration is set up using the cmake PortGroup.
> 
> So instead of adding the cmake build dependency, and probably instead of manually changing the install path of the include files, what you do is use the PortGroup
> 
> ```
> PortGroup cmake 1.1
> ```
> 
> give that a try instead of your depends_build and patch, and let's see how it works out!

@kencu Thank you for responding. I tried, but it failed without a patch:
```
Install the project...
/opt/local/bin/cmake -P cmake_install.cmake
-- Install configuration: "MacPorts"
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/cmake/miniupnpc/miniupnpc-private.cmake
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/libminiupnpc.a
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/cmake/miniupnpc/libminiupnpc-static.cmake
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/cmake/miniupnpc/libminiupnpc-static-macports.cmake
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/libminiupnpc.2.2.3.dylib
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/libminiupnpc.17.dylib
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/libminiupnpc.dylib
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/cmake/miniupnpc/libminiupnpc-shared.cmake
-- Installing: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot/opt/local/lib/cmake/miniupnpc/libminiupnpc-shared-macports.cmake
CMake Error at cmake_install.cmake:131 (file):
  file INSTALL cannot find
  "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/miniupnpc-2.2.3/miniupnpc.h":
  No such file or directory.


make: *** [install/fast] Error 1
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/build'
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/build" && /usr/bin/make -w install/fast INSTALLPREFIX=/opt/local CC="/usr/bin/gcc-4.2 -Os -DNDEBUG -I/opt/local/include -arch ppc" DESTDIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_miniupnpc/miniupnpc/work/destroot 
Exit code: 2
```

2022-04-23 15:04 UTC, reneeotten commented
@barracuda156 please do not remove the PR checklist when you submit a PR. Instead do check off the thing you actually did (and ideally you should do of course all of them) so that it is clear how well tested things are.

2022-04-29 14:40 UTC, barracuda156 commented
> @barracuda156 please do not remove the PR checklist (here and in others) when you submit a PR. Instead do check off the thing you actually did (and ideally you should do of course all of them) so that it is clear how well tested things are.

@reneeotten Thank you, I won’t be removing it. (Here it is a mere update of the version with no tweaks aside of fixing includes linking, therefore I thought it is redundant. The single patch is trivial.)

2022-05-07 09:51 UTC, barracuda156 commented
@reneeotten @mascguy @kencu If everyone happy, maybe we could push it?

2022-05-07 11:59 UTC, reneeotten requested changes
Not sure about the patch - seems unlikely that upstream messed this up...

2022-05-07 11:59 UTC, reneeotten commented on net/miniupnpc/Portfile
> +PortGroup			cmake 1.1
please align this properly

2022-05-07 11:59 UTC, reneeotten commented on net/miniupnpc/Portfile
> +revision            1
leave the revison at zero since you increased the version.

2022-05-07 14:04 UTC, barracuda156 commented
> Not sure about the patch - seems unlikely that upstream messed this up...

@reneeotten The patch is actually from upstream: https://github.com/miniupnp/miniupnp/commit/f82b0563a72e33800f5918ead68c41bcda1fd4c1
Referred by: https://github.com/miniupnp/miniupnp/issues/574#issuecomment-1086778404

2022-05-07 14:08 UTC, reneeotten commented
> > Not sure about the patch - seems unlikely that upstream messed this up...
> 
> 
> 
> @reneeotten The patch is actually from upstream: https://github.com/miniupnp/miniupnp/commit/f82b0563a72e33800f5918ead68c41bcda1fd4c1
> 
> Referred by: https://github.com/miniupnp/miniupnp/issues/574#issuecomment-1086778404


then please add that link at the top of the patchfile to reflect that fact.

2022-05-07 14:29 UTC, barracuda156 commented
> then please add that link at the top of the patchfile to reflect that fact.

@reneeotten Three requested changes made now.

2022-05-14 21:36 UTC, barracuda156 commented
@reneeotten @mascguy @kencu I think this should be ready to be pushed into the master.

2022-05-15 11:41 UTC, mascguy approved these changes

2022-05-15 11:41 UTC, merged

2022-05-18 16:22 UTC, jmroot commented
> [miniupnp/miniupnp#574 (comment)](https://github.com/miniupnp/miniupnp/issues/574#issuecomment-1086778404)

Lack of a .pc file as mentioned in that issue is a serious problem. Some dependents are now unable to find the library.