swi-prolog-devel: Updated to version 8.5.11
macports/macports-ports pull request #14772
Opened 2022-05-06 14:19 UTC by JanWielemaker

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.3.1 21E258 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-05-06 17:04 UTC, reneeotten requested changes

2022-05-06 17:04 UTC, reneeotten commented on lang/swi-prolog-devel/Portfile
>  conflicts           swi-prolog swi-prolog-lite
the `swi-prolog-lite` port doesn't exist anymore - removed in 5b78527791d23667665d3b639be4fe9d9703bb88. Can you please remove that port from the `conflicts` line here?

2022-05-07 10:00 UTC, merged

2022-05-07 13:36 UTC, JanWielemaker commented
> [Remove conflict with deleted port](https://github.com/macports/macports-ports/pull/14772/commits/57827cab15b1b4fca8b468756d54c88ee5dd8595)

Thanks Ryan!

P.s.  Surely the wrong place to address this.    I'm using a Linux shell script to generate these PRs.  That uses `openssl rmd160 < tar-file` to generate the digest.  That failed after upgrade to Ubuntu 22.04 because the `rmd160` is deprecated and now requires some option to use it anyway.    Is this picked up somewhere in the Macport community?

2022-05-07 13:39 UTC, ryandesign commented
I've noted the rmd160 deprecation here: https://trac.macports.org/ticket/63885 but nothing has been done yet about removing its use from MacPorts.