ffmpeg, ffmpeg-devel: add dependency and enable libvidstab
macports/macports-ports pull request #15084
Opened 2022-06-07 21:15 UTC by townba

* add port libvidstab 1.1.0 with patch (essentially identical to
  [this patch](https://github.com/Homebrew/formula-patches/blob/master/libvidstab/fix_cmake_quoting.patch))
* add dependency to ffmpeg and ffmpeg-devel and enabled for GPL 2+

Closes: https://trac.macports.org/ticket/59561

#### Description

[Vidstab](https://github.com/georgmartius/vid.stab) is used to smooth
and stabilize video.

* [FFmpeg filters documentation](https://ffmpeg.org/ffmpeg-filters.html#vidstabdetect-1)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.4 21F79 arm64
Command Line Tools 13.4.0.0.1.1651278267

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2022-06-07 22:08 UTC, townba commented
Changed to only affect `ffmpeg-devel`.

2022-06-08 01:05 UTC, reneeotten requested changes
@townba a few small comments

2022-06-08 01:05 UTC, reneeotten commented on multimedia/libvidstab/Portfile
> +revision            1
this should start at `0`

2022-06-08 01:05 UTC, reneeotten commented on multimedia/libvidstab/Portfile
> +
please add `github.tarball_from releases` (if upstream provides those) or, alternatively `github.tarball_from archive`. You will need to recalculate the checksums, after cleaning the port locally with `sudo port clean --all libvidstab`

2022-06-08 01:05 UTC, reneeotten commented on multimedia/libvidstab/Portfile
> +platforms           darwin
this is the default since MacPorts 2.7 - please remove the `platforms` line

2022-06-08 01:05 UTC, reneeotten commented on multimedia/libvidstab/Portfile
> +
no need for newline

2022-06-08 13:05 UTC, merged