Tentative fix for issue 63741 (plugin referencing builddir paths)
macports/macports-ports pull request #15100
Opened 2022-06-09 11:26 UTC by RJVB

This patches the paths post-hoc; I cannot reproduce the issue myself
so have not been able to find a true fix (and the current patch is a
no-op for me).

Fixes: https://trac.macports.org/ticket/63741
- [X ] bugfix

###### Tested on
OS X 10.9.5

###### Verification 
Have you

- [X ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X ] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

2022-06-09 23:19 UTC, ryandesign requested changes
> followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?

The commit message needs to be changed to conform to the guidelines.

2022-06-09 23:19 UTC, ryandesign commented on audio/audacity/Portfile
> +    version         3.0.2.129 ; revision 1
Syntax error.
```suggestion
    version         3.0.2.129
    revision        1
```

2022-06-09 23:19 UTC, ryandesign commented on audio/audacity/Portfile
>  set python_bin      ${prefix}/bin/python3.7
Python 3.10 is preferred today. Can that version be used instead?
```suggestion
                    port:python310 \
                    port:cctools
set python_bin      ${prefix}/bin/python3.10
```

2022-06-09 23:19 UTC, ryandesign commented on audio/audacity/Portfile
> +    if {${subport} eq "${name}"} {
Quotes are not needed.
```suggestion
    if {${subport} eq ${name}} {
```

2022-06-09 23:19 UTC, ryandesign commented on audio/audacity/Portfile
> +    if {${subport} eq "${name}" && ![variant_isset wxsystem]} {
```suggestion
    if {${subport} eq ${name} && ![variant_isset wxsystem]} {
```

2022-06-10 17:23 UTC, RJVB commented
On Thursday June 09 2022 16:20:07 Ryan Schmidt wrote:

>Syntax error.

Nope, that's perfectly valid syntax.

>Python 3.10 is preferred today. Can that version be used instead?

I don't know and I'd rather leave trying it to my successor. One of the embedded components uses a python-based build system and IMHO it should be possible to the instruct the port to "use any python3 that's installed" (like it would be with perl5).

>Quotes are not needed.

No but they are in the other subport tests against composite names. I'm keeping the quotes for consistency (and because I don't want to have to remember when to use them and when not).

2023-08-28 16:03 UTC, pmetzger commented
This has now been sitting in the queue for well over a year. I would propose we close it unless someone wants to finish it soon.

2023-08-28 16:06 UTC, mascguy commented
> This has now been sitting in the queue for well over a year. I would propose we close it unless someone wants to finish it soon.

That's fine, we can always resurrect it if there's interest.

2023-08-28 16:07 UTC, closed without merging