macos-trash: new port
macports/macports-ports pull request #15225
Opened 2022-06-27 18:48 UTC by halostatue

#### Description

This is a Swift implementation of a command to move files and folders to the MacOS trash.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 arm64
Xcode 13.4.1 13F100

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2022-06-27 20:35 UTC, halostatue commented
I’m not understanding why the checksum matching failed.

```console
DEBUG: Calculated (rmd160) is 0fc3fbf74364226cf9e8b90bc8fbc1edb509260e
  The correct checksum line may be:
  Error: Checksum (rmd160) mismatch for macos-trash-1.2.0.tar.gz
  checksums           rmd160  0fc3fbf74364226cf9e8b90bc8fbc1edb509260e \
 DEBUG: Calculated (sha256) is c4472b5c8024806720779bc867da1958fe871fbd93d200af8a2cc4ad1941be28
                      sha256  c4472b5c8024806720779bc867da1958fe871fbd93d200af8a2cc4ad1941be28 \
  Error: Checksum (sha256) mismatch for macos-trash-1.2.0.tar.gz
                      size    2986
  DEBUG: Calculated (size) is 2986
```

I had copied the output from the previous build into the current state of the Portfile (`ca17bb6`), verified the result with the appropriate commands, and it’s still failing.

2022-06-28 09:16 UTC, reneeotten requested changes
For the checksum failures: perhaps you added the "github.tarball_from" statement later and checked the checksums without cleaning the port first? Try doing "sudo port clean --all" in the Portfile directory and try again to get the checksums afterwards.

2022-06-28 09:16 UTC, reneeotten commented on sysutils/macos-trash/Portfile
> +name                macos-trash
this is set already from the "github.setup" line

2022-06-28 09:16 UTC, reneeotten commented on sysutils/macos-trash/Portfile
> +platforms           darwin
this is the default since MacPorts v2.7, so can be removed

2022-06-28 09:16 UTC, reneeotten commented on sysutils/macos-trash/Portfile
> +maintainers         @halostatue
If possible please also add (obfuscated) e-mail and "openmaintainer"

2022-06-28 15:12 UTC, halostatue commented
I’ve made the changes (not yet committed or pushed), but am not seeing any errors with the hashes on my machine.

As a side note, is there a `.noarch` or `.universal` archive? This always builds universal x86_64 / arm64, so seeing this in the output:

```
--->  Attempting to fetch macos-trash-1.2.0_0.darwin_21.arm64.tbz2 from https://packages.macports.org/macos-trash
```

Suggests that, even though the build package is *small* (~30k on the pre-built GitHub releases), there will be two copies of it.

Is there anything I can put in the Portfile that will (a) grab the pre-built release from GitHub releases and/or (b) ensure that there’s only one archive built for this by the buildbots?

2022-06-28 15:23 UTC, halostatue commented
My error. Somehow, the first amended commit did not include the updated hashes. It does now, and it should all build correctly.

2022-06-29 03:31 UTC, halostatue commented
@reneeotten @mascguy 

The latest failure (macOS-10.15) is related to something in the target repo’s `Package.swift`:

```swift
// swift-tools-version:5.5
import PackageDescription

let package = Package(
	name: "trash",
	platforms: [
		.macOS(.v10_10)
	],
	products: [
		.executable(
			name: "trash",
			targets: [
				"trash"
			]
		)
	],
	targets: [
		.executableTarget(name: "trash")
	]
)
```

This produces the error (edited for readability):

```console
…/work/macos-trash-1.2.0: error: package at '…/work/macos-trash-1.2.0' is using Swift tools version 5.5.0 but the installed version is 5.3.0
```

I don’t know Swift well enough to know if we can tell macOS 10.15 to install Swift tools 5.5.0 on the build server, nor do I know Portfile construction well enough to know if we can apply a patch only for some OS versions. What it interesting is that the `Package.swift` and the repo indicate that there is compatibility back to macOS 10.10 (with versions through 10.13 requiring the [Swift runtime support libraries](https://support.apple.com/kb/DL1998).

I don’t know if this means that a binary built on macOS 12 would be backwards compatible to 10.10 (with 10.10, 10.11, 10.12, and 10.13 requiring an additional download before it works), or if we should continue the 10.14 limit that I have put into place based on `mint`. Do you have any suggestions?

2022-06-29 16:11 UTC, mascguy commented
> The latest failure (macOS-10.15) is related to something in the target repo’s `Package.swift`:
> [...]
> I don’t know Swift well enough to know if we can tell macOS 10.15 to install Swift tools 5.5.0 on the build server, nor do I know Portfile construction well enough to know if we can apply a patch only for some OS versions. What it interesting is that the `Package.swift` and the repo indicate that there is compatibility back to macOS 10.10 (with versions through 10.13 requiring the [Swift runtime support libraries](https://support.apple.com/kb/DL1998).

We can definitely help you, relative to patches for certain macOS releases. (Though the less we have to do, the better.)

> I don’t know if this means that a binary built on macOS 12 would be backwards compatible to 10.10 (with 10.10, 10.11, 10.12, and 10.13 requiring an additional download before it works), or if we should continue the 10.14 limit that I have put into place based on `mint`. Do you have any suggestions?

Worst-case, we can start with 10.14+ compatibility, and then tackle earlier macOS releases in a subsequent PR.

Unfortunately I'm a bit light on Swift knowledge at this point, so I can't (yet) offer much relative to that.

@reneeotten / anyone, thoughts on all of this?

2022-06-29 16:15 UTC, mascguy commented
On a semi-related note, we do have an existing port that provides similar functionality: `trash`.

Though I'm not trying to discourage you from seeing this through. And if nothing else, it would be good for all of us to gain more Swift knowledge. So perhaps it's still a worthwhile exercise.

Thoughts...?

2022-06-29 16:39 UTC, halostatue commented
> On a semi-related note, we do have an existing port that provides similar functionality: trash.

The underlying code for that has not been updated in four years. It *does* more than `macos-trash`. ObjC isn’t going away anytime soon, but `macos-trash` is more recently maintained.

I’m not sure which of these is better, but thought it would be worthwhile to add this.

2022-06-29 16:41 UTC, mascguy commented
> The underlying code for that has not been updated in four years. It _does_ more than `macos-trash`. ObjC isn’t going away anytime soon, but `macos-trash` is more recently maintained.
> 
> I’m not sure which of these is better, but thought it would be worthwhile to add this.

Yeah definitely, so let's see this through!

2022-07-03 05:33 UTC, ryandesign commented
> As a side note, is there a .noarch or .universal archive? This always builds universal x86_64 / arm64, so seeing this in the output:

Yes, MacPorts supports both noarch and universal archives. The former is not applicable here since this software is not noarch.

> ```
> --->  Attempting to fetch macos-trash-1.2.0_0.darwin_21.arm64.tbz2 from https://packages.macports.org/macos-trash
> ```
> Suggests that, even though the build package is small (~30k on the pre-built GitHub releases), there will be two copies of it.

Yes, in its current form, there will.

> Is there anything I can put in the Portfile that will (a) grab the pre-built release from GitHub releases

The full facilities of the Tcl programming language are available to you in a Portfile so you can implement almost anything. However, we would not wish to use binaries built by others unless there is no alternative. MacPorts is first and foremost a build-from-source-ourselves system.

> and/or (b) ensure that there’s only one archive built for this by the buildbots?

We want to build multiple archives, but they should not be the same; they should differ by architecture. You should have the port provide whatever flags, environment variables, or even patches are necessary to convince this build system to build only for the architectures MacPorts wants it to build for (i.e. enable the universal variant and build for `${configure.universal_archs}` when a universal build is possible* and the variant is set, and build for `${configure.build_arch}` otherwise). If this software only works on x86_64 and arm64, indicate that using the `supported_archs` keyword.

\* Even if the port says to create a universal variant, MacPorts won't do so if a universal build is not possible on the user's particular OS/arch combination.

2022-07-03 05:42 UTC, ryandesign commented
> I don’t know Swift well enough to know if we can tell macOS 10.15 to install Swift tools 5.5.0 on the build server

As far as I can tell, Swift 5.5.0 is in Xcode 13.0, which requires macOS 11.3 or later. However, a user on macOS 11 may not necessarily have upgraded to Xcode 13; they might be using Xcode 12.x. The xcodeversion portgroup can be used to require a particular Xcode version on a particular macOS version.

> I don’t know if this means that a binary built on macOS 12 would be backwards compatible to 10.10 (with 10.10, 10.11, 10.12, and 10.13 requiring an additional download before it works),

I'm not familiar with this project, but that could be. If so, unfortunately MacPorts does not really support that scenario; we would have to take the minimum build machine OS version as the minimum runtime machine OS version, even if the project could actually run on an earlier OS. One idea for how we might better support that in the future is described in https://trac.macports.org/ticket/60878.

> or if we should continue the 10.14 limit that I have put into place based on `mint`. Do you have any suggestions?

I'm not familiar with mint, but if this project requires Swift 5.5.0 as it appears to, then it requires macOS 11.3 or later and on macOS 11 the Xcode version should be verified as well.

2022-07-04 01:00 UTC, halostatue commented
Thanks, @ryandesign. I have adjusted this to build according to what you have suggested. It *does* restrict to macOS 11+ and Xcode 13, as suggested.

2022-07-04 18:18 UTC, mascguy commented
> Thanks, @ryandesign. I have adjusted this to build according to what you have suggested. It *does* restrict to macOS 11+ and Xcode 13, as suggested.

That's a bit of a bummer, as it greatly limits where this can be used.

Does upstream's code truly require Swift 5.5, and/or Big Sur...?

2022-07-04 18:28 UTC, halostatue commented
@mascguy Unless we were to patch the code, the answer is sort of yes. In [sindresorhus/macos-trash:Package.swift](https://github.com/sindresorhus/macos-trash/blob/main/Package.swift), there is a line `// swift-tools-version:5.5`, which was causing the build failures on macOS 10.15.

I don’t know Swift well enough, but if we change that to `swift-tools-version:5.3` and then loosen the added in this update of the Portfile, we might be able to make it compile on 10.15 again, but I’m not sure what *other* version changes might be needed otherwise. As I understand it, the `-arch` flag was added with Xcode 12 (see [macports/macports-ports:devel/mint/Portfile:46](https://github.com/macports/macports-ports/blob/master/devel/mint/Portfile#L46)). So we might be able to make it work with earlier versions, if we can suppress the `+universal` variant in earlier versions. Again, this is a suspicion, but we could probably make this work with any version of Swift 5 (which I think takes us back to Xcode 10 or Xcode 11 and corresponding versions), but it comes down to "I don’t know".

We could also ask Sindre Sorhus (the author of `macos-trash`) if they know any better.

2022-07-06 18:58 UTC, mascguy commented
> @mascguy Unless we were to patch the code, the answer is sort of yes. In [sindresorhus/macos-trash:Package.swift](https://github.com/sindresorhus/macos-trash/blob/main/Package.swift), there is a line `// swift-tools-version:5.5`, which was causing the build failures on macOS 10.15.
> 
> I don’t know Swift well enough, but if we change that to `swift-tools-version:5.3` and then loosen the added in this update of the Portfile, we might be able to make it compile on 10.15 again, but I’m not sure what _other_ version changes might be needed otherwise. As I understand it, the `-arch` flag was added with Xcode 12 (see [macports/macports-ports:devel/mint/Portfile:46](https://github.com/macports/macports-ports/blob/master/devel/mint/Portfile#L46)). So we might be able to make it work with earlier versions, if we can suppress the `+universal` variant in earlier versions. Again, this is a suspicion, but we could probably make this work with any version of Swift 5 (which I think takes us back to Xcode 10 or Xcode 11 and corresponding versions), but it comes down to "I don’t know".
> 
> We could also ask Sindre Sorhus (the author of `macos-trash`) if they know any better.

I don't want to over-complicate this, particularly if there's a good chance that it simply does require Big Sur and later. So up to you.

@ryandesign , your thoughts? Is this worth the effort at this point, or should we go ahead and merge as-is?

2022-07-13 17:25 UTC, mascguy commented
Let's start with the port as-is, given that we're not yet sure whether supporting on 10.15 and earlier is feasible.

And thanks so much for your contribution Austin!

2022-07-13 17:25 UTC, merged

2022-07-13 17:51 UTC, halostatue commented
No problem. It was quite fun. It’s been years since I’ve used tcl.