duktape: update to 2.7.0
macports/macports-ports pull request #15549
Opened 2022-08-01 00:07 UTC by barracuda156

#### Description

Update to 2.7.0.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-08-15 22:13 UTC, barracuda156 commented
@mascguy Guess this is good to merge. Checks pass, no maintainer.

2022-08-31 01:04 UTC, reneeotten requested changes
it looks like the library name changed from compared to the previous version, if that's the case you should likely revbump the port that declares a dependency on this one, i.e., `policykit`. Please verify.

2022-08-31 12:49 UTC, barracuda156 commented
> it looks like the library name changed compared to the previous version, if that's the case you should likely revbump the port that declares a dependency on this one, i.e., `policykit`. Please verify.

@reneeotten I have a PR for its update in fact: https://github.com/macports/macports-ports/pull/15550
All checks pass too.

2022-08-31 17:28 UTC, mascguy commented
Need to hold on this, until we've validated https://github.com/macports/macports-ports/pull/15550

2022-08-31 18:08 UTC, mascguy commented
Tested both `duktape` and `policykit` on a few older macOS releases - 10.7, 10.9, 10.11, and 10.12 - and looks good. Merging both.

2022-08-31 18:08 UTC, mascguy approved these changes

2022-08-31 18:08 UTC, merged

2022-08-31 18:42 UTC, barracuda156 commented
@mascguy Great!