netcdf: do not use gcc-4.2 on PPC
macports/macports-ports pull request #15744
Opened 2022-08-15 21:42 UTC by barracuda156

Fixes: https://trac.macports.org/ticket/65672

#### Description

On PPC: blacklist `*gcc-4.*`.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-08-16 07:49 UTC, barracuda156 commented
@tenomoto macos-12 check successful, macos-11 check cancelled, why is that?

2022-08-20 14:43 UTC, kencu commented
this error has nothing to do with ppc, I believe. most likely fails with all older gccs that do not support redefinition of typedefs, on any system

2022-08-20 14:44 UTC, kencu requested changes
see if this needs to be applied to all older gccs please, not ppc-specific

2022-08-31 18:58 UTC, barracuda156 commented
> see if this needs to be applied to all older gccs please, not ppc-specific

@kencu I will check it now.

2022-08-31 19:40 UTC, barracuda156 commented
@kencu @mascguy Is this a correct value for Clang? We need to avoid using Xcode 3.2.x clang on 10.6.x (in addition to gcc-4.2).

2022-08-31 19:52 UTC, kencu commented
here is a table with more information that you ever wanted to know about clang versions:

https://trac.macports.org/wiki/XcodeVersionInfo#MacOSX10.6

2022-08-31 19:55 UTC, kencu commented
looking at that, your clang 400 cutoff should be OK. That lets 10.7's through, and blocks all the earlier ones.

2022-08-31 23:26 UTC, mascguy approved these changes

2022-08-31 23:26 UTC, merged