flac: fixes for PPC
macports/macports-ports pull request #15763
Opened 2022-08-17 02:36 UTC by barracuda156

Fixes: https://trac.macports.org/ticket/64610

#### Description

PR only affects PPC systems:
– Disables a broken Doxygen.
– Fixes a build failure on Rosetta due to Intel assembler being used.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-08-17 07:16 UTC, kencu commented
you’ve been disabling doxygen all over the place, but I don’t see that you ever tried the proper fix we suggested of binwrapping the doxygen binaries instead. You should try that first.

It’s simple. See:

https://github.com/macports/macports-ports/blob/f3ef4cd21fd307e941e7deadd638fb81516a5589/devel/cmake/Portfile#L58

if it doesn’t work, fine. But it almost always does work, and you can revert all your doxygen disabling patches.

2022-08-17 08:29 UTC, barracuda156 commented
@kencu Thank you! I will try that.

2022-08-18 06:49 UTC, kencu commented
I just installed ppc doxygen on my 10.4 Tiger PPC system and it works perfectly, and passes 99% of the test suite as well.

So whatever is wrong on your system with doxygen, it is not a ppc issue generally, nor is it apparently an issue with building with gcc7.

2022-08-18 06:53 UTC, kencu requested changes
doxygen works fine on ppc, Tiger at least verified.

2022-08-18 07:55 UTC, barracuda156 commented
@kencu Thank you for checking. I will check on Leopard soon, once I’m back to TW.
I have seen doxygen failures quite a number of times, but you are right, it may be specific to either OS or compiler, not all PPC.

2022-10-11 01:00 UTC, barracuda156 commented
@kencu Removed Doxygen part here, since the thing is fixed. Rosetta fix still needed (it tries using Intel assembler due to physical cpu).

2022-10-12 06:30 UTC, barracuda156 commented
@mascguy Safe to merge.

2022-11-05 00:16 UTC, barracuda156 commented
@kencu Can this be merged? I removed Doxygen part, but specifying `--build` still needed, otherwise it fails:
```
ld: warning: in ia32/.libs/libFLAC-asm.a, file was built for unsupported file format which is not the architecture being linked (ppc)
Undefined symbols:
…
ranlib: archive member: .libs/libFLAC-static.a(cpu_asm.o) cputype (7) does not match previous archive members cputype (18) (all members must match)
…
```

2022-11-05 07:50 UTC, merged