opensc: fix build for <11
macports/macports-ports pull request #15923
Opened 2022-08-26 18:42 UTC by barracuda156

Fixes: https://trac.macports.org/ticket/65709

#### Description

Addition to the patch is from upstream, see: https://github.com/OpenSC/OpenSC/issues/2596
`gcc-4.2` fails to build the port, at least for PPC, blacklisted for that case.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-08-29 14:38 UTC, kencu requested changes
the gcc-4.2 failure is unlikely to be specific to powerpc. verify and generalize if so.

the added configure flag is unlike to be specific to poeerpc. verify and generalize if so

2022-08-29 16:17 UTC, barracuda156 commented
> the added configure flag is unlike to be specific to powerpc. verify and generalize if so

@kencu Perhaps it can be set for GCC builds, instead of powerpc, indeed. Given no one is complaining about Clang builds, it is not needed in those cases.

2022-08-29 16:59 UTC, barracuda156 commented
> the gcc-4.2 failure is unlikely to be specific to powerpc. verify and generalize if so.

I will try now.

2022-08-31 11:36 UTC, barracuda156 commented
So the missing definition error is expectedly present on 10.6 x86 too:
```
reader-pcsc.c: In function 'pcsc_to_opensc_error':
reader-pcsc.c:185: error: 'SCARD_E_NO_READERS_AVAILABLE' undeclared (first use in this function)
reader-pcsc.c:185: error: (Each undeclared identifier is reported only once
reader-pcsc.c:185: error: for each function it appears in.)
  CC       libopensc_la-card-flex.lo
make[3]: *** [libopensc_la-reader-pcsc.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src/libopensc'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19'
make: *** [all] Error 2
make: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19'
Command failed:  cd "/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/opensc-0.22.0" && /usr/bin/make -j6 -w all 
Exit code: 2
Error: Failed to build opensc: command execution failed
```

2022-08-31 11:42 UTC, barracuda156 commented
@kencu And you are right, `gcc-4.2` fails on Intel too:
```
cc1: error: unrecognized command line option "-Wno-unused-but-set-variable"
cc1: error: unrecognized command line option "-Wno-unused-but-set-variable"
make[3]: *** [opensc_notify-opensc-notify.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [opensc_notify-opensc-notify-cmdline.o] Error 1
cc1: warnings being treated as errors
opensc-explorer.c: In function ‘main’:
opensc-explorer.c:2475: warning: ‘multiple’ may be used uninitialized in this function
make[3]: *** [opensc-explorer.o] Error 1
make[3]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src/tools'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19'
make: *** [all] Error 2
make: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19'
Command failed:  cd "/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/opensc-0.22.0" && /usr/bin/make -j6 -w all 
Exit code: 2
Error: Failed to build opensc: command execution failed
```
P. S. It is perhaps also possible to cut out unsupported flags, but to build `opensc` it is a _must_ to have either newer GCC or Clang (`icu` is one of dependencies). So I guess blacklisting `*gcc-4.*` is fine.

2022-08-31 11:45 UTC, barracuda156 commented
Then, `gcc12` fails on this:
```
In file included from /usr/include/string.h:148,
                 from sm-iso.c:29:
In function 'prefix_buf',
    inlined from 'format_data' at sm-iso.c:234:7:
sm-iso.c:194:17: error: pointer may be used after 'realloc' [-Werror=use-after-free]
  194 |                 memcpy(p + 1, buf, buflen);
      |                 ^~~~~~
sm-iso.c:186:13: note: call to 'realloc' here
  186 |         p = realloc(*cat, buflen + 1);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
  CCLD     libsm.la
cc1: all warnings being treated as errors
make[3]: *** [sm-iso.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src/sm'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19'
make: *** [all] Error 2
```

2022-08-31 11:51 UTC, barracuda156 commented
Xcode Clang also fails on 10.6.8 Intel:
```
opensc-notify.c:193:32: error: unknown warning group '-Wunused-result', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Wunused-result"
                               ^
1 warning and 1 error generated.
make[3]: *** [opensc_notify-opensc-notify.o] Error 1
make[3]: *** Waiting for unfinished jobs....
1 warning generated.
make[3]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src/tools'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86Ports_security_opensc/opensc/work/OpenSC-OpenSC-c902e19'
make: *** [all] Error 2
```

2022-08-31 12:00 UTC, barracuda156 commented
@kencu Ok, I cannot figure out how to ban `llvm-gcc-4.2` on 10.6.8. This does not work:
```
compiler.blacklist-append *gcc-4.* {clang < 421}
```

2022-08-31 13:58 UTC, kencu commented
that looks very good, thanks.

2022-08-31 13:58 UTC, merged

2022-08-31 14:02 UTC, barracuda156 commented
@kencu Thank you for help with this!