ffcall: fix Rosetta build
macports/macports-ports pull request #15941
Opened 2022-08-29 12:05 UTC by barracuda156

Fixes: https://trac.macports.org/ticket/65736

#### Description

Fixes otherwise failing build on Rosetta. Passing arch flags is necessary, Macports does not handle it correctly here (see the ticket).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-08-29 14:32 UTC, kencu commented
so it passes the arch flags correctly with all other builds besides building as powerpc on snowleopard using rosetta?

that would be really weird.

probably it never passes the needed flags…if so, that requires a general fix, of course.

2022-08-29 14:35 UTC, kencu requested changes
verify whether proper flags are passed with other builds

2022-08-29 14:46 UTC, barracuda156 commented
@kencu Thank you! I guess you are right. I am just always cautious to extend fixes to general case unless it is clearly necessary.

By the way, we don’t know why sometimes cflags aren’t passed, right?

2022-08-29 15:44 UTC, kencu commented
You'd have to look into that... but that is the fix that needs doing, it would seem. There are a number of possible reasons, depending on the build system, but improperly written Makefiles seem to be 99% of them.

2022-08-29 16:49 UTC, barracuda156 commented
> verify whether proper flags are passed with other builds

@kencu So I bootstrapped Macports for 10.6.8 x86_64 and built `ffcall`. Arch flags do not get passed at certain points, but it does not cause errors, perhaps because Intel is a default arch.
```
make[1]: Entering directory `/opt/x86_64/var/macports/build/_opt_x86_64_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_ffcall/ffcall/work/libffcall-2.4/avcall'
case "darwin10.8.0" in \
	  cygwin* | mingw*) variant='-windows';; \
	  *) variant='';; \
	esac; \
	/usr/bin/gcc-4.2 -std=gnu99 -E `if test true = true; then echo '-DASM_UNDERSCORE'; fi` -I./../common - < ./avcall-x86_64${variant}-macro.S | grep -v '^ *#line' | grep -v '^#' | sed -e 's,% ,%,g' -e 's,\. ,.,g' -e 's,@ ,@,g' -e 's,//.*$,,' -e 's/##//g' > avcall-x86_64.s
/bin/sh ../libtool --mode=compile /usr/bin/gcc-4.2 -std=gnu99 -x none -c avcall-x86_64.s
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -x none -c avcall-x86_64.s  -fno-common -DPIC -o .libs/avcall-x86_64.o
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -x none -c avcall-x86_64.s -o avcall-x86_64.o >/dev/null 2>&1
rm -f avcall.lo avcall.o
ln avcall-x86_64.lo avcall.lo
if test -f avcall-x86_64.o; then ln avcall-x86_64.o avcall.o; fi
/bin/sh ../libtool --mode=compile /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I.. -I./.. -I/opt/x86_64/include -pipe -Os -arch x86_64 -fno-strict-aliasing -c ./avcall-libapi.c
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I.. -I./.. -I/opt/x86_64/include -pipe -Os -arch x86_64 -fno-strict-aliasing -c ./avcall-libapi.c  -fno-common -DPIC -o .libs/avcall-libapi.o
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I.. -I./.. -I/opt/x86_64/include -pipe -Os -arch x86_64 -fno-strict-aliasing -c ./avcall-libapi.c -o avcall-libapi.o >/dev/null 2>&1
/bin/sh ../libtool --mode=compile /usr/bin/gcc-4.2 -std=gnu99 -I./../common -I/opt/x86_64/include -pipe -Os -arch x86_64 -c ./avcall-structcpy.c
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -I./../common -I/opt/x86_64/include -pipe -Os -arch x86_64 -c ./avcall-structcpy.c  -fno-common -DPIC -o .libs/avcall-structcpy.o
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -I./../common -I/opt/x86_64/include -pipe -Os -arch x86_64 -c ./avcall-structcpy.c -o avcall-structcpy.o >/dev/null 2>&1
/bin/sh ../libtool --mode=compile /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I.. -I./.. -I/opt/x86_64/include -pipe -Os -arch x86_64 -c ./avcall-compat.c
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I.. -I./.. -I/opt/x86_64/include -pipe -Os -arch x86_64 -c ./avcall-compat.c  -fno-common -DPIC -o .libs/avcall-compat.o
libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I.. -I./.. -I/opt/x86_64/include -pipe -Os -arch x86_64 -c ./avcall-compat.c -o avcall-compat.o >/dev/null 2>&1
/bin/sh ../libtool --mode=link /usr/bin/gcc-4.2 -std=gnu99 -o libavcall.la -rpath /opt/x86_64/lib -no-undefined -export-symbols-regex '^avcall_|^__builtin_avcall$' -version-info 2:0:1 avcall.lo avcall-libapi.lo avcall-structcpy.lo avcall-compat.lo -L/opt/x86_64/lib -Wl,-headerpad_max_install_names -arch x86_64
libtool: link: /usr/bin/nm  .libs/avcall-x86_64.o .libs/avcall-libapi.o .libs/avcall-structcpy.o .libs/avcall-compat.o   | sed -n -e 's/^.*[	 ]\([BCDEGRST][BCDEGRST]*\)[	 ][	 ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/\1 _\2 \2/p' | sed '/ __gnu_lto/d' | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libavcall.exp
libtool: link: /usr/bin/grep -E -e "^avcall_|^__builtin_avcall$" ".libs/libavcall.exp" > ".libs/libavcall.expT"
libtool: link: mv -f ".libs/libavcall.expT" ".libs/libavcall.exp"
libtool: link: sed 's|^|_|' < .libs/libavcall.exp > .libs/libavcall-symbols.expsym
libtool: link: /usr/bin/gcc-4.2 -std=gnu99 -dynamiclib  -o .libs/libavcall.1.dylib  .libs/avcall-x86_64.o .libs/avcall-libapi.o .libs/avcall-structcpy.o .libs/avcall-compat.o   -L/opt/x86_64/lib  -Wl,-headerpad_max_install_names -arch x86_64   -install_name  /opt/x86_64/lib/libavcall.1.dylib -compatibility_version 3 -current_version 3.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libavcall-symbols.expsym
libtool: link: (cd ".libs" && rm -f "libavcall.dylib" && ln -s "libavcall.1.dylib" "libavcall.dylib")
libtool: link: ar cru .libs/libavcall.a  avcall-x86_64.o avcall-libapi.o avcall-structcpy.o avcall-compat.o
libtool: link: ranlib .libs/libavcall.a
libtool: link: ( cd ".libs" && rm -f "libavcall.la" && ln -s "../libavcall.la" "libavcall.la" )
make[1]: Leaving directory `/opt/x86_64/var/macports/build/_opt_x86_64_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_ffcall/ffcall/work/libffcall-2.4/avcall'
```
[ffcall_x86.log](https://github.com/macports/macports-ports/files/9446391/ffcall_x86.log)

2022-08-29 16:58 UTC, barracuda156 commented
@kencu Apparently this part in Makefiles omits arch flags:
```
avcall-i386.lo : avcall-i386.s
	$(LIBTOOL_COMPILE) $(CC) -x none -c avcall-i386.s

avcall-i386.s : $(srcdir)/avcall-i386-macro.S
	$(CPP) $(ASPFLAGS) -I$(srcdir)/../common - < $(srcdir)/avcall-i386-macro.S | grep -v '^ *#line' | grep -v '^#' | sed -e 's,% ,%,g' -e 's,\. ,.,g' -e 's,@ ,@,g' -e 's,//.*$$,,' -e 's/##//g' > avcall-i386.s
```
```
avcall-powerpc.lo : avcall-powerpc.s
	$(LIBTOOL_COMPILE) $(CC) -x none -c avcall-powerpc.s

avcall-powerpc.s : $(srcdir)/avcall-powerpc-aix.s $(srcdir)/avcall-powerpc-linux-macro.S $(srcdir)/avcall-powerpc-macos.s $(srcdir)/avcall-powerpc-sysv4-macro.S
	case "$(OS)" in \
	  aix*) syntax=aix;; \
	  linux* | netbsd* | openbsd*) syntax=linux;; \
	  macos* | darwin*) syntax=macos;; \
	  *) syntax=sysv4;; \
	esac; \
	case $${syntax} in \
	  macos) \
	    grep -v '\.machine' $(srcdir)/avcall-powerpc-$${syntax}.s > avcall-powerpc.s || exit 1 ;; \
	  linux | sysv4) \
	    $(CPP) $(ASPFLAGS) $(srcdir)/avcall-powerpc-$${syntax}-macro.S | grep -v '^ *#line' | grep -v '^#' | sed -e 's,% ,%,g' -e 's,//.*$$,,' > avcall-powerpc.s || exit 1 ;; \
	  *) \
	    cp $(srcdir)/avcall-powerpc-$${syntax}.s avcall-powerpc.s || exit 1 ;; \
	esac
```

2022-08-29 19:23 UTC, kencu commented
oh, interesting. it is just directly compiling assembly files, so no arch flags are getting added.

well, that is something to ponder and work through. What CFLAGS or CXXFLAGS or any flags are supposed to be added when assembly files are compiled? You'd have to do a bit of Sherlock Holmes on that question.

At least archflags matching the assembly, it would seem... at least on darwin.

2022-08-30 20:13 UTC, barracuda156 commented
@kencu @ryandesign Could you advise me if using `CC="${configure.cc} [get_canonical_archflags cc]"` is correct for a general case, considering it includes FAT builds as well?

2023-05-28 14:59 UTC, mascguy commented
> @kencu @ryandesign Could you advise me if using `CC="${configure.cc} [get_canonical_archflags cc]"` is correct for a general case, considering it includes FAT builds as well?

I'm not proficient enough with universal builds to say with certainty, but that looks correct in principle.

Anyone else?

2023-05-28 15:03 UTC, barracuda156 commented
> > @kencu @ryandesign Could you advise me if using `CC="${configure.cc} [get_canonical_archflags cc]"` is correct for a general case, considering it includes FAT builds as well?
> 
> I'm not proficient enough with universal builds to say with certainty, but that looks correct in principle.
> 
> Anyone else?

@mascguy From what I saw in other ports, it should be.

2023-05-28 19:33 UTC, barracuda156 commented
@mascguy 
UPD. Oh, this is 10.6 ppc-only. Why do we even care about building universal? It does not support `ppc64` (neither 10A190 nor Rosetta), and building for ppc+x86_64 is badly broken generally, I have been there and gave up, and no one else apparently even tried.

2023-05-28 19:54 UTC, mascguy commented
> @mascguy 
> UPD. Oh, this is 10.6 ppc-only. Why do we even care about building universal? It does not support `ppc64` (neither 10A190 nor Rosetta), and building for ppc+x86_64 is badly broken generally, I have been there and gave up, and no one else apparently even tried.

If there's not an easy fix, then no worries. But perhaps @MarcusCalhoun-Lopez might have some ideas.

2023-05-29 00:58 UTC, MarcusCalhoun-Lopez commented
This worked for me:
```
PortGroup           muniversal 1.1
```
...
```
foreach arch {arm64 x86_64 i386 ppc ppc64} {
    # `libtool` compiles assembly with CC but without any way to set compiler flags                                                                                                                                                             
    # this is a problem if ${configure.build_arch} is not the same as the compiler default architecture                                                                                                                                         
    # and for universal builds                                                                                                                                                                                                                  
    configure.args.${arch}-append   CC="${configure.cc} -arch ${arch}"
}
```

2023-05-29 01:01 UTC, barracuda156 commented
> This worked for me:
> 
> ```
> PortGroup           muniversal 1.1
> ```
> 
> ...
> 
> ```
> foreach arch {arm64 x86_64 i386 ppc ppc64} {
>     # `libtool` compiles assembly with CC but without any way to set compiler flags                                                                                                                                                             
>     # this is a problem if ${configure.build_arch} is not the same as the compiler default architecture                                                                                                                                         
>     # and for universal builds                                                                                                                                                                                                                  
>     configure.args.${arch}-append   CC="${configure.cc} -arch ${arch}"
> }
> ```

@MarcusCalhoun-Lopez Let me try.

2023-06-06 11:18 UTC, barracuda156 commented
@mascguy Given this is Rosetta-only (10A190 does not require this, but is fine with it), maybe mergeable?

2023-06-06 13:56 UTC, MarcusCalhoun-Lopez commented
There are two separate issues here.
One just affects PowerePC Darwin 10 using Rosetta (incorrect value of `uname` causes inclusion of avcall-i386.s in the list of assembly files).
The other one affects **all** universal builds (libtool does not respect `-arch` when compiling assembly).
My first suggestion only fixed one of these issues.
The following should fix both problems.
I would be happy to open a PR if that would make testing easier.

```
PortGroup           muniversal 1.1
```
...
```
foreach arch {arm64 x86_64 i386 ppc ppc64} {
    # `libtool` compiles assembly with CC but without any way to set compiler flags                                                                                                                                                         
    # this is a problem if ${configure.build_arch} is not the same as the compiler default architecture                                                                                                                                     
    # and for universal builds                                                                                                                                                                                                              
    configure.args.${arch}-append   CC="${configure.cc} -arch ${arch}"
}

# https://trac.macports.org/ticket/65736                                                                                                                                                                                                    
platform darwin 10 powerpc {
    configure.args-append \
	--build=powerpc-apple-darwin${os.major} \
}
```

2023-06-06 14:36 UTC, barracuda156 commented
@MarcusCalhoun-Lopez Sure, let me close this in favor of your PR.

2023-06-06 14:36 UTC, closed without merging

2023-06-06 14:46 UTC, MarcusCalhoun-Lopez commented
#18994 is an attempt at a general fix.