py-mupdf: Submission
macports/macports-ports pull request #15971
Opened 2022-09-01 22:45 UTC by essandess

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2022-09-02 02:48 UTC, reneeotten requested changes
from the CI log you'll see it cannot run "swig", likely a missing dependency. Are you positive this worked locally in trace-mode? One small comment besides that the Portfile looks good to me!

2022-09-02 02:48 UTC, reneeotten commented on python/py-mupdf/Portfile
> +    livecheck.type  none
this is the default set by the "python" PG so can/should be removed.

2022-09-06 17:43 UTC, mascguy commented
Rebased against master, to pick up `mupdf` update.

2022-09-06 17:56 UTC, mascguy commented
While CI is succeeding, this cannot be merged until `mupdf` is fixed. See comment: https://github.com/macports/macports-ports/pull/15970#issuecomment-1238475692

2022-09-07 00:29 UTC, essandess commented
Rebased.

2022-09-07 19:45 UTC, mascguy commented
Just a friendly reminder that the following needs to be fixed, before this can be merged:
* [65799 - mupdf @1.20.3: builds fail across-the-board: expected ';' after top level declarator](https://trac.macports.org/ticket/65799)

2022-09-07 22:20 UTC, essandess commented
> Just a friendly reminder that the following needs to be fixed, before this can be merged:
> 
> * [65799 - mupdf @1.20.3: builds fail across-the-board: expected ';' after top level declarator](https://trac.macports.org/ticket/65799)

I don't know how to fix that, and don't understand the issue. Builds locally across the board for me, and also here in the CI.

2022-09-07 22:26 UTC, mascguy commented
> > Just a friendly reminder that the following needs to be fixed, before this can be merged:
> > 
> > * [65799 - mupdf @1.20.3: builds fail across-the-board: expected ';' after top level declarator](https://trac.macports.org/ticket/65799)
> 
> I don't know how to fix that, and don't understand the issue. Builds locally across the board for me, and also here in the CI.

See my latest update on the ticket. But in short, we need to disable optimization, when compiling generated resources.

2022-09-08 00:22 UTC, mascguy commented
> > I don't know how to fix that, and don't understand the issue. Builds locally across the board for me, and also here in the CI.
> 
> See my latest update on the ticket. But in short, we need to disable optimization, when compiling generated resources.

Unfortunately that doesn't fix the issue, so I'm not sure where to go from here. And since `mupdf` fails across-the-board on the buildbots, this port is blocked until the issue has been fixed.

Since you updated the port, perhaps you can jump in and help try to figure this out? Please?  :-)

2023-04-05 01:07 UTC, reneeotten commented
Closed by dadf9ffdd85684357d2aa94250683fa108533d91

2023-04-05 01:07 UTC, closed without merging