libxml2: update to 2.10.0
macports/macports-ports pull request #16179
Opened 2022-09-19 14:16 UTC by szhorvat

- Update libxml2 to 2.10.0
 - Fixes https://trac.macports.org/ticket/65865

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C504

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-09-19 14:19 UTC, szhorvat commented
Please check the `post-destroot` section. It's not clear to me what this is for and whether it needs any changes after the update.

2022-09-20 00:52 UTC, reneeotten requested changes

2022-09-20 00:52 UTC, reneeotten commented on textproc/libxml2/Portfile
>  # Please keep the version of the libxml2 and py-libxml2 ports the same.
as stated here, please make sure to update the `py-libxml2` to the same version. I notice that the`livecheck` for that port doesn't show the latest version, but it's there... So please add the update for the Python bindings to this PR as well and ideally fix the `livecheck` in that port.

2022-09-20 06:52 UTC, szhorvat commented
@reneeotten I would prefer to close this PR and leave it instead to @ryandesign who understands this port better, and just let me know that he is working on it: https://trac.macports.org/ticket/65865

2022-09-20 06:52 UTC, closed without merging

2022-09-20 06:54 UTC, ryandesign commented
I didn't see this PR before doing my own update, which is ready to go and will be committed shortly. If you open a PR for a ticket, be sure to put the PR URL into the ticket and add the `haspatch` keyword so that anyone seeing the ticket will know it's already being dealt with.

2022-09-20 07:05 UTC, szhorvat commented
Sorry about that, I'll cross link future issues in both directions. Thanks for doing this update in this case. This way it was completed faster, as my PR seems to have more than one issue.