FAudio: Update to 22.09.01
macports/macports-ports pull request #16220
Opened 2022-09-24 16:50 UTC by Gcenx

#### Description

Updated to the latest release and block below 10.7 due to a hard requirement on SDL 2.24

###### Type(s)

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2022-09-24 16:56 UTC, reneeotten commented on audio/FAudio/Portfile
> +}
instead of doing this please just restrict it the to latest version that still works

2022-09-24 16:57 UTC, reneeotten requested changes
see above

2022-09-24 17:10 UTC, Gcenx commented
I can't do that due to `libsdl2`
https://github.com/macports/macports-ports/blob/a1bf4959c541fe8a00e6ef016c23a9fea810bbe8/devel/libsdl2/Portfile#L37-L51

Once `libsdl2` ether resolves this or adds fallback to an older version it's not possible to have a fallback.

2022-09-24 17:33 UTC, kencu commented
it's only a 10 minute project to do that libsdl2 fallback for 10.6, so I hope someone does it before too many ports are just blocked on 10.6 instead.

Perhaps I'll do it myself later today. And then the one for 10.4 - 10.5 might even be possible, finally, after all these years.

2022-09-24 18:39 UTC, mascguy commented
> it's only a 10 minute project to do that libsdl2 fallback for 10.6, so I hope someone does it before too many ports are just blocked on 10.6 instead.
> 
> Perhaps I'll do it myself later today. And then the one for 10.4 - 10.5 might even be possible, finally, after all these years.

Oh Gawd Yes, please fix 10.6!  :-)

2022-09-25 06:13 UTC, kencu commented
> Yes, please fix 10.6! :-)

done

2022-09-25 06:16 UTC, Gcenx commented
> done

I’ll update this PR in a coupe of hours I need to sleep lol

2022-09-25 15:28 UTC, Gcenx commented
Added the fallback to 22.08 below 10.7

2022-09-25 17:35 UTC, mascguy approved these changes

2022-09-25 17:35 UTC, merged