iso-codes: update to python 3.10
macports/macports-ports pull request #16256
Opened 2022-09-30 00:37 UTC by lukaso

#### Description

Update `iso-codes` to python 3.10.

###### Type(s)

- [ ] bugfix
- [1] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 arm64
Xcode 14.0.1 14A400

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-09-30 02:03 UTC, reneeotten requested changes
same as in your other PR -  no need to increase the `revision` since it's only a build dependency

2022-09-30 09:30 UTC, lukaso commented
> same as in your other PR - no need to increase the `revision` since it's only a build dependency

Done.

2022-09-30 15:55 UTC, mascguy approved these changes
LGTM. @ryandesign ?

2022-10-01 02:56 UTC, reneeotten approved these changes

2022-10-02 06:07 UTC, merged