qbe: new Portfile
macports/macports-ports pull request #16384
Opened 2022-10-18 04:59 UTC by alterae

#### Description

Add qbe: a compiler backend (https://c9x.me/compile/)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 arm64
Xcode 14.0.1 14A400

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2022-10-18 06:06 UTC, herbygillot commented on devel/qbe/Portfile
> +maintainers         @alterae
Usually the maintainers section is written within curly braces, and `openmaintainer` appended:
```suggestion
maintainers         {@alterae openmaintainer}
```

`openmaintainer` means that other port maintainers are allowed to make minor updates to this port, unless there is a specific reason why it should be you and only you.

2022-10-18 06:07 UTC, herbygillot commented on devel/qbe/Portfile
> +platforms           darwin
`platforms darwin` is implicit and no longer needs to be included in Portfiles. You can delete this line.

2022-10-18 06:08 UTC, herbygillot commented
Hey @alterae, thanks for this submission. Some minor comments above.  Also, when you make your changes, please squash everything back into the same commit with the same commit message format as you have now.

2022-10-19 03:09 UTC, reneeotten requested changes

2022-10-19 03:09 UTC, reneeotten commented on devel/qbe/Portfile
> +distfiles           qbe-${version}.tar.xz
you shouldn't need to explicitly specify this, instead add the line `use_xz yes` which specifies the archive type and MacPorts should take care of the rest

2022-10-19 03:09 UTC, reneeotten commented on devel/qbe/Portfile
> +maintainers         {@alterae} \
typically this would contain both an obfuscated e-mail address and GitHub handle

2022-10-19 03:09 UTC, reneeotten commented on devel/qbe/Portfile
> +use_configure       no
without a `configure` command it's up to the Portfile author to make sure the port will be [UsingTheRightCompiler](https://trac.macports.org/wiki/UsingTheRightCompiler) and associated MacPorts' flags. Oftentimes the `makefile` PortGroup can help/automate this. 

Admittedly, I haven't looked into the specifics of this package but please take a look at the above-mentioned link to make sure the correct stuff is happening.

2023-08-13 12:00 UTC, reneeotten commented
@alterae do you have the intention to follow-up on the comments above so that we could move this PR forward to a point where it could get merged?

2023-08-28 20:13 UTC, pmetzger commented
@alterae Howdy! I think we could get this merged with just a couple more small changes. Are you in a position to do it?

2023-10-24 18:57 UTC, pmetzger commented
@alterae Howdy! This could be easily merged, but it doesn't appear that you've been paying attention to your Github alerts. If you don't respond in a few days, I'm afraid we'll have to close this request for now.

2023-11-12 00:09 UTC, closed without merging