libbtbb: update to current upstream, 2022-08-26
macports/macports-ports pull request #16538
Opened 2022-11-01 06:03 UTC by barracuda156

#### Description

Update, claim maintainership (it is my port initially).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2022-11-01 08:24 UTC, barracuda156 commented
Wait a bit, I need to add Cmake config installation.

2022-11-04 10:24 UTC, reneeotten requested changes
one minor suggestion

2022-11-04 10:24 UTC, reneeotten commented on devel/libbtbb/Portfile
>  homepage            https://github.com/greatscottgadgets/libbtbb
this is set by the github PG

2022-11-05 06:04 UTC, barracuda156 commented on devel/libbtbb/Portfile
>  homepage            https://github.com/greatscottgadgets/libbtbb
Fixed!

2022-11-07 21:47 UTC, barracuda156 commented
@reneeotten This also should be mergeable.

2022-11-15 04:52 UTC, barracuda156 commented
@reneeotten Could we merge this, so that `ubertooth` build can be confirmed?

2022-11-23 17:57 UTC, merged