virtualenvwrapper_select: new port
macports/macports-ports pull request #16822
Opened 2022-11-26 15:21 UTC by bashu

#### Description

Add port select support virtualenvwrapper

Closes: https://trac.macports.org/ticket/41187

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 12.6.1 21G217 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2022-11-26 15:32 UTC, bashu commented
I skipped: `port test ...` cuz there are no tests for this port

2022-11-26 16:18 UTC, reneeotten requested changes

2022-11-26 16:18 UTC, reneeotten commented on python/virtualenvwrapper_select/Portfile
> +revision            1
revision should be zero

2022-11-26 16:22 UTC, bashu commented on python/virtualenvwrapper_select/Portfile
> +revision            1
fixed

2022-11-27 15:15 UTC, reneeotten approved these changes

2022-11-27 15:16 UTC, merged