Drop compiler_blacklist_versions.  Availability of threads.h is deter…
macports/macports-ports pull request #16913
Opened 2022-12-07 08:48 UTC by JanWielemaker

…mined

by CMake and acted upon.

As discussed in https://github.com/macports/macports-ports/pull/16907#discussion_r1041650332

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2022-12-12 11:24 UTC, barracuda156 commented
I guess you rather mention the port in the title. Otherwise it given an impression you wanna drop the PG itself.

2022-12-13 00:15 UTC, reneeotten requested changes

2022-12-13 00:15 UTC, reneeotten commented on lang/swi-prolog-devel/Portfile
> -PortGroup           compiler_blacklist_versions 1.0
that is okay, but then you will need remove the lines (38-39 or so) where you do the compiler.blacklist stuff as well.

2022-12-18 12:46 UTC, pmetzger commented
The commit message here is in the wrong format; that needs to be fixed. It has to start "swi-prolog-devel:" and probably needs to be turned into multiple lines.

2022-12-18 17:25 UTC, JanWielemaker commented
Ok.   I see I'll drop this PR.    As the next release is ready, should I first make a PR for this, make a PR to also do the release update (with one or two commits?)

2022-12-18 17:25 UTC, closed without merging

2022-12-19 01:31 UTC, reneeotten commented
Thanks @JanWielemaker - you can do it in the same PR/commit.