py-log-symbols: new port
macports/macports-ports pull request #16978
Opened 2022-12-15 09:22 UTC by bashu

#### Description

Colored symbols for various log levels for Python 

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.2 21G320 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2022-12-15 09:23 UTC, bashu commented
Instead of tests
```python
>>> from log_symbols import LogSymbols #Enum
>>> print(LogSymbols.SUCCESS.value) # ✔
✔
>>> print(LogSymbols.INFO.value) # ℹ
ℹ
>>> print(LogSymbols.WARNING.value) #
⚠
>>> print(LogSymbols.ERROR.value) # ✖
✖
```

2022-12-23 05:46 UTC, reneeotten requested changes

2022-12-23 05:46 UTC, reneeotten commented on python/py-log-symbols/Portfile
> +supported_archs     noarch
add "platforms {darwin any}"

2022-12-30 10:12 UTC, reneeotten approved these changes

2022-12-30 10:12 UTC, merged