hjson_select, py-hjson: new port
macports/macports-ports pull request #16979
Opened 2022-12-15 12:14 UTC by bashu

#### Description

Hjson for Python

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.2 21G320 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2022-12-23 05:51 UTC, reneeotten requested changes
is this intended to be used as a library by other Python packages or is it a "program that is written in Python"? In the latter case we wouldn't need the other subports and the name could just be "hsjon" with a specified Python version and no need for the use of "select".

2022-12-23 05:51 UTC, reneeotten commented on python/py-hjson/files/py27-hjson
> +bin/hjson-2.7
remove this unused select file

2022-12-23 05:51 UTC, reneeotten commented on python/py-hjson/files/py34-hjson
> +bin/hjson-3.4
remove this unused select file

2022-12-23 05:51 UTC, reneeotten commented on python/py-hjson/files/py35-hjson
> +bin/hjson-3.5
remove this unused select file

2022-12-23 05:51 UTC, reneeotten commented on python/py-hjson/files/py36-hjson
> +bin/hjson-3.6
remove this unused select file

2022-12-23 05:51 UTC, reneeotten commented on python/py-hjson/files/setup.py.patch
> ++        packages=['hjson'],
why not install the tests?

2022-12-23 05:51 UTC, reneeotten commented on python/py-hjson/Portfile
> +
check for correct setting of "platforms" line

2022-12-30 11:03 UTC, bashu commented
> is this intended to be used as a library by other Python packages or is it a "program that is written in Python"?

Yes, this is a library and intended to be used by other python packages. hjson_select was removed too.

2022-12-31 02:02 UTC, reneeotten commented
thanks @bashu ; I'll merge this now. If in the future a "select" port is deemed useful that can be added.

2022-12-31 02:03 UTC, merged

2022-12-31 04:12 UTC, bashu commented
> If in the future a "select" port is deemed useful that can be added.

Absolutely