gegl, babl: fixes for PPC and <10.6 Intel
macports/macports-ports pull request #17411
Opened 2023-01-20 22:58 UTC by barracuda156

#### Description

This PR addresses a few bugs:

1. Invalid option in meson.build used for PPC (cannot be boolean): https://trac.macports.org/ticket/66233
2. No OpenCL on <10.6 Intel and any PPC (has been thrown away prior to release or not implemented at all).
3. Blacklisting GCC – no reason for that, GCC works fine. Moreover, on PPC it is the only compiler.
4. Vapigen is broken on PPC, related default variants should not be used there.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-03-12 16:15 UTC, reneeotten requested changes
@barracuda156 : one comment but these changes look nicely restricted to older systems. There has been sufficient time for maintainers to review this so I'm fine with merging after the few issues are addressed.

2023-03-12 16:15 UTC, reneeotten commented on graphics/gegl/Portfile
> +if {${os.major} < 10 || (${os.major} == 10 && ${build_arch} eq "ppc")} {
missing check for os.platform

2023-04-16 15:05 UTC, reneeotten commented
@barracuda156 is this only fixing build failure and thus doesn't require a "revision" increase? Other than that I'll merge; this has been around in the queue (too) long (enough) by now...

2023-04-17 00:38 UTC, barracuda156 commented on graphics/gegl/Portfile
> +if {${os.major} < 10 || (${os.major} == 10 && ${build_arch} eq "ppc")} {
I will it now, sorry, missed.

2023-04-17 06:49 UTC, barracuda156 commented
> @barracuda156 is this only fixing build failure and thus doesn't require a "revision" increase? Other than that I'll merge; this has been around in the queue (too) long (enough) by now...

@reneeotten Will finish this today. Found an improvement over what we have here: `gegl` allows to use `libsdl1` as an option, we can use it for old systems.

2023-04-17 09:12 UTC, barracuda156 commented
@reneeotten Okay, once CI pass, this should be ready.

2023-04-17 23:49 UTC, barracuda156 commented
@reneeotten Something left to fix or good to merge?

2023-04-18 00:08 UTC, merged