psblas3: new port in math
macports/macports-ports pull request #17565
Opened 2023-02-02 19:16 UTC by barracuda156

Signed-off-by: Sergey Fedorov <vital.had@gmail.com>

#### Description

New port: https://github.com/sfilippone/psblas3

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-02-02 19:47 UTC, barracuda156 commented
This is not something I have touched in this PR:
```
Installing dependency (40 of 40) 'mpich-default' with variants '+gcc12' ... [FAIL]
```

2023-02-05 13:39 UTC, reneeotten requested changes

2023-02-05 13:39 UTC, reneeotten commented on math/psblas3/Portfile
> +                    --with-metis="${prefix}" \
this suggest you should add an explicit dependency on the "metis" port

2023-02-05 16:06 UTC, barracuda156 commented
@reneeotten Added dependency on `metis`, thank you.

2023-02-07 20:49 UTC, reneeotten approved these changes

2023-02-07 20:50 UTC, merged