#### Description qtcurve : upgrade to 1.9.0.117 (main, Qt5 and extra subports)
macports/macports-ports pull request #17692
Opened 2023-02-13 22:54 UTC by RJVB

This brings the style up to date with upstream, supporting up to and
including Qt 5.15 . The qtcurve-extra subport now also installs the
translation files.

The GTk2 subport is updated to 1.9.0.66 .

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

OS X 10.9.5

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-02-14 03:59 UTC, kencu commented
thanks!

Any idea what's going on the the CI system errors?

2023-02-14 12:13 UTC, RJVB commented
No. TBH, I'm so used about getting linting and timeout errors that I no longer even try to find my way through the interface digging for an error in way too many logs. I see here that it says it failed to install dependencies but getting the actual failures seems to be beyond my skills?!

I did notice a few things I missed converting my own version to the one for here. Bummer, installing the translations requires a KF5 framework, somehow that detail slipped my mind :(

2023-08-13 13:04 UTC, reneeotten requested changes

2023-08-13 13:04 UTC, reneeotten commented on kde/qtcurve/Portfile
> +        PortGroup   kf5 1.1
this is an unknown PortGroup ; perhaps you have this only locally?

2023-08-13 13:04 UTC, reneeotten commented on kde/qtcurve/Portfile
> +                            port:kf5-ki18n
this dependency does not exist

2024-01-07 21:38 UTC, pmetzger commented
This has been sitting since August without any answer for @reneeotten's concerns. I'm closing it for now. It can always be reopened if there is interest.

2024-01-07 21:38 UTC, closed without merging