gallery-dl: make yt-dlp variant default, adopt
macports/macports-ports pull request #18058
Opened 2023-03-22 16:24 UTC by akierig

#### Description

adopts gallery-dl and sets a default variant for improved compatibility

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 arm64
Xcode 14.2 14C18

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-03-22 16:32 UTC, akierig commented
apologies @Ionic @i0ntempest there was an errant MPV commit in the branch that didn't get moved out which is why you all were assigned.

2023-03-25 22:32 UTC, reneeotten reviewed
I suppose the reason for this as a variant is that it pulls in `ffmpeg` which is a fairly large package. Is there a reason one would want to make this the default? 

If that's the decision is made, then I suspect it doesn't make sense anymore either to have a `ffmpeg` variant as that is already a runtime dependency of the `yt-dlp` and would be thus installed already.

Finally, as a guideline one should ideally not make non-functional changes (e.g., ordering of lines) in the same commit with functional changes (or perhaps at all) to make sure diffs are readable and only contain relevant things.

2023-03-25 23:27 UTC, reneeotten commented
okay, so then the only change is that you added yourself as maintainer. Why do you then still increase the "revison" - I guess that's an leftover from your initial commit? Also please undo the non-functional changes.

2023-03-26 12:53 UTC, reneeotten requested changes

2023-03-26 12:53 UTC, reneeotten commented on net/gallery-dl/Portfile
> +maintainers         {@akierig fastmail.de:akierig} \
trailing backslash; this is missing "openmaintainer" (please keep those on the same line anyway

2023-03-26 18:12 UTC, reneeotten approved these changes

2023-03-26 18:12 UTC, merged