p5-dbd-pg: add support for building with postgresql15
macports/macports-ports pull request #18092
Opened 2023-03-26 07:55 UTC by jrabinow

#### Description

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`? NO TESTS
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-03-27 00:01 UTC, reneeotten requested changes

2023-03-27 00:01 UTC, reneeotten commented on perl/p5-dbd-pg/Portfile
> +        default_variants    +postgresql15
it looks like this PR changes the default variant; in that case, one should increase the "revision".

2023-03-28 07:54 UTC, jrabinow commented
Done. Sorry about that, I wasn't sure if libraries should bump the revision in this scenario

2023-03-30 01:34 UTC, reneeotten approved these changes

2023-03-30 01:34 UTC, merged