py-mupdf: new port (PyMuPDF)
macports/macports-ports pull request #18164
Opened 2023-04-02 13:25 UTC by markmentovai

#### Description

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.3 22E252 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-04-02 22:19 UTC, reneeotten commented
this should replace then #15971?

2023-04-02 22:23 UTC, reneeotten requested changes

2023-04-02 22:23 UTC, reneeotten commented on python/py-mupdf/Portfile
> +    livecheck.type  none
this is the default set by the python PG and should thus be removed

2023-04-02 22:23 UTC, reneeotten commented on python/py-mupdf/Portfile
> +platforms           darwin
this is the default and can therefore be removed

2023-04-02 22:23 UTC, reneeotten commented on python/py-mupdf/Portfile
> +    depends_lib     port:mupdf
please change both specification to depends_*-append as not to overwrite dependencies added by the python PG

2023-04-03 01:34 UTC, markmentovai commented
https://github.com/macports/macports-ports/pull/18164#issuecomment-1493453663:
> this should replace then #15971?

Yes.

I don’t love doing that, but #15971 seems to have lost traction with no activity in 7 months, and by now, the version of PyMuPDF that it seeks to add is already out of date.

I addressed all review feedback. Thanks, Renee.

2023-04-04 01:38 UTC, reneeotten commented on python/py-mupdf/Portfile
> +
please do "proper" line continuations for the long description so that lines in the Portfiles don't extend beyond 80 characters.

2023-04-04 01:39 UTC, reneeotten commented on python/py-mupdf/Portfile
> +    depends_lib-append port:mupdf
please make sure that the "four spaces" indentation is correct in the lines above

2023-04-05 01:06 UTC, reneeotten approved these changes

2023-04-05 01:06 UTC, merged