py-jfricas: new port (version 1.0.0)
macports/macports-ports pull request #18823
Opened 2023-05-26 17:37 UTC by catap

#### Description

This is Jupyter kernel for Fricas.

This PR requires https://github.com/macports/macports-ports/pull/18819 

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2023-05-26 17:38 UTC, catap commented
After I've installed both PR I was able to use Fricas from MacPorts' Jupyter Notebook:

<img width="1173" alt="Screenshot 2023-05-26 at 19 35 56" src="https://github.com/macports/macports-ports/assets/37775/12e04b28-b359-4871-9450-a45b586adfdb">

2023-05-30 22:53 UTC, catap commented
@mascguy and may I ask you to review this one? Since hunchentoot are merged it works ;)

2023-05-30 22:56 UTC, mascguy commented on python/py-jfricas/Portfile
> +        set dst ${destroot}${frameworks_dir}/Python.framework/Versions/${python.branch}/share/jupyter/kernels/fricas
Rather than hard-coding `${frameworks_dir}/Python.framework/Versions/${python.branch}`, use `${python.prefix}`.

2023-05-30 22:57 UTC, mascguy commented on python/py-jfricas/Portfile
> +        fs-traverse item ${destroot}${frameworks_dir}/Python.framework/Versions/${python.branch} {
Same comment as previous

2023-05-30 22:58 UTC, mascguy commented on python/py-jfricas/files/kernel.json
> +    "%FRAMEWORKS_DIR%/Python.framework/Versions/%PYVERSION%/Resources/Python.app/Contents/MacOS/Python",
Simplify this similarly, using a placeholder for `${python.prefix}`.

2023-05-30 23:37 UTC, mascguy requested changes
Simplify via the comments

2023-05-30 23:44 UTC, catap commented
@mascguy here it is

2023-05-30 23:45 UTC, mascguy approved these changes

2023-05-31 00:15 UTC, merged