libcommuni: new port in devel
macports/macports-ports pull request #19284
Opened 2023-07-01 11:39 UTC by barracuda156

#### Description

New port.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-07-01 17:49 UTC, reneeotten requested changes

2023-07-01 17:49 UTC, reneeotten commented on devel/libcommuni/Portfile
> +revision            0
please add `github.tarball_from archive`

2023-07-01 18:32 UTC, barracuda156 commented on devel/libcommuni/Portfile
> +revision            0
Done

2023-07-02 10:11 UTC, barracuda156 commented
@reneeotten Anything else to amend or we are good on this one?

2023-07-02 11:30 UTC, reneeotten commented
would it be worthwhile to add variants for Qt5/Qt6? I'm pretty sure nobody who isn't using ancient systems would want to use Qt4 for anything anymore...

2023-07-02 13:09 UTC, barracuda156 commented
> would it be worthwhile to add variants for Qt5/Qt6? I'm pretty sure nobody who isn't using ancient systems would want to use Qt4 for anything anymore...

I can’t test that, but if you or someone interested to add those, please. On the other hand, it perhaps can be done in a separate PR, whenever someone gets time for that. At least Qt4 works fine on latest OS too.

2023-07-04 08:43 UTC, barracuda156 commented
@reneeotten I guess let us merge this first? Then anyone is welcome to add support for newer Qt versions.

2023-07-05 11:33 UTC, merged