fortran-polyroots: new port
macports/macports-ports pull request #19336
Opened 2023-07-05 03:58 UTC by barracuda156

#### Description

New port: https://github.com/jacobwilliams/polyroots-fortran

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-07-05 11:40 UTC, reneeotten requested changes

2023-07-05 11:40 UTC, reneeotten commented on fortran/fortran-polyroots/Portfile
> +github.setup        jacobwilliams polyroots-fortran ef5433e943eeb3edec7f5fce62ad7a09412cb23d
please use the released version as it is tagged. No tags please unless a -devel version as per the usual guidelines.

2023-07-06 03:17 UTC, barracuda156 commented
@reneeotten This has been done.

2023-07-06 19:17 UTC, reneeotten commented
> @reneeotten This has been done. Good to merge now?

as usual, it should set also "github.tarball_from archive". Didn't notice that last review...

If you make that change we can certainly merge!

2023-07-06 19:33 UTC, barracuda156 commented
> > @reneeotten This has been done. Good to merge now?
> 
> as usual, it should set also "github.tarball_from archive". Didn't notice that last review...
> 
> If you make that change we can certainly merge!

Well, done.

2023-07-06 19:41 UTC, merged