py-photomosaic: fix platforms
macports/macports-ports pull request #19696
Opened 2023-08-01 11:32 UTC by macportsraf

#### Description

This Portfile had `platforms any` but python modules should have `playforms {darwin any}`, so this pull request changes it.

The `port install -vst` failed because it failed for 

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G6032 x86_64
Xcode 11.3 11C29

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?

2023-08-02 18:15 UTC, reneeotten requested changes

2023-08-02 18:15 UTC, reneeotten commented on python/py-photomosaic/Portfile
> +revision            1
no need for a "revision" increase

2023-08-03 00:10 UTC, macportsraf commented on python/py-photomosaic/Portfile
> +revision            1
Thanks. I've put it back to 0.

2023-08-03 00:37 UTC, reneeotten approved these changes

2023-08-03 00:37 UTC, merged