py-pytorch: Update to version 2.0.1; Add Python 311
macports/macports-ports pull request #19712
Opened 2023-08-01 23:28 UTC by essandess

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.4.1 22F770820d arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-08-13 18:46 UTC, reneeotten requested changes
See lint error message:
```Error: Line 46 uses compiler.blacklist entry {clang >= 1400} {macports-clang-1[4-9]} which requires the compiler_blacklist_versions portgroup which has not been included```

2023-08-13 18:47 UTC, reneeotten commented on python/py-pytorch/Portfile
> +    }
this doesn't look right ; why can we not use the "normal" PEP517 build tools here instead of doing `pip` stuff in the destroot phase?

2023-08-20 19:21 UTC, mascguy commented
> See lint error message: `Error: Line 46 uses compiler.blacklist entry {clang >= 1400} {macports-clang-1[4-9]} which requires the compiler_blacklist_versions portgroup which has not been included`

Steve, please bypass CI for now - by adding `[skip ci]` in the commit message - until you're 100% certain that this is ready.

Based on the comments from @reneeotten - which I completely agree with - more work needs to be done. That includes the lint errors which Renee mentioned, which are absolutely legitimate... and need to be corrected before wasting any more CI cycles.

2023-09-21 22:02 UTC, pmetzger commented
Hi @essandess! It's been over a month and we haven't heard from you on this and the pull request doesn't pass the CI and you've neither explained nor fixed that. I'm going to close this for now. Feel free to request the pull again if it passes the CI or there's a good reason it doesn't.

2023-09-21 22:02 UTC, closed without merging