py-onnx: Update to version 1.14.0
macports/macports-ports pull request #19711
Opened 2023-08-01 23:26 UTC by essandess

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.4.1 22F770820d arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-08-13 18:48 UTC, reneeotten requested changes

2023-08-13 18:48 UTC, reneeotten commented on python/py-onnx/Portfile
> +    destroot.post_args
same comment as in the other PR ; the "normal" PEP517 build should work here I would think. What's the error you are trying to workaround here?

2023-08-28 19:27 UTC, pmetzger commented
@reneeotten Is this now commitable, or no?

2023-08-28 19:31 UTC, reneeotten commented
> @reneeotten Is this now commitable, or no?

I don't think so; there has been no response why the dance with "pip" is needed in the destroot phase compared to the usual stuff.

2023-08-29 11:47 UTC, essandess commented
I have other time conflicts and won't be able to address this for a bit.

The `destroot` code is copied from other `py-*` Portfiles that do this to install `.whl`'s created in build.

I'm not familiar enough with PEP517 to know if this has been superseded in Python 311, but it's there here and in many other Python ports (from which this is copied) because build creates a `.whl`.

2023-09-21 22:03 UTC, pmetzger commented
Hi @essandess! It's been some weeks and we haven't heard from you on this and the pull request doesn't pass the CI. I'm going to close this for now. Feel free to request the pull again if it passes the CI.

2023-09-21 22:03 UTC, closed without merging