py-pylint-mpl: update to version 0.16.1 and add Python 3.10-3.11
macports/macports-ports pull request #19722
Opened 2023-08-02 13:47 UTC by nilason

#### Description

py-pylint-mpl: update to version 0.16.1 and add Python 3.10, 3.11 support

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-08-02 14:32 UTC, lpsinger requested changes
pytest-mpl 0.16.1 requires Python >= 3.6.

2023-08-02 14:57 UTC, nilason commented
> pytest-mpl 0.16.1 requires Python >= 3.6.

As pytest 7.4 requires Python >=3.7, how about to set the lowest Python version to 3.7?

2023-08-02 14:59 UTC, nilason commented
> pytest-mpl 0.16.1 requires Python >= 3.6.

As pytest 7.4 requires Python >=3.7, how about to set the lowest Python version to 3.7?

2023-08-02 19:08 UTC, nilason commented
> > pytest-mpl 0.16.1 requires Python >= 3.6.
> 
> As pytest 7.4 requires Python >=3.7, how about to set the lowest Python version to 3.7?

Updated PR, removed Python 2.7.

2023-08-03 02:24 UTC, lpsinger approved these changes

2023-08-03 02:24 UTC, merged