py-pysal: update with new "family"-ports
macports/macports-ports pull request #19749
Opened 2023-08-04 09:07 UTC by nilason

#### Description

The PySAL (`py-pysal`) package has been refactored, it is now a wrapper package for a number of separate modules.

This PR updates py-pysal and adds the separate modules as new ports.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.6 21G646 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-08-04 10:47 UTC, nilason commented
Depends on #19719

2023-08-07 21:24 UTC, nilason commented
Oh dear, finally the CI builds succeeded! Please review!

2023-08-13 18:44 UTC, reneeotten requested changes
thanks @nilason for all your work on these ports! I've left a few comments - they all apply to pretty much every port in this PR.

2023-08-13 18:44 UTC, reneeotten commented on python/py-access/Portfile
> +    livecheck.type  none
this is the default set by the `python` PG and can thus be removed

2023-08-13 18:44 UTC, reneeotten commented on python/py-access/Portfile
> +github.setup        pysal access 1.1.9 v
we typically prefer to fetch Python ports from PyPI - is there a reason as to why you not do that here?

2023-08-13 18:44 UTC, reneeotten commented on python/py-momepy/Portfile
> +python.pep517_backend setuptools
this is the default and shouldn't be specified

2023-08-13 18:44 UTC, reneeotten commented on python/py-pysal/Portfile
> +github.tarball_from     tarball
why not `archive`? If it needs to be `tarball` then you can omit it, as that is the current default in the `github` PG

2023-08-13 18:44 UTC, reneeotten commented on python/py-spopt/Portfile
> +                    PYTHONPATH=${worksrcpath}/build/lib
these are the default set up by the `python` PG ; so you'll only need to retain `test.run yes`

2023-08-13 18:44 UTC, reneeotten commented on python/py-spopt/Portfile
> +                    port:py${python.version}-pytest \
this is added by default when setting `test.run yes` so the `pytest` dependency can be removed here

2023-08-13 18:44 UTC, reneeotten commented on python/py-spopt/Portfile
> +    livecheck.type  none
default

2023-08-15 17:42 UTC, nilason commented
> thanks @nilason for all your work on these ports! I've left a few comments - they all apply to pretty much every port in this PR.

I believe I have addressed all your points. I kept one port (py-spopt) installing from Github and therefore enabling the tests.

(Some other modules also did have tests, but they seemed unreliable.)

2023-08-18 01:03 UTC, reneeotten approved these changes

2023-08-18 01:03 UTC, merged

2023-08-18 01:04 UTC, reneeotten commented
thanks @nilason !

2023-08-18 19:00 UTC, nilason commented
@reneeotten Thank you!