gmp: update to 6.3.0
macports/macports-ports pull request #20313
Opened 2023-09-04 21:24 UTC by szhorvat

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 13.5.1 22G90 arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-09-04 21:26 UTC, szhorvat commented
Ran the tests both for the default and `+native` variants, they passed.

----

Removed the patch since it appeared to be for Apple Silicon support, but [the changelog](https://gmplib.org/gmp6.3) indicates that 6.3.0 provides this support.

----

With `+native`, there's a warning from the Portfile:

> No processor dependent assembly code being used. gmp might be slower.

I am not sure if this is still valid.

----

2023-09-09 14:57 UTC, reneeotten requested changes
also the "platforms" line is the default since MacPorts v1.7 so that line can/should be removed.

2023-09-09 14:57 UTC, reneeotten commented on devel/gmp/Portfile
>  revision                1
the "revision" field should be set to "0" when updating the version

2023-09-09 15:07 UTC, MarcusCalhoun-Lopez commented
I am afraid there are two issues with this pull request other than the one pointed out by @reneeotten.
The first is minor.
`triplet.cpu.arm64` should be changed to `applem1` (see https://gmplib.org/repo/gmp/rev/0d19622b27a9).

The second is that version 6.3.0 does not work on (very) old systems.
The problem seems to revolve around setting the correct language standard in `CC_FOR_BUILD` and/or `CFLAGS_FOR_BUILD`, but I still haven't had quite enough time to find a proper fix.

2023-09-09 15:41 UTC, szhorvat commented
At this point, I would hand this over to you @MarcusCalhoun-Lopez. I do not have the possibility to test on old systems. I'll close this PR since the changes are so minor that there's no reason to build on top of it (but if you want to, just reopen).

2023-09-09 15:41 UTC, closed without merging