pdbpp, deps: add python 3.9, 3.10, 3.11 variants
macports/macports-ports pull request #20462
Opened 2023-09-16 22:50 UTC by jrabinow

#### Description

PDB and all dependencies now have python3.9, 3.10 and 3.11 variants
dependents:
- python/py-fancycompleter/Portfile
- python/py-repl/Portfile
- python/py-wmctrl/Portfile

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 13.5.2 22G91 arm64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-09-17 23:27 UTC, reneeotten requested changes
please change to commit message; it should list the portnames and it's not a variant but subports that you are adding. 
You can combine names as in:
py{name1,name2,...}: add py3{9,10,11} subports"

2023-09-18 00:29 UTC, jrabinow commented
I had listed the individual ports in the commit message, just not on the same line. I thought it might be better to provide the reason for them all being in the same commit.

<img width="480" alt="Screenshot 2023-09-17 at 17 23 32" src="https://github.com/macports/macports-ports/assets/5642686/4554d5a2-31e0-42a6-b64d-13c7337d2bf6">

Hopefully the new commit message is an improvement, but I'm curious for the future if listing the dependencies on separate lines is a good idea or not. There can be a lot more than 4 ports changed, they won't always fit on one line.

re variants vs subports: good point, fixed that as well.

2023-09-18 03:23 UTC, reneeotten commented
well... there is no `pdbpp` port and now the commit message still doesn't fit on one line, so I am not a fan yet ;) Also, you can always have separate commits within the same PR to make sure it's clear they all go together.

2023-09-18 05:40 UTC, jrabinow commented
I feel that separate commits is a bit too process-oriented for my taste - I think the dependents fall under the "minor changes" listed in "subject" 4th bullet point of the commit guidelines.

I followed "subject" bullet point 3 and moved the dependents to the commit body, but if you could give me some context on if there's any automation or tools that do some kind of commit-parsing, I think the added process of separate commits would make more sense

2023-09-18 22:53 UTC, merged