proselint: update to python3.11
macports/macports-ports pull request #20460
Opened 2023-09-16 22:17 UTC by jrabinow

#### Description

proselint: update to python3.11

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 13.5.2 22G91 arm64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`? NO TRACE MODE
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-09-16 22:18 UTC, catap requested changes
You need also to increase revision because you've changed dependencies

2023-09-16 22:27 UTC, jrabinow commented
@catap sorry, done

2023-09-17 23:32 UTC, reneeotten reviewed
let's give @catap the change to look at this. While you're doing so @catap, can you please verify whether this is a `noarch` port and whether changing to `platforms {darwin any}` is warranted here?

2023-09-18 07:04 UTC, catap approved these changes

2023-09-18 22:54 UTC, merged