zsh-history-substring-search: Update to 1.1.0
macports/macports-ports pull request #20463
Opened 2023-09-17 01:58 UTC by TheRealKeto

#### Description

Update zsh-history-substring-search to its latest version, 1.1.0. Add notes on how to use the port.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2023-09-17 04:29 UTC, bashu commented
I approve, can be merged

2023-09-17 17:36 UTC, TheRealKeto commented
@herbygillot Mind merging this? Thanks.

2023-09-17 23:37 UTC, reneeotten requested changes

2023-09-17 23:37 UTC, reneeotten commented on sysutils/zsh-history-substring-search/Portfile
> +license             BSD-3-Clause
this is not a valid license for MacPorts, it should remain `BSD`

2023-09-17 23:45 UTC, reneeotten commented on sysutils/zsh-history-substring-search/Portfile
> +this change to take effect.
please use `\` at the end of the lines to let MacPort wrap the lines to the terminal width.

2023-09-18 03:25 UTC, reneeotten approved these changes

2023-09-18 03:25 UTC, merged