qt6: Add macdeployqt patch
macports/macports-ports pull request #20610
Opened 2023-09-27 20:14 UTC by jonaski

#### Description

Fixes deploying application libraries with .so extension such as glib gio modules, this also applies to gstreamer since macports currently uses an older version of gstreamer which uses .so extensions for plugins. See https://codereview.qt-project.org/c/qt/qtbase/+/507393

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-09-29 03:35 UTC, chrstphrchvz requested changes
The revision of qtbase should be incremented, correct?

2023-09-30 21:24 UTC, chrstphrchvz requested changes
See item “Wrap body text at 72 characters” on https://trac.macports.org/wiki/CommitMessages#guidelines

I have not tested the patch, but I would be okay with it especially since it is a backport. I am not a committer and cannot start the CI for this PR.

2023-09-30 21:24 UTC, chrstphrchvz commented on aqua/qt6/files/patch-qtbase-macdeployqt.diff
> ++++ b/src/tools/macdeployqt/shared/shared.cpp
`patch -p0` is used by default, so I think the prefix needs to be removed (see other qt6 patches).

```suggestion
--- src/tools/macdeployqt/shared/shared.cpp
+++ src/tools/macdeployqt/shared/shared.cpp
```

2023-10-02 23:08 UTC, pmetzger commented
I note that the CI is still broken.

2023-10-02 23:09 UTC, pmetzger commented
@chrstphrchvz Please let us know when you think this is in good shape.

2023-10-02 23:11 UTC, chrstphrchvz commented
> I note that the CI is still broken.

CI was not broken, it just doesn’t run automatically for someone who hasn’t already contributed to a repository.

2023-10-02 23:12 UTC, chrstphrchvz commented
> > I note that the CI is still broken.
> 
> CI was not broken, it just doesn’t run automatically for someone who hasn’t already contributed to a repository.

Never mind, you meant that the CI was still failing.

2023-10-03 01:02 UTC, chrstphrchvz approved these changes
The CI was able to build qt6-qtbase, which I believe is the only port affected by this PR. Any CI failures are the same as those in https://github.com/macports/macports-ports/pull/20562#issuecomment-1741568975. I think this is ready to merge.

2023-10-03 13:36 UTC, chrstphrchvz commented
I meant to check for this again before clicking “approve” but this still applies:

> See item “Wrap body text at 72 characters” on https://trac.macports.org/wiki/CommitMessages#guidelines

2023-10-04 13:24 UTC, merged