ldid-procursus: Restrict building on < OSX 10.13
macports/macports-ports pull request #20729
Opened 2023-10-05 21:35 UTC by TheRealKeto

Per upstream, there's no real reason for anyone to use this port on < OSX 10.13. The port is known to fail.

#### Description

###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.6 21G115 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2023-10-06 23:07 UTC, reneeotten commented
there are many package for which upstream states that it doesn't build/work on older OSes, while in fact MacPorts is perfectly able to do so. 

Is there a real issue here; in other words are there build failures that cannot be fixed or does it build but fail to run on these systems?

2023-10-08 00:45 UTC, TheRealKeto commented
@reneeotten This [build report](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/149873/steps/install-port/logs/stdio) showcases that the project can't be build on anything pre-10.10. I originally excluded OSX 10.10 support as I was advised by upstream to do; I can't test whether the project works on lower systems, however.

2023-10-08 02:44 UTC, reneeotten commented
> @reneeotten This [build report](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/149873/steps/install-port/logs/stdio) showcases that the project can't be build on anything pre-10.10. I originally excluded OSX 10.10 support as I was advised by upstream to do; I can't test whether the project works on lower systems, however.

from that build log it appears that this package requires a CXX11 compatible compiler (at least it is adding `-std=c++11` to the `clang++` command). However, you are not requesting a compiler that supports that; I didn't check but would not be surprised that the default `clang` for older macOS versions does not support that. 

So instead of restricting building on any systems, please first try adding the line: `compiler.cxx_standard       2011`. See [the wiki entry](https://trac.macports.org/wiki/CompilerSelection) for more information.

2023-10-08 02:53 UTC, TheRealKeto commented
@reneeotten The C11 and C++11 standards are only supported on pre-Xcode 5.0, which is why legacy systems are not capable of building this package. A few days ago, I managed to get a VM of OSX 10.7, but I didn't have any success getting it to build.

Should anyone you know be able to diagnose this problem further, I'm happy to comply with further changes, even if they're needed in upstream; given that other systems can build the project, is `compiler.cxx_standard` a required flag?

2023-10-08 11:23 UTC, reneeotten commented
I don't think it has anything to do with "legacysupport", it could just be a compiler issue. If you set "compilers.cxx_standard 2011" it will use Apple's system clang version it that supports the standard otherwise it will install a newer version first and use that to compile the package. That should be clear from the link I provided. 

Please try this first, I will not spend anymore time on this if you do not follow advice first...

2023-10-09 04:48 UTC, TheRealKeto commented
@reneeotten After adding `compiler.cxx_standard` and getting logs (I'd actually done this before, just didn't save any logs), [the build still fails](https://github.com/macports/macports-ports/files/12842731/main.log).

This was tested on macOS 10.7.5 11G63 x86_64 running Xcode 4.3.3 4E3002.

2023-12-23 20:24 UTC, reneeotten requested changes
If you want to restrict it to some versions then please use the correct syntax using the "platforms" field

2024-01-04 20:12 UTC, reneeotten requested changes
I am fine with this change, but as I said before the build is using CXX11 and thus you should request a compiler that supports it (that is unrelated to whether it does or doesn't build on earlier OSes for other reasons.

2024-01-04 20:12 UTC, reneeotten commented on devel/ldid-procursus/Portfile
> +revision            2
why are you increasing the `revision` here - there shouldn't be a need for that. I didn't build before on the earlier OSes and will not now either.

2024-01-05 12:35 UTC, merged

2024-01-05 18:44 UTC, barracuda156 commented
@TheRealKeto It literally builds fine with zero changes besides dropping the prohibition. If old clangs do not build it, blacklisting those should be sufficient.
[build_10.6.log](https://github.com/macports/macports-ports/files/13845471/build_10.6.log)

Earlier discussion: https://github.com/macports/macports-ports/commit/07ba8f0c118c8e2c3ecaf28fb56317171c1f3621

2024-01-05 19:08 UTC, TheRealKeto commented
> It literally builds fine with zero changes besides dropping the prohibition. [build_10.6.log](https://github.com/macports/macports-ports/files/13845471/build_10.6.log)
> 
> Earlier discussion: [07ba8f0](https://github.com/macports/macports-ports/commit/07ba8f0c118c8e2c3ecaf28fb56317171c1f3621)
> 
> UPD. I see from the log above it was clang-15 which failed, and I am not familiar with that to offer a fix, but gcc builds it with no issues, apparently. The problem is either with clang or with the setup used, not with the code being impossible to compile.

@barracuda156 Can ports specify a specific compiler for certain systems? I'm convinced this is an issue with the version of clang used. I'm always open to suggestions regardless, and thanks for debugging further :)

2024-01-05 19:16 UTC, barracuda156 commented
@TheRealKeto Yes, compiler choice can be controlled up to a specific compiler version conditional on whatever is relevant. However, AFAIK restricting anything to GCC on Intel will be a hard “sell” (sadly, but as a matter of fact). For clangs it should be rather flexible, at least for older systems.

I have nothing at hand to try on, but I got 10.6.8 and 10.8.5 in VM at home. I can see if some clang can build this.

2024-01-06 23:17 UTC, ryandesign commented
> Can ports specify a specific compiler for certain systems?

Since Portfiles are written in Tcl, which is a full programming language, yes, you can write anything you want.

> I'm convinced this is an issue with the version of clang used.

Then the solution would not be to write conditionals for specific systems but rather to use the compiler_blacklist_versions portgroup to blacklist those versions of clang with which this port is not compatible.

2024-01-07 12:04 UTC, barracuda156 commented
@TheRealKeto @ryandesign In fact it is trivially fixed for older Intel:

```
legacysupport.use_mp_libcxx yes
compiler.blacklist-append {clang < 1100}
```
And:
```
10:~ svacchanda$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.8.5
BuildVersion:	12F2560
10:~ svacchanda$ port -v installed ldid-procursus
The following ports are currently installed:
  ldid-procursus @2.1.5-procursus7_1 (active) requested_variants='' platform='darwin 12' archs='x86_64' date='2024-01-07T20:04:24+0800'
```