poppler: fix library paths in generated typelib file
macports/macports-ports pull request #21251
Opened 2023-11-06 18:24 UTC by FlyingSamson

#### Description
This PR adds a patch that explicitly specifies the paths to the dynamic libraries in the install prefix, as otherwise a path relative to the working directory during buildtime of the port is used.

Before the fix `strings /opt/local/lib/girepository-1.0/Poppler-0.18.typelib | grep lib` gives
```
/opt/local/var/macports/build/_Users_dominik_my-ports_graphics_poppler-dev/poppler-dev/work/build/libpoppler-glib.8.dylib,/opt/local/var/macports/build/_Users_dominik_my-ports_graphics_poppler-dev/poppler-dev/work/build/libpoppler.133.dylib
```

and with the patch we get the correct:
```
/opt/local/lib/libpoppler-glib.8,/opt/local/lib/libpoppler.133
```

Note that I excluded the `dylib` extension intentionally, following the documentation of the `--shared-library` which says
```
The name of the library should not contain the ending shared library suffix.
```

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 13.6.1 22G313 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?

2023-11-07 12:47 UTC, mascguy commented
Converting to draft, until I've had a chance to test locally.

2024-01-22 23:11 UTC, pmetzger commented
@mascguy This has been sitting dormant for months because you asserted a lock on it. It's a two line patch. Please finish this.

2024-01-30 15:01 UTC, pmetzger commented
@FlyingSamson Please update the patch so that we can commit it. We have a conflict because Poppler was updated in the meantime.

2024-01-31 19:06 UTC, FlyingSamson commented
I just saw while looking at the changes made in the meantime, that the ports `poppler` and `poppler-devel` are exactly equivalent. Should I therefore include this patch also in the `poppler-devel` port?

2024-01-31 19:48 UTC, pmetzger commented
@FlyingSamson Maybe, if the problem is there too? Regardless, please resolve the conflicts here.

2024-02-02 18:00 UTC, mascguy commented
> I just saw while looking at the changes made in the meantime, that the ports `poppler` and `poppler-devel` are exactly equivalent. Should I therefore include this patch also in the `poppler-devel` port?

Great point.

Actually we should update this PR to update `poppper-devel` only. Then I'll update `poppler` separately.

2024-02-02 18:02 UTC, mascguy requested changes
Switch to updating `poppler-devel`, and I'll go ahead and merge.

2024-02-03 11:02 UTC, FlyingSamson commented
I now rebased and reevaluated that the patch is still necessary, valid, and fixes the problem. 
I also moved the changes to `poppler-devel` now.

2024-02-03 14:02 UTC, mascguy approved these changes

2024-02-03 14:03 UTC, merged