gtk-internet-radio-locator: update to 128.0, replace gnome-radio
macports/macports-ports pull request #21484
Opened 2023-11-20 05:25 UTC by oleaamot

#### Description

Update gtk-internet-radio-locator-128.0 from http://www.gnomeradio.org/src/gtk-internet-radio-locator-128.0.tar.xz and
replace gnome-radio

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.1 23B74 arm64
Command Line Tools 15.0.0.0.1.1694021235

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-11-20 06:13 UTC, oleaamot commented
See https://trac.macports.org/ticket/68749

I observe that geocode-glib-2.0 dependent packages such as gtk-internet-radio-locator requires geocode-glib-2.0.pc and it is not currently installed on macports 2.8.1.

From [​https://github.com/macports/macports-ports/pull/21484/checks](https://github.com/macports/macports-ports/pull/21484/checks)

No package 'geocode-glib-2.0' found

2023-11-21 15:16 UTC, pmetzger requested changes

2023-11-21 15:16 UTC, pmetzger commented on gnome/gnome-radio/Portfile
> +replaced_by         gtk-internet-radio-locator
This is not sufficient for removing a port; you will want to follow the entire process listed in: https://guide.macports.org/#development.practices.rename-replace-port

2023-11-26 12:52 UTC, reneeotten commented
@oleaamot so then you could never have succeeded in installing this locally before submitting a PR - or?

If it needs a new dependency then you will have to add that together with the update of this port. 

Feel free to re-open this PR once you have done so.

2023-11-26 12:52 UTC, closed without merging