ffmpeg: fix build with texinfo >= 7
macports/macports-ports pull request #21526
Opened 2023-11-25 04:58 UTC by maxcrees

#### Description

Backport upstream ffmpeg commit to prevent a build failure in doc generation. The recent upgrade of texinfo to 7.1 in 3c51e9bb4c77fcbc2232330af3621c99194bee33 caused deprecated function name usage in the ffmpeg docs to turn into failures now that the old function names have been removed.

Fixes: https://trac.macports.org/ticket/68747
Upstream bug: http://trac.ffmpeg.org/ticket/1063
Upstream commit: https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/f01fdedb69e4accb1d1555106d8f682ff1f1ddc7

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.1.1
Xcode 15.0.1 / Command Line Tools 15.0.0.0.1.1694021235

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-11-25 05:21 UTC, maxcrees commented
V2: don't bump `revision`, but do fix `ffmpeg-devel` too.

2023-11-25 22:53 UTC, ryandesign requested changes

2023-11-25 22:53 UTC, ryandesign commented on multimedia/ffmpeg-devel/Portfile
> +# http://trac.ffmpeg.org/ticket/1063
```suggestion
# https://trac.ffmpeg.org/ticket/10636
```

2023-11-25 22:53 UTC, ryandesign commented on multimedia/ffmpeg/Portfile
> +# http://trac.ffmpeg.org/ticket/1063
```suggestion
# https://trac.ffmpeg.org/ticket/10636
```

2023-11-26 05:51 UTC, maxcrees commented
V3: fix upstream bug URL comments in the Portfiles as spotted by @ryandesign - sorry about that, not sure how those got corrupted.

2023-11-26 08:28 UTC, ryandesign approved these changes
Thanks!

2023-11-27 13:15 UTC, maxcrees commented
72 hour timeout will expire in a few hours. I'm requesting a trybuild on the CI and a merge if it is successful.

2023-11-27 18:34 UTC, mascguy approved these changes
LGTM. Thank you for your contribution!

2023-11-27 18:34 UTC, merged