Final PR at updating some python ports
macports/macports-ports pull request #21837
Opened 2023-12-18 22:54 UTC by catap

#### Description

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2023-12-18 23:48 UTC, pmetzger commented
CI failed.

2023-12-18 23:59 UTC, reneeotten requested changes

2023-12-18 23:59 UTC, reneeotten commented on python/py-certomancer-csc-dummy/Portfile
> +supported_archs     noarch
it this is "noarch" it should potentially also set: "platforms {darwin any}".

2023-12-18 23:59 UTC, reneeotten commented on python/py-certomancer-csc-dummy/Portfile
> +                    port:py${python.version}-setuptools
this is implied with the default "python.pep517 yes"

2023-12-18 23:59 UTC, reneeotten commented on python/py-certomancer/Portfile
> +supported_archs     noarch
same as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-certomancer/Portfile
> +python.pep517       yes
this is the default for Python 3.7+

2023-12-18 23:59 UTC, reneeotten commented on python/py-hanko-certvalidator/Portfile
> +supported_archs     noarch
same as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-hanko-certvalidator/Portfile
> +python.pep517       yes
As above, default for Python 3.7+

2023-12-18 23:59 UTC, reneeotten commented on python/py-hanko/Portfile
> +supported_archs     noarch
as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-hanko/Portfile
> +python.pep517       yes
as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-oscrypto/Portfile
> +supported_archs     noarch
as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-oscrypto/Portfile
> +                    port:py${python.version}-setuptools
as above, this is an dependency already added because of "python.pep517 yes"

2023-12-18 23:59 UTC, reneeotten commented on python/py-python-pae/Portfile
> +supported_archs         noarch
as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-uritools/Portfile
> +supported_archs     noarch
as above

2023-12-18 23:59 UTC, reneeotten commented on python/py-uritools/Portfile
> +                    port:py${python.version}-setuptools
dependency is implied as it is using "python.pep517 yes" with the default "setuptools"

2023-12-19 01:42 UTC, catap commented
@reneeotten thanks for review. @pmetzger I guess that CI had failed because of buildbots need some time to catch the lag. Now it should be better.

2023-12-19 02:03 UTC, reneeotten commented
the CI has nothing to do with the buildbots - let's see how it goes this time.

2023-12-19 02:19 UTC, catap commented
all good

2023-12-19 02:34 UTC, pmetzger commented
Is this ready to merge?

2023-12-19 02:37 UTC, reneeotten commented
> Is this ready to merge?

I'll take another look some time tonight or tomorrow and will merge when it is

2023-12-19 03:26 UTC, reneeotten approved these changes

2023-12-19 03:26 UTC, merged

2023-12-19 10:17 UTC, catap commented
Thanks, Renee!