gnucash: use_mp_libcxx on older macos
macports/macports-ports pull request #21948
Opened 2023-12-26 21:48 UTC by tenzap

This will fix build errors on El Capitan (and probably other macos versions)

See commit message for errors that are fixed.

~~Build still fails later on, but I don't know how to fix that one.~~

#### Description

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010 x86_64
Xcode 7.3.1 7D1014

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2023-12-30 02:44 UTC, reneeotten requested changes
see below. And please remove all the random code in the body of the commit message - there is really no point or use for that.

2023-12-30 02:44 UTC, reneeotten commented on gnome/gnucash/Portfile
> +revision          1
if you're fixing only build failures a "recision" increase is not needed.

2023-12-30 12:27 UTC, reneeotten commented
The question was whether this is only fixing a build issue. If so, no increase of the "revision"; if not, then an increase of the "revision" might be warranted. Please remove the text i. The body of the commit message; there is no need for it.

2024-01-02 19:29 UTC, pmetzger commented
@reneeotten Is it okay now?

2024-01-05 15:23 UTC, reneeotten commented
> @reneeotten Is it okay now?

I don't k ow whether this is the appropriate fix... I just pointed out a few general things that should be changed, I can't comment on the actual code changes. 

Perhaps @kencu would be willing to take a quick look at this?

2024-01-10 13:54 UTC, merged