rb-gettext: support ruby 3.3, fix installation, add missing deps
macports/macports-ports pull request #22294
Opened 2024-01-20 15:46 UTC by barracuda156

#### Description

Fixups and support for Ruby 3.3.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1
Xcode 15.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-01-20 15:56 UTC, reneeotten commented
If you're anyway plan to fix something yourself, just submit a PR and don't open a Trac ticket. There is no point to that...

2024-01-20 16:00 UTC, reneeotten requested changes

2024-01-20 16:01 UTC, barracuda156 commented
@reneeotten Fair enough, I just looked into it and decided it is easier to fix it straightaway.

2024-01-20 16:58 UTC, barracuda156 commented on ruby/rb-erubi/Portfile
> +ruby.branches       3.3 3.2 3.1 3.0 2.7 2.6 2.5
@reneeotten Awesome: looks like nothing depends on `rb2*-gettext`, so these can be dropped.

2024-01-21 12:47 UTC, kimuraw commented
NOTE: port:sup depends rb-gettext (ruby1.8).  
I will remove sup from macports-ports.

2024-01-21 13:27 UTC, kimuraw commented on ruby/rb-erubi/Portfile
> +ruby.branches       3.3 3.2 3.1 3.0 2.7 2.6 2.5
(scheduled) EOL date of ruby versions:

- 2.7: 2023-03-31
- 3.0: 2024-03-31
- 3.1: 2025-03-31
- 3.2: 2026-03-31

https://www.ruby-lang.org/en/downloads/branches/

2024-01-21 14:48 UTC, reneeotten commented on ruby/rb-erubi/Portfile
> +ruby.branches       3.3 3.2 3.1 3.0 2.7 2.6 2.5
thanks; so as I said everything below version 3 should be dropped.

2024-01-26 07:30 UTC, barracuda156 commented
@kimuraw Finally, CI pass.

2024-01-27 17:36 UTC, judaew approved these changes
LGTM

2024-01-27 21:30 UTC, merged