cryfs: update to 0.11.4
macports/macports-ports pull request #22436
Opened 2024-01-28 21:56 UTC by jolan78

#### Description

- update cryfs to latest version : 0.11.4
- fix libfmt10 dependency: fixes https://trac.macports.org/ticket/69167

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.7 21G816 arm64
Xcode 13.3 13E113

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2024-01-29 01:21 UTC, reneeotten requested changes
Please change to use Python 3.12 as that is now MacPorts' default Python version.

2024-01-29 05:37 UTC, ryandesign commented
> * [x]  referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

Please reference the ticket URL in the commit message in the standard way.

2024-01-29 05:41 UTC, ryandesign commented on net/cryfs/Portfile
> +cmake.module_path-append  ${prefix}/lib/libfmt10/cmake
```suggestion
# This has to match the version of libfmt used by spdlog.
# See https://trac.macports.org/ticket/68248
cmake.module_path-append  ${prefix}/lib/libfmt10/cmake
```

2024-01-30 00:10 UTC, pmetzger commented
Looks like the requested changes were made, so I'm going to commit. Thanks, @jolan78 and thanks to everyone who reviewed.

2024-01-30 00:10 UTC, merged