cryfs: set compiler.thread_local_storage
macports/macports-ports pull request #22480
Opened 2024-01-31 21:01 UTC by jolan78

set `compiler.thread_local_storage yes` as requested in https://trac.macports.org/ticket/69237.
unfortunately I have no way to test it builds on macOS 10.10

#### Description

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.7 21G816 arm64
Xcode 13.3 13E113

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2024-02-01 00:45 UTC, reneeotten requested changes
Please don't make unneeded whitespace changes together with a functional change in the same commit.

2024-02-01 20:48 UTC, jolan78 commented
> Please don't make unneeded whitespace changes together with a functional change in the same commit.

do you mean I shall not align values or that I'm expected to do that in a separate commit ? if the latter, wouldn't that break the "one commit per logical change" rule ?

2024-02-02 00:07 UTC, reneeotten commented
> > Please don't make unneeded whitespace changes together with a functional change in the same commit.
> 
> 
> 
> do you mean I shall not align values or that I'm expected to do that in a separate commit ? if the latter, wouldn't that break the "one commit per logical change" rule ?

there is no need to have everything aligned identically, as long as things are aligned with four spaces. 
If you decide to change the alignment of the whole Portfile (which I don't recommend doing) then it should be in a separate commit. The changes here are two-fold: a functional change fixing a build failure and a non-functional change of adjusting whitespace.

2024-02-02 00:24 UTC, pmetzger commented
Yes. It's easier to review if non-functional and functional changes are in distinct commits. Makes it much easier for those of us trying to read the changes.

2024-02-02 20:57 UTC, jolan78 commented
Thank you for the clarification. the alignment change is removed

2024-02-03 01:57 UTC, pmetzger commented
Short and sweet now. Thanks for the update!

2024-02-03 01:57 UTC, merged