Maintainer fixed https://trac.macports.org/ticket/67860
macports/macports-ports pull request #23301
Opened 2024-03-31 20:22 UTC by trodemaster

#### Description

Fixes https://trac.macports.org/ticket/67860 by adding missing port dependencies. This also stops the build from downloading and building additional libraries.
###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 14.4.1 23E224 arm64
Command Line Tools 15.3.0.0.1.1708646388
###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [X] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?
- [X] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-03-31 21:30 UTC, ryandesign requested changes
> * [x]  followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?

Thank you but you commit message does not follow the guidelines.

2024-03-31 21:30 UTC, ryandesign commented on audio/nrsc5/Portfile
>                      path:bin/cmake:cmake \
Remove `path:bin/cmake:cmake` here; the cmake portgroup has added this for you already.

2024-03-31 21:30 UTC, ryandesign commented on audio/nrsc5/Portfile
> +                    port:fftw-3-single \
These dependencies are confused. `depends_lib` means "needed at build time and at runtime" and so anything listed in `depends_lib` does not also need to be specified in `depends_build` and `depends_run`. Does nrsc5 link with libraries installed by fftw-3 and fftw-3-single? If so, they belong in `depends_lib`, not in the other two dependency types.

2024-04-01 05:42 UTC, trodemaster commented
Ok, thanks for the guidance on tightening this up.  The port file and commit message should be good now. Looking at how to squash the commits correctly.

2024-04-01 12:28 UTC, pmetzger commented
You just rebase your commits into a single commit with the right message and force push to your branch.

2024-04-03 15:20 UTC, pmetzger commented
@trodemaster Please squash your commits?

2024-04-07 11:49 UTC, merged