podman: workaround for macOS 11 and below
macports/macports-ports pull request #23463
Opened 2024-04-11 19:54 UTC by judaew

#### Description

See
- https://trac.macports.org/ticket/69683
- https://github.com/crc-org/vfkit/issues/125

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-04-11 23:11 UTC, reneeotten requested changes

2024-04-11 23:11 UTC, reneeotten commented on sysutils/podman/Portfile
> +epoch               0
don't add an "epoch" here

2024-04-11 23:11 UTC, reneeotten commented on sysutils/podman/Portfile
> +if {${os.major} <= 20} {
this should also check for os.platforms in the usual way

2024-04-12 10:57 UTC, judaew commented
@reneeotten IDK why this issue occurs (port trying to get 4.9.3 version from 5.0.1 tag)

```
podman-4.9.3.tar.gz does not exist in /opt/local/var/macports/distfiles/go
  --->  Attempting to fetch podman-4.9.3.tar.gz from https://github.com/containers/podman/archive/v5.0.1
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
```

In this case, MacPorts will take the archive from its mirror. But I don't know how maintaining of subport for devel versions with this issue in other ports. I know one way to overcome this issue: use the excellent `github.tarball_from` from the main port.

2024-04-12 18:05 UTC, merged