rb-net-ftp: remove rb33 subport, as it is now included in ruby33
macports/macports-ports pull request #23808
Opened 2024-05-03 20:19 UTC by barracuda156

#### Description

Ruby 3.3.1 has this gem included.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-05-03 20:23 UTC, barracuda156 commented
```
Error: Failed to activate ruby33: Image error: /opt/local/lib/ruby3.3/gems/3.3.0/cache/net-ftp-0.3.4.gem is being used by the active rb33-net-ftp port.  Please deactivate this port first, or use 'port -f activate ruby33' to force the activation.
    while executing
"throw registry::image-error $msg"
    ("foreach" body line 49)
    invoked from within
"foreach file $imagefiles {
                incr progress_step
                _progress update $progress_step $progress_total_steps
                se..."
    invoked from within
"registry::write {
            # extract phase complete, assume 1/3 is done
            set progress_step $num_imagefiles
            foreach file $ima..."
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_ruby33/ruby33/main.log for details.
Error: Couldn't activate ruby33 3.3.1_0: 1
```

2024-05-04 02:42 UTC, reneeotten requested changes

2024-05-04 02:42 UTC, reneeotten commented on ruby/rb-net-ftp/Portfile
> +revision            1
no need to increase the `revision`

2024-05-04 02:47 UTC, barracuda156 commented on ruby/rb-net-ftp/Portfile
> +revision            1
OK, will drop that now.

2024-05-04 03:25 UTC, merged