mingw-w64-wine-mono: New Port
macports/macports-ports pull request #23888
Opened 2024-05-10 15:08 UTC by Gcenx

Stub that contains multiple subports, will be used for the new `wine` portfiles.

#### Description

###### Type(s)

###### Tested on

macOS 14.5 23F5074a x86_64
Xcode 15.3 15E204a

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-05-11 10:45 UTC, reneeotten requested changes

2024-05-11 10:45 UTC, reneeotten commented on cross/mingw-w64-wine-mono/Portfile
> +license             GPL, LGPL2.1, MPL
this doesn't look correct or at least inconsistent with ysafe in other Portfiles. Please use just spaces if multiple licenses apply; if there is a choice add curly brackets. See the [guide](https://guide.macports.org/index.html#reference.keywords) for more details.

2024-05-11 21:01 UTC, reneeotten commented on cross/mingw-w64-wine-mono/Portfile
> +license             GPL, LGPL2.1, MPL
thanks!
In this port as well: please correct your GitHub handle to have it match with what you're actually using when submitting a PR.

2024-05-24 15:48 UTC, pmetzger commented on cross/mingw-w64-wine-mono/Portfile
> +maintainers         {@Gcenx gmail.com:gcenx83}
Is this intentionally not openmaintainer?

2024-05-24 15:48 UTC, merged