openssl3: update to 3.3.0
macports/macports-ports pull request #24106
Opened 2024-05-24 11:47 UTC by herbygillot

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-05-24 19:45 UTC, neverpanic requested changes

2024-05-25 00:15 UTC, herbygillot commented on devel/openssl3/Portfile
> -patchfiles          e9d7083e241670332e0443da0f0d4ffb52829f08.patch
Gotcha, I was careless here and had removed the patch initially, not realizing that older pinned versions were still using it. I've restored it and switched to `patchfiles-append` as directed.

2024-05-25 19:20 UTC, neverpanic requested changes

2024-05-25 19:20 UTC, neverpanic commented on devel/openssl3/Portfile
>                              7e4d731b1c07201ad9374c1cd9ac5263bdf35bce.patch
The `patchfiles-append` needs to only list the second patch `7e4d731b1c07201ad9374c1cd9ac5263bdf35bce.patch`. The `e9d7083e241670332e0443da0f0d4ffb52829f08.patch` was for 3.2.1, `7e4d731b1c07201ad9374c1cd9ac5263bdf35bce.patch` is for 3.1.5.

2024-05-26 18:57 UTC, neverpanic approved these changes
Thanks for taking care of this!

2024-05-26 18:57 UTC, merged