abella: update to 2.0.8.3
macports/macports-ports pull request #24836
Opened 2024-07-07 07:22 UTC by barracuda156

#### Description

Finally, update this one

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-07-07 16:14 UTC, reneeotten requested changes

2024-07-07 16:14 UTC, reneeotten commented on ocaml/ocaml-base64/Portfile
> +name                ocaml-base64
this is set by the PortGroup already

2024-07-07 16:14 UTC, reneeotten commented on ocaml/ocaml-crunch/Portfile
> +homepage            https://github.com/mirage/ocaml-crunch
this is set by the PH already

2024-07-08 05:05 UTC, barracuda156 commented on ocaml/ocaml-base64/Portfile
> +name                ocaml-base64
Ok, I will change these today.

2024-07-08 08:42 UTC, barracuda156 commented
@reneeotten Fixed both issues above now.

2024-07-08 15:25 UTC, pmetzger commented
You added three ports, but that's not mentioned in the commit message.

2024-07-08 15:36 UTC, barracuda156 commented
> You added three ports, but that's not mentioned in the commit message.

@pmetzger Those are required dependencies, not random stuff. But I will change commit message now.

2024-07-08 15:47 UTC, merged

2024-07-08 15:48 UTC, pmetzger commented
Not my fave commit message but whatever.

2024-07-08 16:03 UTC, barracuda156 commented
Thanks for merging!