Rework the guile ecosystem
macports/macports-ports pull request #25319
Opened 2024-08-12 23:08 UTC by graywolf

#### Description

Move guile18 to guile-1.8, guile to guile-2.2, create new port guile-3.0.  Update all ports accordingly and add guile_select port.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.6
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
I think there is a value in preserving individual commits.  But I can squash it if you insist.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-08-12 23:12 UTC, Schamschula commented
Why did you revision bump `gnutls`, but not `gnutls-devel`? Both need it. Please fix this.

2024-08-12 23:52 UTC, markemer commented
These are failing with:
```
Failed to parse file lang/guile-3.0/Portfile: invalid command name "configure.checks.implicit_int"
```

2024-08-13 03:39 UTC, reneeotten commented
thanks @graywolf for working on this. I suppose you looked at the relevant Trac tickets, for example https://trac.macports.org/ticket/60139 ?

There appear to be / have been issues in making sure that none of the "guile-x.y" ports install overlapping files and thus would conflict. Is all of this resolved?

I haven't looked in detail but it appears that much of the indentation in the Portfiles is messed up: indentations should be with spaces in multiples of four - that is something (admittedly cosmetic) that will need to be resolved. 

But maIn question is whether all these ports can be installed side-by-side and whether dependents are verified to find/link with the correct version.

2024-08-13 09:37 UTC, lemzwerg reviewed
Very nice, thanks!

2024-08-13 09:37 UTC, lemzwerg commented on lang/guile-1.8/Portfile
> +# Note: I removed the compatibility symlinks.  The dependant ports should just
`s/dependant/dependent/`

2024-08-13 11:31 UTC, barracuda156 commented
@graywolf I will test this in a day or two.

2024-08-13 13:26 UTC, barracuda156 requested changes
Some things to change in the portfile, mostly non-functional.

2024-08-13 13:26 UTC, barracuda156 commented on lang/guile-3.0/Portfile
> +maintainers         wolfsden.cz:~+macports
Please make it `openmaintainer` too.

2024-08-13 13:26 UTC, barracuda156 commented on lang/guile-3.0/Portfile
> +                    port:pkgconfig \
Perhaps, rather `path:bin/pkg-config:pkgconfig`, unless it is known not to work with `pkgconf`.

2024-08-13 13:26 UTC, barracuda156 commented on lang/guile-3.0/Portfile
> +                    port:gnutls \
This should be `path:lib/pkgconfig/gnutls.pc:gnutls` (we have `gnutls-devel` port).

2024-08-13 13:34 UTC, barracuda156 commented
> > These are failing with:
> > ```
> > Failed to parse file lang/guile-3.0/Portfile: invalid command name "configure.checks.implicit_int"
> > ```
> 
> Hm. Any idea why? I am sure I built the Portfile just fine locally. And `port lint' does not complain.

@graywolf I can confirm that it fails to parse for the said reason.

2024-08-13 13:47 UTC, barracuda156 commented
@graywolf `guile-1.8` fails at destroot on:
```
ts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/srfi'
Making install in doc
make[1]: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/doc'
Making install in ref
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/doc/ref'
restore=: && backupdir=".am$$" && \
	am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
	rm -rf $backupdir && mkdir $backupdir && \
	if (/bin/sh /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/build-aux/missing --run makeinfo --version) >/dev/null 2>&1; then \
	  for f in guile.info guile.info-[0-9] guile.info-[0-9][0-9] guile.i[0-9] guile.i[0-9][0-9]; do \
	    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
	  done; \
	else :; fi && \
	cd "$am__cwd"; \
	if /bin/sh /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/build-aux/missing --run makeinfo   -I . \
	 -o guile.info guile.texi; \
	then \
	  rc=0; \
	  CDPATH="${ZSH_VERSION+.}:" && cd .; \
	else \
	  rc=$?; \
	  CDPATH="${ZSH_VERSION+.}:" && cd . && \
	  $restore $backupdir/* `echo "./guile.info" | sed 's|[^/]*$||'`; \
	fi; \
	rm -rf $backupdir; exit $rc
api-compound.texi:908: encoding error at byte 0xa0
gh.texi:1000: must be after `@deftypefun' to use `@deftypefunx'
fdl.texi:411: raising the section level of @appendixsubsec which is too low
make[2]: *** [guile.info] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/doc/ref'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/doc'
make: *** [install-recursive] Error 1
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8'
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8" && /usr/bin/make -w install pkgconfigdir=/opt/local/lib/pkgconfig DESTDIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/destroot 
Exit code: 2
Error: Failed to destroot guile-1.8: command execution failed
```

2024-08-13 19:48 UTC, markemer commented
> > > > These are failing with:
> > > > ```
> > > > Failed to parse file lang/guile-3.0/Portfile: invalid command name "configure.checks.implicit_int"
> > > > ```
> > > 
> > > 
> > > Hm. Any idea why? I am sure I built the Portfile just fine locally. And `port lint' does not complain.
> > 
> > 
> > @graywolf I can confirm that it fails to parse for the said reason.
> > P. S. Or is it something added in 2.10.0? I have 2.9.99 on this machine. Let me update and try again.
> 
> I just installed 2.9.3 from source, and portindex processed the Portfile fine. So I have to admit I have no idea what is wrong. I can change it, is there any other recommended way to suppress
> 
> ```
> Warning: Configuration logfiles contain indications of -Wimplicit-int; check that features were not accidentally disabled:
>   found in guile-3.0.10/config.log
> ```
> 
> warnings from configure phase?

Yeah, 2.10.0 was my theory, and now it's shot. It seems like it should be valid.

2024-08-13 22:53 UTC, barracuda156 commented
> ~Yeah, 2.10.0 was my theory, and now it's shot. It seems like it should be valid.~
> 
> Edit: Yeah, it got added in 2.10: [macports/macports-base@cfacb20](https://github.com/macports/macports-base/commit/cfacb20bde7f9073e388f7368bdf77c65be5e2b2)

Parsing portfile worked after updating to 2.10.

2024-08-14 06:14 UTC, barracuda156 commented
@graywolf You have asked about `dprintf`, this:
```
:info:build posix.c: In function 'piped_process':
:info:build posix.c:1612:9: error: implicit declaration of function 'dprintf'; did you mean 'vprintf'? [-Wimplicit-function-declaration]
:info:build  1612 |         dprintf (err, "In execvp of %s: %s\n", exec_file,
:info:build       |         ^~~~~~~
:info:build       |         vprintf
:info:build make[3]: *** [libguile_3.0_la-posix.lo] Error 1
:info:build make[3]: *** Waiting for unfinished jobs....
```

2024-08-14 06:28 UTC, barracuda156 commented
More generally: https://www.gnu.org/software/gnulib/manual/html_node/dprintf.html
And AFAICT, it is missing in 10.6, at least it is not in `stdio.h`: https://github.com/alexey-lysiuk/macos-sdk/blob/main/MacOSX10.6.sdk/usr/include/stdio.h

I have this in `libSystem`, no idea where it is defined:
```
36-25% nm -arch ppc -g /usr/lib/libSystem.dylib | grep dprintf
0011a284 T __simple_dprintf
0011a1e8 T __simple_vdprintf
```

2024-08-14 07:02 UTC, barracuda156 commented
@graywolf And then this fails, since it requires a full bootstrap, like guile2:
```
Making all in stage0
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/stage0'
  BOOTSTRAP(stage0) GUILEC ice-9/eval.go
/bin/sh: line 1: 32915 Abort trap              GUILE_BOOTSTRAP_STAGE=stage0 ../meta/build-env guild compile --target="powerpc-apple-darwin10.0.0d2" -W0 -O1 -L "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/module" -o "ice-9/eval.go" "../module/ice-9/eval.scm"
make[2]: *** [ice-9/eval.go] Error 134
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/stage0'
make[1]: *** [all-recursive] Error 1
```

If you have a better solution for `dprintf`, we can adopt that instead of my patch. I am not sure it is an optimal solution.

As for the rest, I think we should start with using on `powerpc` what is known to work (and possibly enable threads etc later on). I can make a commit against your branch, so that you can just cherry-pick it. Is this convenient?

2024-08-14 08:22 UTC, barracuda156 commented
@graywolf I am grateful that you spend time on this.

Having CI would have made life easier, but there is no trivial way to set it up, AFAIK. Locally, in absence of native hardware, the easiest way to test for `ppc` is Rosetta, however I am not sure `guile` will build on it (Rosetta has problems with some languages which are built by themselves).

Logs:
[config.log.zip](https://github.com/user-attachments/files/16609826/config.log.zip)
[main.log.zip](https://github.com/user-attachments/files/16609832/main.log.zip)

2024-08-14 12:28 UTC, reneeotten commented
just as a reminder: a maintainer and/or PR submitter has no obligation to support old OSes and/or architectures. So if this works on the last three macOS releases (i.e., the CI passes, I've just started that) we're technically done.

2024-08-14 12:30 UTC, reneeotten commented
> > ~Yeah, 2.10.0 was my theory, and now it's shot. It seems like i 
> However, it is perhaps better to avoid it indeed, since some people will be on an earlier version of MacPorts, and then will face the same error.

Agreed, there is a grace period where we do not really yet on newly released features. I think that's typically two weeks but we should check; and at least the CI should be updated to the latest version before we can do so.

2024-08-14 14:29 UTC, markemer commented
> > just as a reminder: a maintainer and/or PR submitter has no obligation to support old OSes and/or architectures. So if this works on the last three macOS releases (i.e., the CI passes, I've just started that) we're technically done.
> 
> There are few failures in the CI, I will investigate in the evening. Some of them are expected (drgeo1 does not build even before my changes for example), some of them I need to check.
> 
> PS: The CI run takes over 3 hours, so the iteration cycle is bit slow :)

Yeah - I've done github action for work for a long time now, and I'm noodling on ways to parallelize PRs like this one, so while it will take a while to find runners probably, we could just rerun the fails as people fix them.

2024-08-14 16:12 UTC, markemer commented
Also, now that I mention it, can you add Fixes: for trac tickets in the description?

Take a look at https://trac.macports.org/wiki/CommitMessages

2024-08-15 09:29 UTC, barracuda156 commented
@graywolf BTW do we really need multiple guile ports for each minor version? Once 3.1 lands, guile-3.0 should either be renamed or a new port is needed.

Why not just use `guile2` and `guile3`?

2024-08-15 09:31 UTC, barracuda156 commented
> I went through the CI failures:
> 
> 
> 
> drgeo1 does not built even not master.  g-wrap, gnotime, swig-d, swig-gcj failed to install dependencies.  libfive, swig-chicken, swig-clisp fail to build even after simple revision bump (I tried in separate branches), so nothing I broke.
> 
> 
> 
> Only one I am unsure about yet is graphviz-gui-devel, I do not fully understand what is wrong there.  It seems to build on master, however I just do not understand how guile change could lead to
> 
> 
> 
> ```
> 
> 2024-08-14T19:47:53.9385980Z     Failure Reason: Operation not permitted
> 
> 2024-08-14T19:47:53.9388130Z /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_graphviz-devel/graphviz-gui-devel/work/graphviz-9.0.0/macosx/English.lproj/MainMenu.xib: error: Compilation failed. Unable to write to path: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_graphviz-devel/graphviz-gui-devel/work/graphviz-9.0.0/macosx/build/Release/Graphviz.app/Contents/Resources/English.lproj/MainMenu.nib
> 
> 2024-08-14T19:47:53.9390140Z     Underlying Errors:
> 
> 2024-08-14T19:47:53.9391320Z         Description: You don’t have permission to save the file “MainMenu.nib” in the folder “English.lproj”.
> 
> 2024-08-14T19:47:53.9392280Z         Failure Reason: You don’t have permission.
> 
> 2024-08-14T19:47:53.9392890Z         Recovery Suggestion: To view or change permissions, select the item in the Finder and choose File > Get Info.
> 
> 2024-08-14T19:47:53.9393460Z         Underlying Errors:
> 
> 2024-08-14T19:47:53.9394090Z             Description: The operation couldn’t be completed. Operation not permitted
> 
> 2024-08-14T19:47:53.9394700Z             Failure Reason: Operation not permitted
> 
> 2024-08-14T19:47:53.9395170Z         Description: “MainMenu.nib” couldn’t be removed.
> 
> 2024-08-14T19:47:53.9395570Z         Failure Reason: The file doesn’t exist.
> 
> 2024-08-14T19:47:53.9395900Z         Underlying Errors:
> 
> 2024-08-14T19:47:53.9396610Z             Description: The operation couldn’t be completed. No such file or directory
> 
> 2024-08-14T19:47:53.9397280Z             Failure Reason: No such file or directory
> 
> ```

I think I had `g-wrap` and `gnotime` building fine locally, but it was a time ago, I need to verify if it still works.

2024-08-15 10:45 UTC, barracuda156 commented
> > Why not just use `guile2` and `guile3`?
> 
> 
> 
> AFAIK there are fundamental incompatibilities between guile 1, 2, and 3.  It took some time to make LilyPond work with guile 2, and it took a really long time and a lot of effort to lift it to guile 3.  As long as there are programs that need a specific major version of guile I think it is prudent to provide a corresponding port.

There is no question about major versions. I doubt we need guile-3.0, then guile-3.1, then guile-3.3. It makes better sense to stick to major versions-based naming: guile18 (okay, for historical reasons), guile2, guile3.

2024-08-15 14:46 UTC, pmetzger commented
What do we have left to get this merged?

2024-08-15 15:22 UTC, Schamschula commented
In the meantime there have been several updates to `gnutls`/`gnutls-devel`

2024-08-15 16:35 UTC, barracuda156 commented
> I am not sure that is correct approach to take here. All the major distributions (as I wrote above) do have guile-2.2 and guile-3.0 (so the package name includes minor as well). And it seems to make sense, just look at the list of _incompatible_ changes in guile 2.2: https://lists.gnu.org/archive/html/guile-devel/2017-03/msg00095.html . With just guile-2 we would have to wait until _all_ software using the 2 version would be update to support it. That does not seem to be wise limitation to impose upon ourselves.
> 
> Heck, even the guile itself install its files into `/share/guile/3.0/` (and other versioned directories) acknowledging the need to have multiple stable series installed at one time.
> 
> Besides, guile is not exactly fast moving language, it took 6 years from 2.0 to 2.2. And 3 more years for guile 3.0.
> 
> There will be no further releases on 2.2 and 1.8 (afaik), and for 3 I signed up as a maintainer, so am willing to do the work with guile-3.1 and obsoleting guile-3.0 when (and if) the time comes.

Ok, so be it.

> There is some debate about PPC support, but based on https://github.com/macports/macports-ports/pull/25319#issuecomment-2288612212 I would suggest leaving that to separate PR after this is merged.

I do not think there is a debate, since consensus position is so far pretty clear and no one questions it: there is no obligation to support any older systems (including but not limited to ppc), but it is desirable to support those when possible (desirable for MacPorts, not necessarily for any specific person, who may not care about systems he is not using personally).

Technically it does not matter if ppc support is merged in a separate PR or at once in this one. The problem is that once this is merged, adding ppc fixes may take another year, just because someone with commit access who happens to bump in first to review the PR has a bad mood. That would be pretty upsetting, especially given how much time I spent to have this fixed.

Nobody bothered about updating Guile for 2 years. Nobody bothered to merge a previous PR which lacked a minor fix to one component and otherwise had everything working (I have used my guile3 to build several dependencies).
Unless all of a sudden getting Guile 3 is a matter of life and death, perhaps it is tolerable to give me 2–3 days to test this?

2024-08-15 20:15 UTC, Schamschula commented
One more update to `gnutls` https://github.com/macports/macports-ports/commit/95635b6063e42e4f8e6c8ca272560fd25ae5e15f

2024-08-16 17:10 UTC, markemer commented
@pmetzger I think we're at the point were all the CI fails are not caused by this PR but already broken ports, since they seem to be guile unrelated failures.

2024-08-16 18:09 UTC, barracuda156 commented
> @pmetzger I think we're at the point were all the CI fails are not caused by this PR but already broken ports, since they seem to be guile unrelated failures.

Some ports will not build, it was established earlier, so perhaps just drop broken ports from revbumps.

@graywolf I am done with JDK and can spend the rest of the weekend on Guile. If you allow me until Monday, I will sort the build of guile 3 and hopefully find a way to disable broken docs for guile 1.8 when building for ppc.
Guile 2.2 should be good, as long as setting match with what I had in the earlier PR (installation pattern may differ, that does not matter, I only mean build settings here).

2024-08-16 18:33 UTC, pmetzger commented
> Some ports will not build, it was established earlier, so perhaps just drop broken ports from revbumps.

I agree with that. Anything that won't build on its own should be taken out of the revbumps for now.

2024-08-16 20:01 UTC, markemer commented
> > Some ports will not build, it was established earlier, so perhaps just drop broken ports from revbumps.
> 
> I agree with that. Anything that won't build on its own should be taken out of the revbumps for now.

Yeah, the revbump removals makes sense, I also don't seem any harm in waiting until Monday.

2024-08-17 12:38 UTC, barracuda156 commented
> > > > Some ports will not build, it was established earlier, so perhaps just drop broken ports from revbumps.
> 
> > > 
> 
> > > 
> 
> > > I agree with that. Anything that won't build on its own should be taken out of the revbumps for now.
> 
> > 
> 
> > Yeah, the revbump removals makes sense, I also don't seem any harm in waiting until Monday.
> 
> 
> 
> Hm, I removed the revbumps but it still tries to built the ports in the CI.  Does it detect changed ports by Portfile changing, not the version?

That should not be the case. Unless something uses that port as a dependency.

2024-08-17 14:17 UTC, barracuda156 commented
@graywolf You can do needed changes to broken ports in a separate PR, adding `[skip ci]`. But I am not giving instructions here, I just suggest what I would have considered in this case myself.

2024-08-18 01:08 UTC, barracuda156 commented
@graywolf The error with `guile-1.8` has been reported long back by multiple people, see: https://trac.macports.org/ticket/48690
I still get the same error here:
```
api-compound.texi:908: encoding error at byte 0xa0
gh.texi:1000: must be after `@deftypefun' to use `@deftypefunx'
fdl.texi:411: raising the section level of @appendixsubsec which is too low
make[2]: *** [guile.info] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-1.8/guile-1.8/work/guile-1.8.8/doc/ref'
make[1]: *** [install-recursive] Error 1
```
This has certainly nothing to do with powerpc whatsoever.

2024-08-18 01:23 UTC, barracuda156 commented
(Let me try again from the latest version, maybe it was already fixed since the time I mentioned it here.)

2024-08-18 03:03 UTC, barracuda156 commented
@graywolf Do you know where `HAVE_DPRINTF=1` comes from? AFAICT, nothing checks for it. `configure.ac` has no mention of it. However, something writes this into configure, while instead it should write `REPLACE_DPRINTF=1`.

This looks like upstream bug.

2024-08-18 06:25 UTC, barracuda156 commented
@graywolf I tried to build without any flags or patches besides `dprintf` (full bootstrap, of course), it fails on this:
```
  GEN      guile-procedures.texi
make[3]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/libguile'
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/libguile'
Making all in module
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/module'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/module'
Making all in stage0
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/stage0'
  BOOTSTRAP(stage0) GUILEC ice-9/eval.go
wrote `ice-9/eval.go'
  BOOTSTRAP(stage0) GUILEC ice-9/psyntax-pp.go
wrote `ice-9/psyntax-pp.go'
  BOOTSTRAP(stage0) GUILEC language/tree-il.go
  BOOTSTRAP(stage0) GUILEC language/tree-il/compile-cps.go
  BOOTSTRAP(stage0) GUILEC language/tree-il/compile-bytecode.go
  BOOTSTRAP(stage0) GUILEC language/tree-il/analyze.go
  BOOTSTRAP(stage0) GUILEC language/tree-il/cps-primitives.go
  BOOTSTRAP(stage0) GUILEC ice-9/boot-9.go
wrote `language/tree-il/cps-primitives.go'
  BOOTSTRAP(stage0) GUILEC language/tree-il/debug.go
wrote `language/tree-il.go'
  BOOTSTRAP(stage0) GUILEC language/tree-il/demux-lambda.go
wrote `language/tree-il/analyze.go'
  BOOTSTRAP(stage0) GUILEC language/tree-il/effects.go
wrote `language/tree-il/compile-bytecode.go'
  BOOTSTRAP(stage0) GUILEC language/tree-il/eta-expand.go
wrote `language/tree-il/compile-cps.go'
  BOOTSTRAP(stage0) GUILEC language/tree-il/fix-letrec.go
Backtrace:
          19 (_ #<procedure 4d17630 at ice-9/eval.scm:383:13 rest>)
          18 (_ #<procedure 4d20180 at ice-9/eval.scm:383:13 rest>)
          17 (_ #<procedure 4d26cb0 at ice-9/eval.scm:383:13 rest>)
          16 (_ #<procedure 4d268e0 at ice-9/eval.scm:383:13 rest>)
          15 (_ #<procedure 4e778f0 at ice-9/eval.scm:383:13 rest>)
In ice-9/eval.scm:
    619:8 14 (_ #(#(#(#(#(#<directory (system base compile) 45c2500> "language/tree-il/debug.go" "../module/language/tree-il/debug.scm" #<module (#{ g4778}#) 3f6cc30> scheme bytecode 1 0 (#:warnings (unsupported-warning)))) "language/tree-il/debug.go") #<closed: file 3f669a0>) #f))
In unknown file:
          13 (_ #<procedure 4e90530 at ice-9/eval.scm:383:13 rest>)
          12 (_ #<procedure 4e93b80 at ice-9/eval.scm:383:13 rest>)
In ice-9/eval.scm:
    619:8 11 (_ #(#(#<directory (system base compile) 45c2500> #<closed: file 3f66968> #<procedure 4e8e4a0 at ice-9/eval.scm:333:13 (a)> "../module/language/tree-il/debug.scm" "language/tree-il/debug.go.mEK89l" "language/tree-il/debug.go")))
   196:35 10 (_ #(#(#<directory (system base compile) 45c2500> #<closed: file 3f669a0> #<module (#{ g4778}#) 3f6cc30> scheme bytecode 1 0 (#:warnings (unsupported-warning))) #<closed: file 3f66968>))
In unknown file:
           9 (_ #<procedure 4ea2190 at ice-9/eval.scm:383:13 rest>)
           8 (_ #<procedure 3f3e3f0 at ice-9/eval.scm:339:13 (a b c)>)
           7 (_ #<procedure 3f3e2c0 at ice-9/eval.scm:339:13 (a b c)>)
In language/tree-il/compile-bytecode.scm:
  1365:33  6 (compile-bytecode #<tree-il (seq (let (m) (#{m 4788}#) ((call (@@ (guile) define-module*) (const (language tree-il debug)) (const #:filename) (const "language/tree-il/debug.scm") (const #:imports) (const (((language tree-il)) ((ice-9 match)) ((srfi srfi-1)) ((srfi srfi-26)))) (const #:exports) (const (verify-tree-il)) (const #:declarative?) (const #t))) (seq (call (@@ (guile) set-current-module) (lexical m #{m 4788}#)) (void))) (define verify-tree-il (lambda ((name . verify-tre?> ?)
    603:2  5 (split-closures #<tree-il (seq (let (m) (#{m 4788}#) ((call (@@ (guile) define-module*) (const (language tree-il debug)) (const #:filename) (const "language/tree-il/debug.scm") (const #:imports) (const (((language tree-il)) ((ice-9 match)) ((srfi srfi-1)) ((srfi srfi-26)))) (const #:exports) (const (verify-tree-il)) (const #:declarative?) (const #t))) (seq (call (@@ (guile) set-current-module) (lexical m #{m 4788}#)) (const #<unspecified>))) (define verify-tree-il (lambda ((name?>)
   588:29  4 (failure)
   545:56  3 (visit #<tree-il (lambda ((name . verify-tree-il)) (lambda-case (((exp) #f #f #f () (#{exp 4789}#)) (let (seen-gensyms) (#{seen-gensyms 4790}#) ((call (toplevel make-hash-table))) (fix (add-env) (#{add-env 4792}#) ((lambda ((name . add-env)) (lambda-case (((new env) #f #f #f () (#{new 5359}# #{env 5360}#)) (if (primcall null? (lexical new #{new 5359}#)) (lexical env #{env 5360}#) (call (lexical add-env #{add-env 4792}#) (primcall cdr (lexical new #{new 5359}#)) (let (sym) (#{sym?>)
In unknown file:
           2 (_ #<procedure 5d7b7d0 at ice-9/eval.scm:383:13 rest>)
In ice-9/eval.scm:
    619:8  1 (_ #(#(#f #f #<&compound-exception components: (#<&assertion-failure> #<&origin origin: "+"> #<&message message: "Wrong type argument in position ~A: ~S"> #<&irritants irritants: (1 #<unknown-immediate (0x1 . 0x2c85) @ 0x1f55724>)> #<&exception-with-kind-and-args kind: wrong-type-arg args: ("+" "Wrong type argument in position ~A: ~S" (1 #<unknown-immediate (0x1 . 0x2c85) @ 0x1f55724>) (#<unknown-immediate (0x1 . 0x2c85) @ 0x1f55724>))>)> #<procedure 4e93c30 at ice-9/eval.sc?> ?)))
In unknown file:
           0 (_ #<procedure 5d7eb70 at ice-9/eval.scm:383:13 rest>)

ERROR: In procedure +: Wrong type argument in position 1: #<unknown-immediate (0x1 . 0x2c85) @ 0x1f55724>
make[2]: *** [language/tree-il/debug.go] Error 1
make[2]: *** Waiting for unfinished jobs....
wrote `ice-9/boot-9.go'
Backtrace:
          19 (_ #<procedure 45da840 at ice-9/eval.scm:383:13 rest>)
          18 (_ #<procedure 45da2b0 at ice-9/eval.scm:383:13 rest>)
          17 (_ #<procedure 45e2dc0 at ice-9/eval.scm:383:13 rest>)
          16 (_ #<procedure 46139b0 at ice-9/eval.scm:383:13 rest>)
In ice-9/eval.scm:
    619:8 15 (_ #(#(#(#(#(#<directory (system base compile) 2cf2190> "language/tree-il/demux-lambda.go" "../module/language/tree-il/demux-lambda.scm" #<module (#{ g4760}#) 4cc73c0> scheme bytecode 1 0 (#:warnings (unsupported-warning)))) "language/tree-il/demux-lambda.go") #<closed: file 3ee7f88>) #f))
In unknown file:
          14 (_ #<procedure 4644380 at ice-9/eval.scm:383:13 rest>)
          13 (_ #<procedure 4648b30 at ice-9/eval.scm:383:13 rest>)
In ice-9/eval.scm:
    619:8 12 (_ #(#(#<directory (system base compile) 2cf2190> #<closed: file 3ee7f50> #<procedure 463d1e0 at ice-9/eval.scm:333:13 (a)> "../module/language/tree-il/demux-lambda.scm" "language/tree-il/demux-lambda.go.6LQZVT" "language/tree-il/demux-lambda.go")))
   196:35 11 (_ #(#(#<directory (system base compile) 2cf2190> #<closed: file 3ee7f88> #<module (#{ g4760}#) 4cc73c0> scheme bytecode 1 0 (#:warnings (unsupported-warning))) #<closed: file 3ee7f50>))
In unknown file:
          10 (_ #<procedure 4689260 at ice-9/eval.scm:383:13 rest>)
           9 (_ #<procedure 4f7c950 at ice-9/eval.scm:339:13 (a b c)>)
           8 (_ #<procedure 4f7c880 at ice-9/eval.scm:339:13 (a b c)>)
In language/tree-il/compile-bytecode.scm:
  1365:33  7 (compile-bytecode #<tree-il (seq (let (m) (#{m 4761}#) ((call (@@ (guile) define-module*) (const (language tree-il demux-lambda)) (const #:filename) (const "language/tree-il/demux-lambda.scm") (const #:imports) (const (((srfi srfi-1)) ((ice-9 match)) ((language tree-il)))) (const #:exports) (const (demux-lambda)) (const #:declarative?) (const #t))) (seq (call (@@ (guile) set-current-module) (lexical m #{m 4761}#)) (void))) (seq (define make-binding (lambda ((name . make-binding?> ?)
    603:2  6 (split-closures #<tree-il (seq (let (m) (#{m 4761}#) ((call (@@ (guile) define-module*) (const (language tree-il demux-lambda)) (const #:filena [...]

2024-08-18 10:17 UTC, barracuda156 commented
@graywolf I am building now from your portfile with ppc-specific fixups, will leave it to run overnight, expect to confirm everything works for `guile-3.0` by tomorrow morning. (Or if something fails, will deal with that no later than tomorrow.)

2024-08-18 19:18 UTC, barracuda156 commented
> > @graywolf I tried to build without any flags or patches besides `dprintf` (full bootstrap, of course), it fails on this:
> 
> > 
> 
> > [..]
> 
> > 
> 
> > So probably extra setting which we had were justified. Trying to drop them breaks compilation here or there.
> 
> 
> 
> Thanks for checking that :)  I admit the error is way beyond my knowledge, would you know if this was reported to the upstream?

@graywolf 
Probably not, but this is a guess. However, given that since Guile 2.x through now they distribute broken ppc binaries (which is why we are forced to do multi-hour bootstrap), it seems that the thing bitrotten and never been tested for years.

If you could bring this to someone’s attention, it would be very helpful.

2024-08-18 19:22 UTC, barracuda156 commented
> > This looks like upstream bug.
> 
> I did look into it based on the config.log you posted before, and got baffled by it as well.  Turns out that it is just hardcoded in gl_STDIO_H_DEFAULTS macro (in m4/stdio_h.m4).  There is a comment above it:

Configure also sets HAVE_GETLINE=1, which is wrong, but apparently the code does not actually use it anywhere.

For this at least we have a fix: `legacysupport` library provides `getline`.

@macportsraf Do you happen to know if `drintf` can be supported?

2024-08-18 22:50 UTC, macportsraf commented
@barracuda156 Sure. What's the last version of macOS that doesn't have it?

2024-08-19 00:58 UTC, barracuda156 commented
@graywolf After 12 hours of building, it failed on Stage 1:
```
Backtrace:
In ice-9/boot-9.scm:
  1755:12 19 (with-exception-handler _ _ #:unwind? _ #:unwind-for-type _)
In system/base/compile.scm:
    69:11 18 (_)
   190:11 17 (_ #<closed: file 2841ea8>)
    309:6 16 (read-and-compile _ #:from _ #:to _ #:env _ #:optimization-level _ #:warning-level _ #:opts _)
   352:28 15 (compile _ #:from _ #:to _ #:env _ #:optimization-level _ #:warning-level _ #:opts _)
   265:44 14 (_ _ _)
   261:33 13 (_ _ #<directory (ice-9 common-list) 288c320>)
In language/cps/optimize.scm:
    136:2 12 (_ _ #<directory (ice-9 common-list) 288c320>)
    111:3 11 (optimize-first-order-cps _ _)
In language/cps/switch.scm:
    414:6 10 (optimize-branch-chains _)
In language/cps/intmap.scm:
    519:6  9 (visit-branch #(#(#(#<intset 0-155> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #f) (absent) (absent) (absent) #((absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) # ?) ?) ?) ?)
    519:6  8 (visit-branch #(#(#<intset 0-155> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #f) (absent) (absent) (absent) #((absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (#) # ?) ?) ?)
    519:6  7 (visit-branch #((absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #<intset 156-199> (absent) (absent) (absent) #f) _ 128 _)
In language/cps/switch.scm:
    99:36  6 (fold-branch-chains #<intmap 0-1831> _ _ #<procedure optimize-branch-chain (var exit tests cps)> _)
    343:8  5 (optimize-branch-chain 122 181 (158 159 160 161 162 163 164 165 167 169 171 173 175 177 179) _)
In ice-9/boot-9.scm:
   260:13  4 (for-each #<procedure 41c6570 at language/cps/switch.scm:343:18 (expr)> _)
In language/cps/switch.scm:
   340:32  3 (_ (count-if . 170))
In language/cps/guile-vm.scm:
    89:31  2 (target-symbol-hash _)
    41:18  1 (jenkins-lookup3-hashword2 "count-if")
In ice-9/boot-9.scm:
  1676:22  0 (raise-exception _ #:continuable? _)

ice-9/boot-9.scm:1676:22: In procedure raise-exception:
Value out of range 0 to< 18446744073709551615: -432225964
gmake[2]: *** [Makefile:2516: ice-9/common-list.go] Error 1
gmake[2]: *** Waiting for unfinished jobs....
Backtrace:
In ice-9/boot-9.scm:
  1755:12 19 (with-exception-handler _ _ #:unwind? _ #:unwind-for-type _)
In system/base/compile.scm:
    69:11 18 (_)
   190:11 17 (_ #<closed: file 2841ea8>)
    309:6 16 (read-and-compile _ #:from _ #:to _ #:env _ #:optimization-level _ #:warning-level _ #:opts _)
   352:28 15 (compile _ #:from _ #:to _ #:env _ #:optimization-level _ #:warning-level _ #:opts _)
   265:44 14 (_ _ _)
   261:33 13 (_ _ #<directory (ice-9 control) 288cf00>)
In language/cps/optimize.scm:
    136:2 12 (_ _ #<directory (ice-9 control) 288cf00>)
    111:3 11 (optimize-first-order-cps _ _)
In language/cps/switch.scm:
    414:6 10 (optimize-branch-chains _)
In language/cps/intmap.scm:
    519:6  9 (visit-branch #(#(#(#<intset 0-129> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #f) (absent) (absent) (absent) #((absent) (absent) #<intset 130-153> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) # ?) ?) ?) ?)
    519:6  8 (visit-branch #(#(#<intset 0-129> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #f) (absent) (absent) (absent) #((absent) (absent) #<intset 130-153> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (#) # ?) ?) ?)
    519:6  7 (visit-branch #((absent) (absent) #<intset 130-153> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #<intset 154-734,1124-1129> (absent) (absent) (absent) (absent) (absent) #f) _ 128 _)
In language/cps/switch.scm:
    99:36  6 (fold-branch-chains #<intmap 0-1129> _ _ #<procedure optimize-branch-chain (var exit tests cps)> _)
    343:8  5 (optimize-branch-chain 100 151 (132 134 136 138 140) _)
In ice-9/boot-9.scm:
   260:13  4 (for-each #<procedure 39b18b8 at language/cps/switch.scm:343:18 (expr)> _)
In language/cps/switch.scm:
   340:32  3 (_ (call-with-escape-continuation . 135))
In language/cps/guile-vm.scm:
    89:31  2 (target-symbol-hash _)
    41:18  1 (jenkins-lookup3-hashword2 "call-with-escape-continuation")
In ice-9/boot-9.scm:
  1676:22  0 (raise-exception _ #:continuable? _)

ice-9/boot-9.scm:1676:22: In procedure raise-exception:
Value out of range 0 to< 18446744073709551615: -512332661
gmake[2]: *** [Makefile:2516: ice-9/control.go] Error 1
```
This could be a regression from 3.0.9, but it also could be a result of some new flag, like `--enable-guile-debug` (I did not override new flags, I only added `--disable-jit --without-threads`). Probably that was a mistake: I need to use exact flags as before (for powerpc only, of course).

2024-08-19 02:48 UTC, barracuda156 commented
> @barracuda156 Sure. What's the last version of macOS that doesn't have it?

@macportsraf Looks like in 10.7: https://github.com/alexey-lysiuk/macos-sdk/blob/69ddec41e6224afebd5f19bb24764305ac3e828a/MacOSX10.7.sdk/usr/include/stdio.h#L446

10.6.8 SDK lacks `dprintf` in `stdio.h`.

2024-08-19 23:04 UTC, barracuda156 commented
@graywolf Unfortunately, looks like 3.0.10 is genuinely broken. I did not strictly copy my old (working correctly) settings, but AFAICT only difference now is `--disable-deprecated` (I left it as-is).

```
Making all in stage1
gmake[2]: Entering directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_guile-3.0/guile-3.0/work/guile-3.0.10/stage1'
  BOOTSTRAP(stage1) GUILEC ice-9/psyntax-pp.go
  BOOTSTRAP(stage1) GUILEC language/tree-il/analyze.go
  BOOTSTRAP(stage1) GUILEC ice-9/eval.go
  BOOTSTRAP(stage1) GUILEC language/tree-il.go
  BOOTSTRAP(stage1) GUILEC language/tree-il/compile-bytecode.go
  BOOTSTRAP(stage1) GUILEC ice-9/boot-9.go
wrote `ice-9/eval.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/compile-cps.go
wrote `language/tree-il/analyze.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/cps-primitives.go
wrote `language/tree-il/cps-primitives.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/debug.go
wrote `language/tree-il.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/demux-lambda.go
wrote `language/tree-il/demux-lambda.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/effects.go
wrote `language/tree-il/debug.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/eta-expand.go
wrote `ice-9/psyntax-pp.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/fix-letrec.go
wrote `language/tree-il/eta-expand.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/inlinable-exports.go
wrote `language/tree-il/compile-bytecode.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/letrectify.go
wrote `language/tree-il/fix-letrec.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/optimize.go
wrote `language/tree-il/optimize.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/peval.go
wrote `language/tree-il/letrectify.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/primitives.go
wrote `language/tree-il/effects.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/resolve-free-vars.go
wrote `language/tree-il/primitives.go'
  BOOTSTRAP(stage1) GUILEC language/tree-il/spec.go
wrote `language/tree-il/spec.go'
  BOOTSTRAP(stage1) GUILEC language/cps.go
wrote `language/tree-il/inlinable-exports.go'
  BOOTSTRAP(stage1) GUILEC language/cps/closure-conversion.go
wrote `ice-9/boot-9.go'
ice-9/boot-9.scm:853:27: warning: possibly unbound variable `symbol-pref'
ice-9/boot-9.scm:860:9: warning: possibly unbound variable `symbol-pset!'
ice-9/boot-9.scm:4690:35: warning: possibly unbound variable `syntax?'
  BOOTSTRAP(stage1) GUILEC language/cps/compile-bytecode.go
wrote `language/tree-il/resolve-free-vars.go'
  BOOTSTRAP(stage1) GUILEC language/cps/contification.go
wrote `language/tree-il/compile-cps.go'
  BOOTSTRAP(stage1) GUILEC language/cps/cse.go
wrote `language/cps/contification.go'
  BOOTSTRAP(stage1) GUILEC language/cps/dce.go
wrote `language/cps/closure-conversion.go'
  BOOTSTRAP(stage1) GUILEC language/cps/devirtualize-integers.go
wrote `language/cps/dce.go'
  BOOTSTRAP(stage1) GUILEC language/cps/dump.go
wrote `language/cps/devirtualize-integers.go'
  BOOTSTRAP(stage1) GUILEC language/cps/elide-arity-checks.go
wrote `language/cps/elide-arity-checks.go'
  BOOTSTRAP(stage1) GUILEC language/cps/effects-analysis.go
wrote `language/cps/dump.go'
  BOOTSTRAP(stage1) GUILEC language/cps/graphs.go
wrote `language/cps/graphs.go'
  BOOTSTRAP(stage1) GUILEC language/cps/intmap.go
wrote `language/tree-il/peval.go'
  BOOTSTRAP(stage1) GUILEC language/cps/intset.go
wrote `language/cps/effects-analysis.go'
  BOOTSTRAP(stage1) GUILEC language/cps/licm.go
wrote `language/cps/cse.go'
  BOOTSTRAP(stage1) GUILEC language/cps/optimize.go
wrote `language/cps.go'
  BOOTSTRAP(stage1) GUILEC language/cps/peel-loops.go
wrote `language/cps/optimize.go'
  BOOTSTRAP(stage1) GUILEC language/cps/prune-top-level-scopes.go
wrote `language/cps/prune-top-level-scopes.go'
  BOOTSTRAP(stage1) GUILEC language/cps/renumber.go
wrote `language/cps/licm.go'
  BOOTSTRAP(stage1) GUILEC language/cps/return-types.go
wrote `language/cps/intmap.go'
  BOOTSTRAP(stage1) GUILEC language/cps/rotate-loops.go
wrote `language/cps/peel-loops.go'
  BOOTSTRAP(stage1) GUILEC language/cps/self-references.go
wrote `language/cps/return-types.go'
  BOOTSTRAP(stage1) GUILEC language/cps/simplify.go
wrote `language/cps/self-references.go'
  BOOTSTRAP(stage1) GUILEC language/cps/slot-allocation.go
wrote `language/cps/renumber.go'
  BOOTSTRAP(stage1) GUILEC language/cps/spec.go
wrote `language/cps/spec.go'
  BOOTSTRAP(stage1) GUILEC language/cps/specialize-primcalls.go
wrote `language/cps/rotate-loops.go'
  BOOTSTRAP(stage1) GUILEC language/cps/specialize-numbers.go
wrote `language/cps/intset.go'
  BOOTSTRAP(stage1) GUILEC language/cps/split-rec.go
wrote `language/cps/specialize-primcalls.go'
  BOOTSTRAP(stage1) GUILEC language/cps/switch.go
wrote `language/cps/split-rec.go'
  BOOTSTRAP(stage1) GUILEC language/cps/type-checks.go
wrote `language/cps/type-checks.go'
  BOOTSTRAP(stage1) GUILEC language/cps/type-fold.go
wrote `language/cps/simplify.go'
  BOOTSTRAP(stage1) GUILEC language/cps/types.go
wrote `language/cps/switch.go'
  BOOTSTRAP(stage1) GUILEC language/cps/utils.go
wrote `language/cps/slot-allocation.go'
  BOOTSTRAP(stage1) GUILEC language/cps/verify.go
wrote `language/cps/verify.go'
  BOOTSTRAP(stage1) GUILEC language/cps/with-cps.go
wrote `language/cps/utils.go'
  BOOTSTRAP(stage1) GUILEC language/cps/guile-vm.go
wrote `language/cps/with-cps.go'
  BOOTSTRAP(stage1) GUILEC language/cps/guile-vm/loop-instrumentation.go
wrote `language/cps/type-fold.go'
  BOOTSTRAP(stage1) GUILEC language/cps/guile-vm/lower-primcalls.go
wrote `language/cps/guile-vm/loop-instrumentation.go'
  BOOTSTRAP(stage1) GUILEC language/cps/guile-vm/reify-primitives.go
wrote `language/cps/guile-vm.go'
  BOOTSTRAP(stage1) GUILEC ice-9/and-let-star.go
wrote `ice-9/and-let-star.go'
  BOOTSTRAP(stage1) GUILEC ice-9/arrays.go
wrote `language/cps/specialize-numbers.go'
  BOOTSTRAP(stage1) GUILEC ice-9/atomic.go
wrote `ice-9/atomic.go'
  BOOTSTRAP(stage1) GUILEC ice-9/binary-ports.go
wrote `ice-9/arrays.go'
  BOOTSTRAP(stage1) GUILEC ice-9/buffered-input.go
wrote `ice-9/buffered-input.go'
  BOOTSTRAP(stage1) GUILEC ice-9/calling.go
wrote `ice-9/binary-ports.go'
  BOOTSTRAP(stage1) GUILEC ice-9/command-line.go
wrote `ice-9/calling.go'
  BOOTSTRAP(stage1) GUILEC ice-9/common-list.go
wrote `ice-9/command-line.go'
  BOOTSTRAP(stage1) GUILEC ice-9/control.go
Backtrace:
In ice-9/boot-9.scm:
  1755:12 19 (with-exception-handler _ _ #:unwind? _ #:unwind-for-type _)
In system/base/compile.scm:
    69:11 18 (_)
   190:11 17 (_ #<closed: file 2841ea8>)
    309:6 16 (read-and-compile _ #:from _ #:to _ #:env _ #:optimization-level _ #:warning-level _ #:opts _)
   352:28 15 (compile _ #:from _ #:to _ #:env _ #:optimization-level _ #:warning-level _ #:opts _)
   265:44 14 (_ _ _)
   261:33 13 (_ _ #<directory (ice-9 common-list) 28a8320>)
In language/cps/optimize.scm:
    136:2 12 (_ _ #<directory (ice-9 common-list) 28a8320>)
    111:3 11 (optimize-first-order-cps _ _)
In language/cps/switch.scm:
    414:6 10 (optimize-branch-chains _)
In language/cps/intmap.scm:
    519:6  9 (visit-branch #(#(#(#<intset 0-155> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #f) (absent) (absent) (absent) #((absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) # ?) ?) ?) ?)
    519:6  8 (visit-branch #(#(#<intset 0-155> (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) #f) (absent) (absent) (absent) #((absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (absent) (a [...]

2024-08-20 04:17 UTC, macportsraf commented
@barracuda156 It turns out that *legacysupport* already has `dprintf()` but it has a big bug. It closes the file descriptor and so only works once. I've fixed it and added `vdprintf()`. I only discovered the bug by adding `vdprintf()` and a test for it which wasn't output. The fix is here: https://github.com/macports/macports-legacy-support/pull/95

2024-08-20 04:26 UTC, barracuda156 commented
@macportsbot Awesome, thank you!

@graywolf Is it okay to use `legacysupport` with `guile-3.0`? This is not ppc-specific and can be tested on x86_64.

2024-08-20 16:08 UTC, markemer commented
> > @macportsbot Awesome, thank you!
> > @graywolf Is it okay to use `legacysupport` with `guile-3.0`? This is not ppc-specific and can be tested on x86_64.
> 
> I have just vague idea what that means. If it just means adding `portgroup legacysupport 1.1` line to the Portfile, I can confirm that the test suite is still passing even with that line added. I am to new to macport to understand wider implications of that action though.
> 
> > not ppc-specific
> 
> So it is needed on non-ppc platforms as well I understand. Do people still use those older OSX versions outside of ppc (I though apple provides updates for both intel and arm based macs to newer OSX versions).
> 
> I am not too much against it, since I tested it and it seems to work, just would like to understand why it is needed on non-ppc as well.

Mostly for old unsupported x86_64 machines, if it doesn't break on normal machines, no harm in adding it.

2024-08-20 16:18 UTC, markemer commented
> @pmetzger @markemer Since it was agreed to do ppc support separately, I think this PR is pretty much done as much as possible. In absence of further specific review comments, I do not plan to do any further work (well, except rebasing when required :) ). So from my point of view it is ready to be merged.

Yeah, seems like it's ready. @pmetzger, you agree?

2024-08-20 19:58 UTC, pmetzger commented
Do we know why the CI is failing? Otherwise I have no objections.

2024-08-20 22:32 UTC, barracuda156 commented
> This is bit concerning, thanks for taking the time to report it upstream.  However be prepared for possibly slightly frustrating experience, the project is bit under-staffed.

@graywolf Do you have any guess what may be causing a failure? Could it potentially be related to any configure arguments that are passed?

For reporting, I get it correctly, that the only way is to subscribe to guile mailing list? No proper bugzilla and no GitHub issues which get responded to?
Mailing list is a bit of a pain, but if that is the only way, I will do it. PowerPC should be fixed eventually.

2024-08-20 22:37 UTC, barracuda156 commented
> Mostly for old unsupported x86_64 machines, if it doesn't break on normal machines, no harm in adding it.

Since we only need `legacysupport` for `dprintf` (and possibly `getline`), it can be restricted to 10.6 (since 10.7 has both natively).

```
PortGroup legacysupport 1.1

legacysupport.newest_darwin_requires_legacy 10
```
(This is not arch-specific.)

2024-08-21 01:37 UTC, reneeotten requested changes
@graywolf formatting issues in the `guile*` Portfiles has not been fixed yet. If you check the CI `port lint` (or run that locally as is part of the PR checklist), will warn about that (i.e., you're using tabs instead of spaces).

My other question still stands: if you have all three `guile` versions installed (which should be possible now), do all ports pick up the correct dependency/libraries to link to? In other words, is there nothing else you need to do to point to the correct place where the different versions are installed and just adding the dependency is sufficient? I find that a little hard to believe but admittedly haven't checked any of this myself... Just to be clear, you cannot rely on the `guile_select` setting to have ports behave correctly.

2024-08-21 18:25 UTC, pmetzger commented
Even if the others already had tabs instead of spaces, this would be a good opportunity to fix it. You can (and indeed should!) do it in a separate commit of course.

2024-08-21 21:15 UTC, barracuda156 commented
> I do not think you need to subscribe. While mailing list is used for bug reporting[0], any mail that is received on the mailing list is converted into a bug report in debbugs (for example like this[1]). You will get the bug number back by email response. People usually CC when reacting on the bug, so subscribing is not necessary (and not even common as far as I know).

Sounds good. I will do that once back to the PowerMac (so that I can attach the whole log), perhaps tomorrow.

2024-08-22 12:54 UTC, lemzwerg commented
Regarding the multi-hour bootstrapping process of Guile: Maybe the tiny patch in

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69314

helps (if it does please reply to this bug report so that there is more incentive to the Guile people to react).

2024-08-22 16:26 UTC, barracuda156 commented
> Regarding the multi-hour bootstrapping process of Guile: Maybe the tiny patch in
> 
> 
> 
> https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69314
> 
> 
> 
> helps (if it does please reply to this bug report so that there is more incentive to the Guile people to react).

@lemzwerg The problem is that their prebuilt binaries are broken and using them breaks the build (already at the onset of stage0). So we have to avoid using them. (Well, perhaps I might be able to use my earlier binaries, which worked correctly.)

2024-08-28 11:21 UTC, reneeotten commented
@graywolf where are we on this - the PR and comments have become a bit unwieldy and thus harder to keep up with. 

Warnings like:
```
port test libctl: Warning: libctl is configured to build for the architecture(s) 'x86_64', but did not install any Mach-O files.
```
could occur when ports don't compile stuff and/or not install architecture-dependent files; that doesn't seem to apply to `libtcl` so I am not sure. You can ignore these for the purpose of this PR.

2024-08-28 11:23 UTC, reneeotten commented
are there any other substantial concerns here? If not, let's try and get this merged.

2024-08-28 12:17 UTC, barracuda156 commented
> are there any other substantial concerns here? If not, let's try and get this merged.

Nothing from my side: powerpc is broken at the moment with 3.0.10 (3.0.9 worked fine), but no time right now to fix it (and no real urgency with guile). I will return to this in a while in a separate PR.

2024-08-29 01:44 UTC, reneeotten commented
@graywolf none of the commits to resolve the lint issues actually do so in the preferred way. The Portfile should be aligned the same throughout if possible (typically one would do so at 20 spaces, so starting at "21" "value" of the fields). Right now it's all over the place... the diff should be a small as possible just with removal of the tabs in favor of spaces.

2024-09-01 15:11 UTC, barracuda156 commented
@graywolf I got in touch with Guile devs. As of now, Guile 3.0.10 appears to be broken on 32-bit platforms, including x86.

See: https://issues.guix.gnu.org/72215
Also builds status on Debian: https://buildd.debian.org/guile-3.0

2024-09-02 18:51 UTC, reneeotten commented
thanks @graywolf I'll merge this now. We can keep an eye on the buildbots and if anything fails to build take a look at fixing that. Thank you for all the work!

2024-09-02 18:51 UTC, merged

2024-09-03 07:20 UTC, ryandesign commented on graphics/graphviz/Portfile
> +                                port:gsed
Why do graphviz & graphviz-devel now depend on gsed?

2024-09-22 05:26 UTC, barracuda156 commented
@graywolf Responding to your earlier question, a patch to optflags comes from Debian, see: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977223

2024-10-04 14:35 UTC, holymonson commented
@graywolf Would you please check https://trac.macports.org/ticket/71038 ?