clang-17: unbreak @available on MacOS 10.14
macports/macports-ports pull request #25514
Opened 2024-08-29 00:28 UTC by tuffnatty

#### Description

After the [recent switch](https://github.com/macports/macports-ports/commit/c8cceb0dec2dfb15e3a54e38260a676cb59fc9af) of older OS versions to allow mp-clang-17 as the fallback compiler, [qt64-qtbase has stopped building on 10.14](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/217224/steps/install-port/logs/stdio) with
```
Undefined symbols for architecture x86_64:
  "__availability_version_check", referenced from:
      ___isPlatformVersionAtLeast in libclang_rt.osx.a(os_version_check.c.o)
      __initializeAvailabilityCheck in libclang_rt.osx.a(os_version_check.c.o)
```
There is also https://trac.macports.org/ticket/68522 dealing with the same issue.
The reason is [this upstream clang change](https://reviews.llvm.org/D150397). It looks like a performance-only fix, and it does not prevent `ld` from reporting the undefined symbol on 10.14. It appears the `__attribute__(weak_import)` would work the way they wish only under very specific circumstances, e.g., linking with the flat namespace option.
The patch basically reverts that change for pre-10.15 MacOS versions. 

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C505

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-08-29 00:39 UTC, tuffnatty commented
Apparently, clang-18 requires this patch as well.

2024-08-29 00:44 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented
LGTM, however I am now wondering how @available is doing now.

2024-08-29 13:43 UTC, tuffnatty commented
I've added a clang-18 version of the patch and updated the commit message so that we won't bother that person any longer.

2024-09-02 19:30 UTC, kencu commented
This code should work as it is written -- the symbol is declared as a weak import, and it's only supposed to use the code that uses that symbol if the symbol is found...

I wonder why it's not working? The linker should not fail on the weak import not being found...

I think this has something to do with the default linker flags for undefined symbols being set to generate an error... there are a couple of other settings for what the linker is supposed to do with undefined symbols other than generate an error.

Perhaps upstream has already sorted out what the right linker flags are supposed to be and fixed this properly.

At any rate, blocking it out entirely on systems where the symbol can't exist seems OK to me ... same thing, in the end, as presumably the symbol will never be found on those systems anyway.

2024-09-02 20:19 UTC, tuffnatty commented
> I wonder why it's not working? The linker should not fail on the weak import not being found...
> 
> I think this has something to do with the default linker flags for undefined symbols being set to generate an error... there are a couple of other settings for what the linker is supposed to do with undefined symbols other than generate an error.

@kencu On MacOS, `__attribute__((weak_import))` [allows a symbol to be missing at run time, but requires it to be present at build time](https://glandium.org/blog/?p=2764).
 
> Perhaps upstream has already sorted out what the right linker flags are supposed to be and fixed this properly.

Upstream does not support MacOS 10.14 SDK, and that's where the symbol is undefined at build time.

> At any rate, blocking it out entirely on systems where the symbol can't exist seems OK to me ... same thing, in the end, as presumably the symbol will never be found on those systems anyway.

Right. Another way to deal with this is to use `-Wl,-U,__availability_version_check` while linking - but the code in question is a part of a static library, so this would need to be done in each project having this problem, although in fact it's a Clang's implementation detail.

2024-09-03 06:46 UTC, kencu commented
> > I wonder why it's not working? The linker should not fail on the weak import not being found...
> > I think this has something to do with the default linker flags for undefined symbols being set to generate an error... there are a couple of other settings for what the linker is supposed to do with undefined symbols other than generate an error.
> 
> @kencu On MacOS, `__attribute__((weak_import))` [allows a symbol to be missing at run time, but requires it to be present at build time](https://glandium.org/blog/?p=2764).


Yes, as I alluded to, by default it generates an error, but you pass this linker flag to override the default error:

-undefined dynamic_lookup

and you’re OK.  Or the one for the specific symbol. 

But you are likely right… this linker flag would have to be added to the routine link flags clang uses, and that’s getting a bit messy. It’s do-able, but adds a degree of fragility.

In fact, what upstream did here, switching to “weak_import”, will pretty much require software to be built on only newer systems that have the symbol.. Which probably is just fine with the llvm folks upstream, as that is how they roll.

2024-09-03 09:33 UTC, cjones051073 approved these changes

2024-09-05 12:02 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented
@kencu can it be merged now? Rebuilding Clang takes a lot of time, but this PR can also fix a [linking issue](https://github.com/macports/macports-ports/pull/25050#issuecomment-2254552667) of love-11 portfile.

2024-09-22 23:12 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented
[Clang 19 has been released](https://ports.macports.org/port/clang-19/details/), should these patches be applied to this portfile as well?

2024-12-20 16:39 UTC, mohd-akram commented
This is approved but there are conflicts. Can you rebase?

> [Clang 19 has been released](https://ports.macports.org/port/clang-19/details/), should these patches be applied to this portfile as well?

@cjones051073 Any idea?

2024-12-23 11:30 UTC, tuffnatty commented
@mohd-akram Rebased to master and added a clang-19 patch (identical to clang-18 one).

2024-12-23 14:31 UTC, mohd-akram requested changes

2024-12-23 14:31 UTC, mohd-akram commented on lang/llvm-17/Portfile
> +subport                 flang-${llvm_version} { revision [ expr ${revision} + 0 ] }
I think the revisions got changed in the rebase. Only Clang needs a bump, right?

2024-12-23 14:31 UTC, mohd-akram commented on lang/llvm-18/Portfile
> +subport                 flang-${llvm_version} { revision [ expr ${revision} + 0 ] }
Same here.

2024-12-23 14:31 UTC, mohd-akram commented on lang/llvm-17/Portfile
> +if {${os.platform} eq "darwin" && ${os.major} <= 18} {
```suggestion
if {${os.platform} eq "darwin" && ${os.major} < 19} {
```

2024-12-23 14:31 UTC, mohd-akram commented on lang/llvm-18/Portfile
> +if {${os.platform} eq "darwin" && ${os.major} <= 18} {
```suggestion
if {${os.platform} eq "darwin" && ${os.major} < 19} {
```

2024-12-23 14:31 UTC, mohd-akram commented on lang/llvm-19/Portfile
> +if {${os.platform} eq "darwin" && ${os.major} <= 18} {
```suggestion
if {${os.platform} eq "darwin" && ${os.major} < 19} {
```

2024-12-23 14:43 UTC, tuffnatty commented
@mohd-akram Thanks for the review! Pushed the forgotten revision number fixes and changed `<=` to `<`, although I consider it a very insignificant issue, and other conditions around that place still use `<=`.

2024-12-24 15:32 UTC, mohd-akram approved these changes

2024-12-24 15:32 UTC, merged

2024-12-24 15:35 UTC, mohd-akram commented
Thanks!

> changed <= to <, although I consider it a very insignificant issue

IMO it's a good habit to always use `<` because that would work regardless if the version is an integer or something else.