swiftlint: update to 0.56.2
macports/macports-ports pull request #25522
Opened 2024-08-30 02:30 UTC by herbygillot

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-10-02 08:01 UTC, reneeotten requested changes

2024-10-02 08:01 UTC, reneeotten commented on devel/swiftlint/Portfile
> +github.setup        realm swiftlint 0.56.2
latest upstream version is `0.57.0` - has that resolved some of the build issues?

2024-10-26 02:22 UTC, markemer commented
`error: 'swiftlint-0.57.0': package 'swiftlint-0.57.0' is using Swift tools version 5.9.0 but the installed version is 5.7.1`

So this is just always gonna fail if Xcode < 15, so we need to add that to the Portfile. If you're using Swiftlint but don't have swift n or n-1, I'm not sure what exactly you're doing.

2024-11-03 04:18 UTC, reneeotten commented
@markemer I don't need to review this PR anyore; @herbygillot can merge/commit this himself whenever he feels it's ready.

2024-11-21 16:26 UTC, merged