Fixes broken g-ir-scanner after updated py-setuptools
macports/macports-ports pull request #25564
Opened 2024-09-01 19:21 UTC by christophecvr

#### Description

closes [70667#](https://trac.macports.org/ticket/70667) 

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15
Xcode 12.4 / Command Line Tools 12.4.0.0.1.1610135815

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-09-01 19:39 UTC, mascguy commented
A few thoughts:
* You don't need to increase the epoch, that only necessary when downgrading a port's version.
* Can you also patch the Devel port (`gobject-introspection-devel`)?
* The associated ticket will automatically be closed, if you include a line like `Fixes: <ticket-utl>`.

2024-09-01 19:41 UTC, reneeotten requested changes

2024-09-01 19:41 UTC, reneeotten commented on gnome/gobject-introspection/Portfile
> +epoch               2
do not increase 'epoch`, just the `revision` is needed

2024-09-01 19:41 UTC, reneeotten commented on gnome/gobject-introspection/Portfile
> +# To runtime_path_envvar = ['DYLD_LIBRARY_PATH'] if not lib_dirs_envvar else [lib_dirs_envvar]
please add these comments in the patchfile if needed at all. Also, since the patch is an upstream fix - add the upstream URL in the patchfile

2024-09-01 19:42 UTC, reneeotten commented
while making these changes, also follow the commit message guidelines, as in: `<portname>: short description` the body of the commit message should include: 
```Closes: https://trac.macports.org/ticket/70667```

2024-09-01 20:38 UTC, christophecvr reviewed
epoch reset to 1

2024-09-01 20:44 UTC, reneeotten commented
> epoch reset to 1

thank you - once you add the upstream URL to the patch and move the comments, we'll merge this

2024-09-01 20:47 UTC, christophecvr commented
> > epoch reset to 1
> 
> thank you - once you add the upstream URL to the patch and move the comments, we'll merge this

the comment is already updated with Closes: https://trac.macports.org/ticket/70667

and the title also it now have the port in I really don't see what to do more

2024-09-01 21:07 UTC, reneeotten commented
> > > epoch reset to 1
> > 
> > 
> > thank you - once you add the upstream URL to the patch and move the comments, we'll merge this
> 
> the comment is already updated with Closes: https://trac.macports.org/ticket/70667
> 
> and the title also it now have the port in I really don't see what to do more

the comments you've added in the Portfile where you added the `patchfiles-append` should go in the actual patchfiles, together with a link to the upstream issue/PR.

2024-09-02 01:36 UTC, barracuda156 commented
@christophecvr How to make it work? I have upgrade `gobject-introspection-devel` to the one from your branch, but GIR still broken:
```
[40/41] /opt/local/bin/gi-docgen generate --quiet --no-namespace-dir --config=doc/Gom.toml --output-dir=doc/gom-1.0 --content-dir=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_gnome_gom/gom/work/gom-0.5.3/doc gom/Gom-1.0.gir
FAILED: doc/gom-1.0 
/opt/local/bin/gi-docgen generate --quiet --no-namespace-dir --config=doc/Gom.toml --output-dir=doc/gom-1.0 --content-dir=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_gnome_gom/gom/work/gom-0.5.3/doc gom/Gom-1.0.gir
ERROR: Could not find GIR dependency in the search paths: GObject-2.0
[41/41] /opt/local/bin/g-ir-compiler gom/Gom-1.0.gir --output gom/Gom-1.0.typelib --includedir=/opt/local/share/gir-1.0 --shared-library=/opt/local/lib/libgom-1.0.0.dylib
ninja: build stopped: subcommand failed.
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_gnome_gom/gom/work/build" && /opt/local/bin/ninja -j6 -v 
Exit code: 1
```

2024-09-02 02:01 UTC, barracuda156 commented
Or maybe this is a co-incidential, unrelated error.

2024-09-02 02:42 UTC, reneeotten commented
you can change the PR to do the same thing to the `-devel` port as was done in bd6d608c8525b6f2ac49818eff47da98454e8fe1

2024-09-02 06:54 UTC, christophecvr commented
> Or maybe this is a co-incidential, unrelated error.
No the error still there gobject-introspection-devel port is not adapted in master : 

Sorry just checked but I added the change also to this push request for gobject-introspection-devel , but the gobject-introspection-devel is not changed into the master. The changes I was forced to do by @reneeotten did finally broke the whole commit. Someone solved it for gobject-introspection by renaming the patch and change the portfile but forgot to do the same for gobject-introspection-devel . What you can do is apply same patch (renamed) which is finally added to gobject-introspection port to gobject-introspection-devel port.

2024-09-02 07:35 UTC, christophecvr reviewed
gobject-introspection-devel: Fix giscanner with setuptools 74

2024-09-02 07:56 UTC, barracuda156 commented on gnome/gobject-introspection-devel/Portfile
> +revision            1
Revision should not go down. This is perhaps a typo.

2024-09-02 08:11 UTC, closed without merging

2024-09-02 08:13 UTC, christophecvr commented
closed this pull request do it from scratch but only for gobject-introspection-devel as is done by @ryandesign by gobject-introspection

2024-09-02 10:58 UTC, reneeotten commented
Really... none of the review requests I made broke anything in this PR. In fact, they would have transformed your initial changes to the same thing as Ryan committed directly. 

You are very welcome to contribute but when doing so you will have to follow the projects guidelines and best-practices. I didn't "force" you to make changes, I was trying to have your PR conform to our standards so that it could get merged. 
I guess I'll spend my time elsewhere and ignore your contributions in the future.