dbeaver-community: Update to 2024.2.3 and add `all_arches` variant.
macports/macports-ports pull request #26314
Opened 2024-10-26 14:51 UTC by JLindop

#### Description

The all_arches variant requests distfiles for both aarch64 and x86_64, regardless of the actual build arch. This allows commands like `port bump` to function correctly.
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 15.0.1 24A348 arm64
Xcode 16.0 16A242d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2024-10-26 15:44 UTC, reneeotten requested changes
@JLindop there is no need for that variant - please remove. You can update the checksums yourself without the convenience of "port bump".

2024-10-27 02:53 UTC, reneeotten commented
@JLindop the only purpose of this PR appears to have `port bump` update the checksums; I don't see why mirroring would not work as intended in this case. I am not sure what the exact context of your conversation with @jmroot was but I am not convinced this change benefits MacPorts but of course it's possible that I am missing something here.

2024-10-27 11:00 UTC, jmroot commented
See for yourself: https://distfiles.macports.org/dbeaver-community/

2024-10-27 12:08 UTC, reneeotten commented
> See for yourself: https://distfiles.macports.org/dbeaver-community/

I see - there is only a distfile for `x86_64`. Another reason not to just download pre-compiled binaries, but I don't understand how adding a (non-default) variant would resolve the mirroring issue..

2024-10-27 12:38 UTC, jmroot commented
It's normal for variants to add or remove distfiles, so the mirror job mirrors each port with each of its variants selected.

2025-05-16 17:19 UTC, reneeotten commented
well, I am not really convinced about (or understand) the need for this but then again the PR queue isn't here for parking stuff indefinitely. It seems @jmroot is fine with it, so I'll just merge it.

2025-05-16 17:19 UTC, merged