LyX: remove Qt variants and fix Qt4
macports/macports-ports pull request #26462
Opened 2024-11-06 23:53 UTC by kurthindenburg

Per ML, variants can't handle different versions.  So remove variants and just use os version to pick Qt version.

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-11-07 01:42 UTC, reneeotten requested changes
Besides the inline comments two other ones:
- remove the "python38" variant as that is an EOL Python version; and "boost" doesn't have these variants anymore. 
- whitespace is very inconsistent and does not always appear to follow the modeline

2024-11-07 01:42 UTC, reneeotten commented on aqua/LyX/Portfile
> +    configure.cxxflags-append -std=c++11
this implies you need a compiler that supports the C++11 standard, but further down you request C++14 compatible compiler; that is inconsistent.

2024-11-07 01:42 UTC, reneeotten commented on aqua/LyX/Portfile
> +    qt5.depends_component       qtbase \
qtbase is implied and should not be listed

2024-11-07 14:40 UTC, barracuda156 requested changes

2024-11-07 14:40 UTC, barracuda156 commented on aqua/LyX/Portfile
> -        configure.objcflags-append \
This should not be removed.

2024-11-16 02:02 UTC, ryandesign reviewed
The build fails in CI on macOS 13 and 14:

```
  insets/ExternalTransforms.cpp:334:20: error: 'any_cast<std::function<std::unique_ptr<const lyx::external::TransformOption> (std::string)>>' is unavailable: introduced in macOS 10.13
    334 |         Factory factory = any_cast<Factory>(any_factory);
        |                           ^
```

I think that's because it is using `-mmacosx-version-min=10.10`; we don't want to request such an old deployment target. Oddly, the macOS 15 build succeeds despite this setting.

2024-11-16 02:02 UTC, ryandesign commented on aqua/LyX/Portfile
> +                    --with-version-suffix=-${branch} \
There's some code duplication. These lines seem to be the same regardless of version. Can this common code be pulled out of the conditional?

An additional question is why `-Os` is being hardcoded. Why not use `${configure.optflags}`?

2024-11-16 02:03 UTC, ryandesign commented on aqua/LyX/Portfile
> -}
If adding a python313 variant is possible, that would be a good idea.

2024-11-26 17:50 UTC, kurthindenburg commented
Thanks for the comments - I'll fix those once I get it to build correctly

2024-11-28 17:41 UTC, kurthindenburg commented
The 15 CI is struggling to build this huge port.  Unless someone objects, I'm going to commit it.  I'll squash the commit message.

2024-11-29 16:33 UTC, merged