libressl: re-fix build on macOS < 10.14
macports/macports-ports pull request #26827
Opened 2024-11-29 22:43 UTC by aeiouaeiouaeiouaeiouaeiouaeiou

Marking as draft, as my environment forces to use OpenSSL use.
Any help would be appreciated.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 4.2 4C199

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-02 04:23 UTC, artkiver commented
Cool! At the moment I don't have an easy way to test this. Unfortunately, my car was broken into in August and two laptops were stolen, including a 2012 MacBook Pro which I used for testing on older OS X versions.

I did test the newer Portfile on macOS 15.1.1 without issues.

I noticed port lint --nitpick is producing a warning:

> Warning: Unnecessary platforms line as darwin is the default

But it's been my experience sometimes that warning is spurious and removing the related line can cause more issues than leaving it.

2024-12-02 09:50 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented
>Unfortunately, my car was broken into in August and two laptops were stolen, including a 2012 MacBook Pro which I used for testing on older OS X versions.

It's sad to read that.

I definitely think this PR will solve the issue, however almost **every** portfile depends on OpenSSL and I have no clue how to test this even on a virtual machine.

2024-12-03 14:55 UTC, neverpanic requested changes

2024-12-06 20:52 UTC, neverpanic approved these changes

2024-12-06 20:53 UTC, merged