mosquitto: update to 2.0.20
macports/macports-ports pull request #26992
Opened 2024-12-09 00:03 UTC by danh1979

Also remove/disable broken approach to test for now

Closes https://trac.macports.org/ticket/67874

#### Description

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 14.7.1 23H222 arm64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-13 22:47 UTC, ryandesign commented on net/mosquitto/Portfile
> +                    port:python312
I don't see anywhere in the Portfile that causes the build system to use *this* version of python specifically; that would need to be added.

2024-12-28 15:33 UTC, reneeotten commented
@danh1979 please take care of @ryandesign his comment so we can merge this PR.

2025-01-09 19:31 UTC, reneeotten requested changes

2025-01-09 19:31 UTC, reneeotten commented on net/mosquitto/Portfile
> +test.run            no
```suggestion
```

2025-01-09 19:31 UTC, reneeotten commented on net/mosquitto/Portfile
> +test.run            no
no test-phase is the default; also if you don't run the tests please just remove the test dependencies

2025-01-23 06:01 UTC, reneeotten commented
@danh1979 last ping or I'll close the PR due to inactivity.

2025-01-23 14:01 UTC, closed without merging

2025-01-23 14:06 UTC, danh1979 commented
Ack! I, a noob, did not mean to close this.

2025-01-23 14:27 UTC, danh1979 commented
Since I broke this one, it appears I will have to create a new pull request. When I can do that, it will address the above comments.