scamper: Hotfix to fix building on < 10.7
macports/macports-ports pull request #27057
Opened 2024-12-13 05:31 UTC by TheRealKeto

#### Description

Apply hotfix to fix building `scamper` on < OSX 10.7, per [this Trac ticket](https://trac.macports.org/ticket/71519
)

###### Tested on

macOS 13.6 22G120 arm64
Command Line Tools 14.3.1.0.1.1683849156

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-13 06:54 UTC, barracuda156 commented
It also needs a fix for `AI_NUMERICSERV` like in: https://github.com/macports/macports-ports/commit/976522a861eb4541f8c9735f8467c3197ef16e87

Otherwise:
```
scamper_control.c: In function ‘remote_connect’:
scamper_control.c:3801: error: ‘AI_NUMERICSERV’ undeclared (first use in this function)
scamper_control.c:3801: error: (Each undeclared identifier is reported only once
scamper_control.c:3801: error: for each function it appears in.)
make[2]: *** [scamper-scamper_control.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

2024-12-13 06:57 UTC, barracuda156 requested changes
If you could add a patch here, it would be great (as it also relates to < 10.7).

2024-12-13 14:21 UTC, matthewluckie commented
Thanks, I can do.  Is there a howto on testing ports on older OSes?

2024-12-13 17:42 UTC, barracuda156 commented
@matthewluckie Not really, I guess. It is fairly easy to install pretty much any macOS version in a VM though on an x86_86 hardware. (Building for PowerPC would require everything from scratch, but otherwise pre-built ports are there.) Also port status will show failures on buildbots (if any), so that can be used to see if builds work (since no buildbots for < 10.6 or any PowerPC, those can’t be checked this way).

2024-12-13 21:20 UTC, TheRealKeto commented
@barracuda156 [This is provided by `legacy-support`](https://github.com/macports/macports-legacy-support/blob/master/include/netdb.h), so shouldn't this port just use the `legacysupport` PG?

2024-12-14 04:48 UTC, barracuda156 commented
@TheRealKeto When it is a three line fix in the source, why add an extra dependency?

2024-12-14 04:52 UTC, TheRealKeto commented
> When it is a three line fix in the source, why add an extra dependency?

@barracuda156 I was simply suggesting using an existing solution, and (from what I see) this is only trivial to < 10.7. It builds everywhere else, even on 10.7.

2024-12-14 05:54 UTC, barracuda156 commented
@TheRealKeto What I thought of is that it can be just fixed in upstream code, and then the patch dropped here. Since it is a trivial define with no maintenance burden, that seems to be the right thing to do.

2024-12-14 06:01 UTC, TheRealKeto commented
> What I thought of is that it can be just fixed in upstream code, and then the patch dropped here. Since it is a trivial define with no maintenance burden, that seems to be the right thing to do.

@barracuda156 The patch can stand just as much as the one rudely pushed by Ryan to cleanup the code (which AFAIK has already been implemented upstream). Both patches can be removed in the next update.

2024-12-14 06:05 UTC, matthewluckie commented
The numerichost patch should probably go in internal.h because I suspect compilation will fail elsewhere with the same issue. There's also a numericport constant that probably needs my attention.

2024-12-14 06:41 UTC, TheRealKeto commented
> The numericserv patch should probably go in internal.h because I suspect compilation will fail elsewhere with the same issue. There's also a numericport constant that probably needs my attention.

If that's the case, then I'll just close and wait for the next update, this since it was rudely superseeded by [bdbe1d5](https://github.com/macports/macports-ports/commit/bdbe1d53fa961f081a9f458900113570d4ee22ec) being pushed by Ryan.

2024-12-14 06:41 UTC, closed without merging