yelp-tools: fix broken installation, revbump
macports/macports-ports pull request #27122
Opened 2024-12-18 12:35 UTC by barracuda156

#### Description

Revbump, because it was not a build error.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-18 13:36 UTC, mohd-akram commented on gnome/yelp-tools/Portfile
>                      port:py${py_ver_nodot}-lxml
A bit weird to have this as a build dependency but not python itself.

2024-12-18 13:51 UTC, barracuda156 commented
@mohd-akram I actually agree with you here, but I have been earlier asked in an identical case to use `depends_lib` by @reneeotten. Outcome-wise these are probably identical; `depends_lib` avoid an extra line of code, while `depends_build` + `depends_run` is formally correct.

2024-12-18 15:36 UTC, barracuda156 commented
@mohd-akram Perhaps it needs `py312-lxml` as well by the way.
```
  cd /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_net_parabolic/parabolic/work/build/org.nickvision.tubeconverter.gnome && /opt/local/bin/cmake -E make_directory /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_net_parabolic/parabolic/work/build/org.nickvision.tubeconverter.gnome/el/LC_MESSAGES
  Traceback (most recent call last):
    File "/opt/local/bin/yelp-build", line 29, in <module>
      import lxml.etree
  ModuleNotFoundError: No module named 'lxml'
  make[2]: *** [shared_commands] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_net_parabolic/parabolic/work/build'
  make[1]: *** [libparabolic/CMakeFiles/shared_commands.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
```
https://github.com/barracuda156/powerpc-ports/actions/runs/12393802814/job/34595826923

2024-12-19 14:14 UTC, mohd-akram commented
> @mohd-akram Perhaps it needs `py312-lxml` as well by the way.

In this case I think put both python and lxml in depends_lib and nowhere else.

2024-12-19 14:23 UTC, mohd-akram requested changes

2024-12-19 14:23 UTC, mohd-akram commented on gnome/yelp-tools/Portfile
> +                    port:py${py_ver_nodot}-lxml
Move these to depends_lib.

2024-12-19 14:23 UTC, mohd-akram commented on gnome/yelp-tools/Portfile
>                      port:libxml2 \
Move libxslt and libxml to depends_run.

2024-12-20 04:08 UTC, mohd-akram approved these changes

2024-12-20 04:08 UTC, merged

2024-12-20 04:08 UTC, mohd-akram commented
Thanks!