Update ansible, ansible-core and ansible-compat to latest versions
macports/macports-ports pull request #27148
Opened 2024-12-20 18:14 UTC by jhoyt4

#### Description

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 15.1.1 24B91 arm64
Xcode 16.2 16C5032a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-20 21:47 UTC, jhoyt4 commented
@mascguy - any reason you killed the macOS 15 CI?

2024-12-20 21:49 UTC, jhoyt4 commented
port lint is failing for py-bcrypt.  This issue is unrelated to the update and was there before.

2024-12-20 21:55 UTC, mascguy commented
> @mascguy - any reason you killed the macOS 15 CI?

Yes, because the macOS 15 builder often runs for 6 hours, at which point it's killed by GitHub. Though I'm happy to rerun that, if you think there's a chance it might succeed?

2024-12-20 21:57 UTC, mascguy commented
Restarted the macOS 15 build, let's see how it goes...

2024-12-20 22:05 UTC, jhoyt4 commented
@mascguy - Thanks for restarting it

 I'm not sure if it will succeed, but would like to see if any errors pop out before the timeout.  Everything built in < an hour on my local machine running Sequoia, so I'm crossing my fingers.

2024-12-21 01:05 UTC, jhoyt4 commented
@mascguy - success!  Thanks again for entertaining me.

2024-12-21 01:32 UTC, mascguy commented
> @mascguy - success!  Thanks again for entertaining me.

Great, glad we reran it!

2024-12-21 02:53 UTC, ryandesign commented
> the macOS 15 builder often runs for 6 hours

because it needs to build all dependencies because we don't have a macOS 15 arm64 buildbot worker yet. We should not have added macOS 15 to GitHub Actions CI without that in place.

2025-01-11 20:46 UTC, jhoyt4 commented
@jmroot - The latest CI failure on this PR is due to py-setuptools being upgraded to 75.8.0. 

The latest ansible-core wants setuptools<=75.6.0.  That update might also break older ansible installs.

2025-01-12 16:08 UTC, jhoyt4 commented
making a draft until the upstream ansible team updates to allow use of setuptools 75.8.0

2025-01-13 01:30 UTC, jmroot commented
I doubt there's any actual incompatibility between these setuptools versions. Ansible is just setting an upper bound (in pyproject.toml) of the latest version they tested with.

2025-01-14 10:59 UTC, jhoyt4 commented
patch generated and tested locally

2025-01-14 11:15 UTC, jhoyt4 commented
@jmroot - do you know of a simple way to detect py-setuptools version?  I hacked in a patch, but would prefer it to be less hard coded.

2025-01-15 01:20 UTC, jmroot commented
> @jmroot - do you know of a simple way to detect py-setuptools version? I hacked in a patch, but would prefer it to be less hard coded.

To remove the upper bound you can just remove the <= version entirely, e.g. change `"setuptools >= 66.1.0, <= 75.6.0"` to `"setuptools >= 66.1.0"`. Then it will at least only break when there is an actual incompatibility, and not just when the version number exceeds an arbitrary limit…

2025-01-16 01:48 UTC, jhoyt4 commented
That last force push should implement the suggested setuptools version edit and add a few lines to remove any sylink to ansible-connect-3XX now that it's been removed from ansible.

2025-01-27 15:03 UTC, reneeotten requested changes
a few comments for specific Portfiles are inline. Once you make the changes, please separate the commits so that each commit only touches one Portfile.

2025-01-27 15:03 UTC, reneeotten commented on python/py-ansible-compat/Portfile
> +dist_subdir         ansible_compat-${version}
of the four lines above only `distname` is needed; the rest is the default from the `python` PortGroup so please remove those

2025-01-27 15:03 UTC, reneeotten commented on python/py-ansible-compat/Portfile
>  python.pep517       yes
this is the default for subports for Python 3.7+ so please remove

2025-01-27 15:03 UTC, reneeotten commented on python/py-ansible-core/Portfile
>  python.pep517       yes
as above this is set to the default values for `python.pep517`, please remove

2025-01-27 15:03 UTC, reneeotten commented on python/py-ansible/Portfile
>  python.pep517       yes
please remove

2025-01-27 15:03 UTC, reneeotten commented on python/py-subprocess-tee/Portfile
> +dist_subdir         subprocess_tee-${version}
of the four lines above only `distname` should be needed; please remove the others

2025-01-27 15:03 UTC, reneeotten commented on python/py-subprocess-tee/Portfile
>  python.pep517       yes
please remove

2025-01-28 00:26 UTC, jhoyt4 commented on python/py-ansible-compat/Portfile
>  python.pep517       yes
@reneeotten - to be clear, you're just asking for the removal of the "python.pep517       yes"?

2025-01-28 00:30 UTC, jhoyt4 commented on python/py-ansible-compat/Portfile
> +dist_subdir         ansible_compat-${version}
Strange, when I tested originally, I was getting errors with the download due to pypi needing ansible**_**compat vs. ansible**-**compat so I set the master_sites variable.  I'm no longer getting the download error...

2025-01-28 01:02 UTC, jhoyt4 commented
> Once you make the changes, please separate the commits so that each commit only touches one Portfile.

Done.  I also believe I made all of your requested corrections.

Thank you for taking a look and providing feedback!

2025-01-29 20:58 UTC, reneeotten commented
I've corrected the commit messages (there is no python3.13 variant; these are subports). Other than that looks good to me, so I'll merge - thanks again for working on this and your patience!

2025-01-29 20:58 UTC, merged

2025-01-30 00:23 UTC, jhoyt4 commented
> I've corrected the commit messages (there is no python3.13 variant; these are subports). Other than that looks good to me, so I'll merge - thanks again for working on this and your patience!

Thank you - my apologies for the commit message issue.