ansible-lint, yamllint: Update revision and interpreter to python3.13
macports/macports-ports pull request #27172
Opened 2024-12-21 13:51 UTC by jhoyt4

Update ansible-lint and yamlint to use python 3.13

  Additionally:
    ansible-lint: update to 24.12.2 use python 3.13
    yamlint: update to 1.35.1 and use python 3.13
    py-black: update to 24.10.0 and add python 3.13
    py-bracecx: update to 2.5 and add python 3.13
    py-enrich: add python 3.13
    py-wcmatch: update to 10.0 and add python 3.13

#### Description

Update yamlint and ansible-lint to the latest python (3.13)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 15.1.1 24B91 arm64
Xcode 16.2 16C5032a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
[x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-21 14:44 UTC, jhoyt4 commented
setting as draft as yamllint keeps wanting to install in python3.11...

2024-12-21 18:09 UTC, jhoyt4 commented
This PR required [PR27172](https://github.com/macports/macports-ports/pull/27172) or similar to be accepted before it can go any further

2024-12-21 18:10 UTC, jhoyt4 commented
That last force push created a varian

2024-12-23 09:04 UTC, reneeotten commented
the change to Python 3.13 should happen only after MacPorts has changed its default Python version. That happens on January 1st each year.

2024-12-23 10:42 UTC, jhoyt4 commented
@reneeotten - thanks for the heads up.  I can keep this here for another week.  It's also still blocked by [PR27171](https://github.com/macports/macports-ports/pull/27172) which gets a version of ansible that works with python313

2025-02-02 20:04 UTC, reneeotten requested changes

2025-02-02 20:04 UTC, reneeotten commented on devel/yamllint/Portfile
> +default_variants +python${python.default_version}
there is no need/point of doing this; please remove these lines.

2025-02-02 20:04 UTC, reneeotten commented on sysutils/ansible-lint/Portfile
> +                    port:py${python.version}-importlib-metadata\
are you sure this is needed; typically it is only needed for older Python versions. Please recheck upstream's dependencies.

2025-02-02 20:04 UTC, reneeotten commented on sysutils/ansible-lint/Portfile
>  python.pep517       yes
this is the default, please remove.

2025-02-02 20:43 UTC, jhoyt4 commented on devel/yamllint/Portfile
> +default_variants +python${python.default_version}
strange, I had to add these to keep it from trying to use python311.  That no longer is occuring in my testing.

2025-02-02 20:50 UTC, jhoyt4 commented on sysutils/ansible-lint/Portfile
> +                    port:py${python.version}-importlib-metadata\
It will install without the package, but the throws this error when running without importlib-metadata installed:
`Traceback (most recent call last):
  File "/opt/local/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import _run_cli_entrypoint
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ansiblelint/__main__.py", line 49, in <module>
    from ansiblelint import cli
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ansiblelint/cli.py", line 21, in <module>
    from ansiblelint.file_utils import (
    ...<5 lines>...
    )
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ansiblelint/file_utils.py", line 20, in <module>
    from ansiblelint.app import get_app
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ansiblelint/app.py", line 23, in <module>
    from ansiblelint.requirements import Reqs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ansiblelint/requirements.py", line 3, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'`

2025-02-02 20:51 UTC, jhoyt4 commented on sysutils/ansible-lint/Portfile
> +                    port:py${python.version}-importlib-metadata\
per pip 3:

pip-3.13 show ansible-lint
Name: ansible-lint
Version: 24
Summary: Checks playbooks for practices and behavior that could potentially be improved
Home-page: https://github.com/ansible/ansible-lint
Author: 
Author-email: Will Thames <will@thames.id.au>
License: GPLv3+
Location: /opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages
Requires: ansible-compat, ansible-core, black, filelock, **importlib-metadata**, jsonschema, packaging, pathspec, pyyaml, ruamel.yaml, subprocess-tee, wcmatch, yamllint

2025-02-02 20:54 UTC, jhoyt4 commented
@reneeotten - that last force push should clean up 2 of your three requested changes.  

It appears ansible-lint does in fact require importlib-metadata

2025-02-02 22:01 UTC, reneeotten commented
> @reneeotten - that last force push should clean up 2 of your three requested changes.
> 
> It appears ansible-lint does in fact require importlib-metadata

looks, good. However by now these do not appear to be the latest versions anymore (at least not for `ansible-lint`), so please update to the latest upstream versions where applicable and we'll merge the PR.

2025-02-02 22:16 UTC, jhoyt4 commented
updated.  ansible-lint and bracex now at the latest versions.

2025-02-03 01:52 UTC, merged