add macports libcxx dependency on older macs for gdb
macports/macports-ports pull request #27203
Opened 2024-12-25 17:56 UTC by i3roly

this will ensure older systems are able to build and use the latest gdb with minimal effort

hopefully other members on the macports squad will look into the macro nusiance that otherwise impedes a clean compilation

#### Description

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.7.5 11G63 x86_64
Xcode 4.2.1 4D502

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-26 08:02 UTC, barracuda156 requested changes
This should be fixed.

2024-12-26 08:02 UTC, barracuda156 commented on devel/gdb/Portfile
> +    configure.depends_lib-append port:macports-libcxx
This is wrong and gonna break builds on older OS. If you need this for `libc++`-consuming versions, please make it conditional accordingly.

2024-12-26 14:13 UTC, i3roly commented
Can you please make the recommended changes?As far as I can tell, gdb requires a libc++ newer than the ones in lion and mountain lion. All that we need to do is ensure that older macs use macports-libcxx so gdb is happy                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Sergey FedorovSent: Thursday, 26 December 2024 1:03 AMTo: macports/macports-portsReply To: macports/macports-portsCc: gagan sidhu; AuthorSubject: Re: [macports/macports-ports] add macports libcxx dependency on older macs for gdb (PR #27203)
@barracuda156 requested changes on this pull request.

This should be fixed.

In devel/gdb/Portfile:
> @@ -86,6 +86,13 @@ pre-configure {
 
 build.dir ${configure.dir}
 
+#older macs require a new libcxx
+if {${os.platform} eq "darwin" && ${os.major} < 15} {
+    configure.depends_lib-append port:macports-libcxx

This is wrong and gonna break builds on older OS. If you need this for libc++-consuming versions, please make it conditional accordingly.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/macports/macports-ports/pull/27203#pullrequestreview-2522927573",
"url": "https://github.com/macports/macports-ports/pull/27203#pullrequestreview-2522927573",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

2024-12-26 14:46 UTC, barracuda156 commented
@i3roly What you seem to want is to switch `libc++`-using systems to `legacy-support`-supplied `libc++` (which is somewhat newer than archaic system one). However, this is not just unneeded but also breaking for systems which do not use `libc++` to begin with. So the correct condition must include not only macOS version (whichever appropriate), but also C++ runtime, so that `macports-libcxx` is used only when C++ runtime is `libc++`.

2024-12-26 15:14 UTC, i3roly commented
i see what you’re saying.

could you please provide the runtime check? lol

Thanks,
Gagan

> On Dec 26, 2024, at 7:46 AM, Sergey Fedorov ***@***.***> wrote:
> 
> 
> @i3roly What you seem to want is to switch libc++-using systems to legacy-support-supplied libc++ (which is somewhat newer than archaic system one). However, this is not just unneeded but also breaking for systems which do not use libc++ to begin with. So the correct condition must include not only macOS version (whichever appropriate), but also C++ runtime, so that macports-libcxx is used only when C++ runtime is libc++.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
>

2024-12-26 17:09 UTC, barracuda156 commented
> i see what you’re saying. could you please provide the runtime check?

```
if {${os.platform} eq "darwin" && ${configure.cxx_stdlib} eq "libc++"} {

}
```

2024-12-27 04:43 UTC, aeiouaeiouaeiouaeiouaeiouaeiou requested changes

2024-12-27 04:43 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented on devel/gdb/Portfile
> +    configure.cxxflags-append    -L/opt/local/lib/libcxx
I don't get it why is hardcoded to `/opt/local` instead of `${prefix}`.

2024-12-27 04:44 UTC, i3roly commented
it shouldn’t be. i’ll fix that. thanks
Thanks,
Gagan

> On Dec 26, 2024, at 9:43 PM, aeiouaeiouaeiouaeiouaeiouaeiou ***@***.***> wrote:
> 
> 
> @aeiouaeiouaeiouaeiouaeiouaeiou requested changes on this pull request.
> 
> In devel/gdb/Portfile:
> 
> > @@ -86,6 +86,13 @@ pre-configure {
>  
>  build.dir ${configure.dir}
>  
> +#older macs require a new libcxx
> +if {${os.platform} eq "darwin" && ${os.major} < 15 && ${configure.cxx_stdlib} eq "libc++"} {
> +    configure.depends_lib-append port:macports-libcxx
> +    configure.cxxflags-append    -L/opt/local/lib/libcxx
> 
> I don't get it why is hardcoded to /opt/local instead of ${prefix}.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
>

2024-12-28 14:46 UTC, kencu commented
1. I have never seen this construct used:

configure.depends_lib-append

does it do anything? 


2. you are using:

configure.cxxflags-append    -L${prefix}/lib/libcxx

appending linker flags to the cxxflags. They should be appended to the ldflags.

3. you are not setting any cxx include flags so the headers from the new libcxx are not being used.

4. the legacysupport PG has a mechanism to do all this correctly.  Although the code in the PG does have an error in it nobody has fixed yet, it works anyway in almost all cases and does all this correctly. Have you tried that?

https://github.com/macports/macports-ports/blob/d94ce21c28dc781c81ba103c68eb8abf27100383/_resources/port1.0/group/legacysupport-1.1.tcl#L18

2024-12-28 15:22 UTC, i3roly commented
> 1. I have never seen this construct used:
> 
> 
> configure.depends_lib-append
> 
> does it do anything?

i didn't either, but apparently it's used a lot. it's supposed to ensure that macports-libcxx is installed prior to gdb for older macs. look here for more examples of depends_lib-append: https://github.com/search?q=repo%3Amacports%2Fmacports-ports+depends_lib-append&type=code

> 
>     2. you are using:
> 
> 
> configure.cxxflags-append -L${prefix}/lib/libcxx
> 
> appending linker flags to the cxxflags. They should be appended to the ldflags.
> 
okay i can do that.
>     3. you are not setting any cxx include flags so the headers from the new libcxx are not being used.
> 
gdb isn't complaining about the lack of headers. i think the newer clang headers are being used, it's just not able to find the appropriate (newer) libcxx associated with these headers, as i've pasted below.

>     4. the legacysupport PG has a mechanism to do all this correctly.  Although the code in the PG does have an error in it nobody has fixed yet, it works anyway in almost all cases and does all this correctly. Have you tried that?
> 
> 
> https://github.com/macports/macports-ports/blob/d94ce21c28dc781c81ba103c68eb8abf27100383/_resources/port1.0/group/legacysupport-1.1.tcl#L18

yes, i have, but the problem is the libcxx isn't propagating towards the end of the build:

```
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features by default... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -std=gnu++17... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -std=gnu++1z... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -std=c++17... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with +std=c++17... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -h std=c++17... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -std:c++17... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -std=c++1z... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with +std=c++1z... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -h std=c++1z... no
checking whether /opt/local/bin/clang++-mp-17 supports C++17 features with -std:c++1z... no
configure: error: *** A compiler with support for C++17 language features is required.
```

so the root of the issue is that the macports-libcxx legacy portgroup macro isn't passing the library path so GDB's configure can detect it.

the purpose of depends_lib is to ensure that macports-libcxx is installed beforehand. 

i don't think the legacy portgroup macro can enforce this? correct me if i'm wrong on that?

the headers are taken care of by the newer clang that has to be used. 

i haven't tried with ldflags but i used your cxx-append as the catch-all since you have shown that it plumbs better, and i figured that it was the safest and best way. but i can try with ldflags too.

2024-12-28 16:19 UTC, kencu commented
This is used a lot:

depends_lib-append

This has zero hits in searching the macports repo, other thannin this PR:

configure.depends_lib-append

2024-12-28 16:20 UTC, i3roly commented
oh i see what you’re saying.

yes my apologies that prefix should be removed

Thanks,
Gagan

> On Dec 28, 2024, at 9:19 AM, Ken ***@***.***> wrote:
> 
> 
> This is used a lot:
> 
> depends_lib-append
> 
> This has zero hits in searching the macports repo, other than in this PR:
> 
> configure.depends_lib-append
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
>

2024-12-28 16:44 UTC, kencu commented
If you don’t use the c++ headers in the macports-libcxx port installation, then you are using the default headers installed with the clang port. These default headers have not been modified by me to respect the newer functionality in the newer libcxx, so they will ignore these newer features.

see:

https://github.com/macports/macports-ports/blob/f9cde8c670027940c9b222eba81ccdc99d587f52/lang/macports-libcxx/files/patch-disable-availabilty.diff

2024-12-28 16:48 UTC, kencu commented
there do need to be improvements done to macports-libcxx with respect to using clang compilers significantly newer than the clang-11 used to donate the headers for macports-libcxx. In some cases, isdues may come up, and it’s likely some better method of overriding Apple’s availability tests might be found, like setting a define instead ofbpatching the headers.

I put some initial thoughts on this issue here:

https://trac.macports.org/ticket/71669

2024-12-28 16:49 UTC, i3roly commented
so what would you recommend in this particular instance?

adding a line like the following?

configure.cppflags-append  -I${prefix}/libcxx

2024-12-28 17:23 UTC, i3roly commented
fwiw i noticed that even on sierra (10.12) with the bundled clang 9/xcode, that gdb also fails to build due to the c++17 stuff.

very surprised by this, but seems like the version check needs to be < 17 !

2025-01-03 04:49 UTC, i3roly commented
anybody? it's getting tiresome having to edit portfiles on vms.

2025-07-07 00:16 UTC, closed without merging

2025-07-07 04:56 UTC, barracuda156 commented
@aeiouaeiouaeiouaeiouaeiouaeiou Have you been following this? If GDB is broken on all x86 systems prior to Darwin 17, it’s strange nobody interested to have it fixed. Or is this peculiar to a specific, non-default set-up?

2025-07-07 11:59 UTC, i3roly commented
i just learned vim is building with clang-mp-11 on snow leopard x86_64 instead of regular clang, where clang-mp-11 breaks the build for some weird reason.

lots of things need to get sorted in macports

nobody cares

Thanks,
Gagan

> On Jul 6, 2025, at 10:56 PM, Sergey Fedorov ***@***.***> wrote:
> 
> 
> barracuda156
>  left a comment 
> (macports/macports-ports#27203)
> @aeiouaeiouaeiouaeiouaeiouaeiou Have you been following this? If GDB is broken on all x86 systems prior to Darwin 17, it’s strange nobody interested to have it fixed. Or is this peculiar to a specific, non-default set-up?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.
>

2025-07-07 13:18 UTC, i3roly commented
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} The problem is that clang-mp-11 should compile vim successfully on x86 10.6 just like the clang from xcode 4.2. It doesn't. I found this out after a vim contributor suggested it may be the macports compiler. I didn't think this was the cause but found out it was since I was able to compile vim from source manually       Thanks,GaganSent from my (Inferior Android) BlackBerry—the (second-)most secure mobile device—via the Rogers Network. Long Live QNX                                                                                                                                                                           From: ***@***.***: July 7, 2025 6:28 AMTo: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [macports/macports-ports] add macports libcxx dependency on older macs for gdb (PR #27203)  barracuda156 left a comment (macports/macports-ports#27203)

i just learned vim is building with clang-mp-11 on snow leopard x86_64 instead of regular clang, where clang-mp-11 breaks the build for some weird reason.

If by “regular” clang you mean Xcode clang, then the one from Xcode 3.2.6 is probably just too archaic. (Of course from a fact that Xcode clang builds something on 10.7 it does not follow that the same gonna work on 10.6, these are different clangs.)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2025-07-07 14:13 UTC, barracuda156 commented
@i3roly I see. You can force the compiler to a desired value by `compiler.whitelist clang`, for example. Or, since you don’t need to avoid having clang-11 installed, but just want it not to be used for a given port, do `configure.cc /usr/bin/clang` (or whichever absolute path is needed).

2025-07-07 14:16 UTC, i3roly commented
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} I like the macports clang 11 a lot. I just found it unusual that it would have a bug that's absent in the original xcode 4.2 compiler that works fine. I think maybe for vim we should just use the xcode compiler unless we're on an unusual platform where it's insufficient.       Thanks,GaganSent from my (Inferior Android) BlackBerry—the (second-)most secure mobile device—via the Rogers Network. Long Live QNX                                                                                                                                                                           From: ***@***.***: July 7, 2025 8:14 AMTo: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [macports/macports-ports] add macports libcxx dependency on older macs for gdb (PR #27203)  barracuda156 left a comment (macports/macports-ports#27203)
@i3roly I see. You can force the compiler to a desired value by compiler.whitelist clang, for example. Or, since you don’t need to avoid having clang-11 installed, but just want it not to be used for a given port, do configure.cc /usr/bin/clang (or whichever absolute path is needed).

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>