qt64: Re-enable for 10.14
macports/macports-ports pull request #27202
Opened 2024-12-25 17:31 UTC by tuffnatty

#### Description

Now that #25514 has been merged, most qt64 packages build successfully on 10.14, but alas! 3ddc4db71da5d568f01c628f9e847eee155f9f20 has just shifted the minimal supported version to 10.15. This patch reverts the qt64 part of that commit.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C505

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

2024-12-25 23:10 UTC, reneeotten requested changes
@tuffnatty Upstream does not support it. If you can show that all subports of the qt64 port successfully build on 10.14; then sure, we can re-enable it.

2024-12-26 09:14 UTC, tuffnatty commented
@reneeotten https://doc.qt.io/archives/qt-6.4/supported-platforms.html : macOS 10.14 is supported. Xcode 11 is not supported, right, but somehow it did not matter before 20.12.2024, and we're already using mp-clang instead of Xcode in many other places.
I can try to rebuild all the packages here. AFAIR, only qtwebkit had to be patched, and people here are not very eager to maintain qtwebkit/chromium patched.

2024-12-26 14:16 UTC, reneeotten commented
Yes, it is supported as a target platform but not as a build platform since Xcode 13 or 14 is required. 
I am okay with merging this but please add a comment that 10.14 is not officially supported upstream.

2024-12-27 15:44 UTC, tuffnatty commented
@reneeotten I've added a warning which will be probably also triggered on XCode 11-12 / MacOS 10.15, to stay honest with users.
I've checked and I could indeed rebuild all qt64 ports except qt64-qtwebengine (depending on currently failing nodejs20, but probably also requiring patches, which I have a PoC of) and qt64-qtwebview (depending on failing qt64-qtwebengine)

2024-12-28 15:26 UTC, merged