meetingbar: new port
macports/macports-ports pull request #7884
Opened 2020-07-30 00:12 UTC by herbygillot

#### Description

New port for [MeetingBar](https://meetingbar.onrender.com/)

###### Tested on

macOS 10.15.6 19G73
Xcode 11.6 11E708

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

2020-07-30 00:24 UTC, kencu commented
perhaps add in that it's for 10.15+ only?

If MacPorts is going to embrace the "brew cask" model, we should consider actually setting up a "cask" category and make it obvious for people I guess that we're just installing binaries for them....

2020-07-30 01:54 UTC, herbygillot commented
> perhaps add in that it's for 10.15+ only?

OK, change made.

2020-07-30 02:48 UTC, kencu commented
> I don't know that we need a whole new category for this, I think the `port install` category still works...

It's inherently a totally different kind of installation, with different kinds of issues.

2020-07-30 03:11 UTC, herbygillot commented
> > I don't know that we need a whole new category for this, I think the `port install` category still works...
> 
> It's inherently a totally different kind of installation, with different kinds of issues. 
> 

Gotcha. You're a veteran, so you probably see a lot more of the nuance that I'm currently missing, but I think binary installations fit within the subset of functionality already offered by MacPorts: downloading, caching, checksums, extraction, & uninstallation.

I'm thinking enhancements could be Portfile improvements like an extract_only option (which could probably already exist), or an app_path option that allows you to point to the .app bundle inside the .dmg or .pkg file for a one shot extract + destroot.

2020-07-30 03:17 UTC, herbygillot commented
Also right now the Portfile will fail using `return -code error` for macOS versions less than 10.15... is there a cleaner way of indicating incompatibility?

2020-07-30 03:29 UTC, kencu commented
For one, an app installed this way uses no macports support libraries at all, and either uses only system libraries, or more often has it's own internal libraries and frameworks.  It is therefore built against unknown library versions, and with unknown build arguments. Many of the apps I installed this way with brew cask were not compatible with the OS I installed them on. In part, this is due to the fact that they are not usually built on the os they are installed on.

They usually have intact selfupdate mechanisms in them, and so they update themselves independently of what brew cask (or "MacPorts" cask) does, causing mismatches. 

They are useful -- just a different animal from any MacPorts binary install (usually) -- with a different set of issues. That's why I'm suggesting we find a way to flag them differently, in a different category or with a tag on the name.

Otherwise, when there are issues, it'll be a completely different situation to debug than what we have now.

There is a reason homebrew split them all off into a separate "cask" category.

2020-07-30 03:43 UTC, herbygillot commented
> For one, an app installed this way uses no macports support libraries at all, and either uses only system libraries, or more often has it's own internal libraries and frameworks. It is therefore built against unknown library versions, and with unknown build arguments. Many of the apps I installed this way with brew cask were not compatible with the OS I installed them on. In part, this is due to the fact that they are not usually built on the os they are installed on.
> 
> They usually have intact selfupdate mechanisms in them, and so they update themselves independently of what brew cask (or "MacPorts" cask) does, causing mismatches.
> 
> They are useful -- just a different animal from any MacPorts binary install (usually) -- with a different set of issues. That's why I'm suggesting we find a way to flag them differently, in a different category or with a tag on the name.
> 
> Otherwise, when there are issues, it'll be a completely different situation to debug than what we have now.
> 
> There is a reason homebrew split them all off into a separate "cask" category.

Makes a lot of sense.

2020-07-30 11:46 UTC, ryandesign commented
Is it not possible to build this from source?

2020-07-30 12:53 UTC, kencu commented
> Is it not possible to build this from source?

it looks like it should, but when I tried on Catalina last night outside of MP there was an issue with the code-signing certificates I wasn't sure how to sort out. Should be fixable I think...

2020-12-03 23:55 UTC, cjones051073 requested changes

2020-12-03 23:55 UTC, cjones051073 commented on office/meetingbar/Portfile
> +}
The return statement here should be put inside a pre-fetch block, which is the generally acceptable point in the port processing we prefer these sorts of errors to be issued.

Please also add

known_fail yes

Which prevents build attempts on the buildbots for failing platforms.

See e.g.

https://github.com/macports/macports-ports/blob/370dafef40932d2a53303c40d4c09ae3f6f28c8b/science/root6/Portfile#L209

As a randomly picked example of how it should generally look

2021-01-30 03:14 UTC, kencu commented
I'm going to close this one for now Herby, until MacPorts figures out (if it ever does) how it wants to implement "port cask" type installations. Then we'll bring it back in, with 10,000 more.

2021-01-30 03:14 UTC, closed without merging

2021-01-30 06:31 UTC, herbygillot commented
That's reasonable, np Ken.

On Fri, Jan 29, 2021, 22:14 Ken <notifications@github.com> wrote:

> Closed #7884 <https://github.com/macports/macports-ports/pull/7884>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/macports/macports-ports/pull/7884#event-4268712096>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEW7CGKSBSRHZAJVKXLZH3S4N2RTANCNFSM4PMLTU4Q>
> .
>