shtools: new port
macports/macports-ports pull request #8424
Opened 2020-09-14 12:52 UTC by MarkWieczorek

#### Description

shtools is an archive of Fortran 95 software for performing spherical harmonic transforms and related operations. It is mature software for more than a decade and is an integral component of the python project pyshtools. More information can be found here: https://shtools.github.io/SHTOOLS/

###### Type(s)
submission

###### Tested on
macOS 10.15.6 19G2021
Xcode 11.7 11E801a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-09-15 01:13 UTC, chrstphrchvz requested changes
I am not familiar with building Fortran ports, but I would think the port should be using a MacPorts-specified Fortran compiler, e.g. `${configure.fc}` or `${configure.f90}` (I'm not sure which is more appropriate for Fortran 95), rather than using a `gfortran` command directly (which may not exist even if MacPorts-provided Fortran compilers are present; this is why the CI builds failed). But those are reportedly unavailable when using `use_configure no`; maybe someone else has a suggestion that will work. See https://trac.macports.org/wiki/CompilerSelection#MediumBaseSupport and https://guide.macports.org/chunked/reference.phases.html#reference.phases.configure

2020-09-15 07:45 UTC, MarkWieczorek commented
As far as I can tell, gfortran is being found correctly, but the file`ftypes.f95` in my directory `src` isn't. The file should be there, so I don't understand what is going on.

Here is the relevant part of the log:
```
Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7" && make -w fortran 
DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7" && make -w fortran 
make: Entering directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7'
mkdir -pv /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7/lib
mkdir -pv /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7/modules
/Library/Developer/CommandLineTools/usr/bin/make -C src -f Makefile all F95="gfortran" F95FLAGS="-m64 -fPIC -O3 -std=f2003 -ffast-math" LIBNAME="SHTOOLS" LAPACK_FLAGS="" LIBPATH="/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7/lib" MODPATH="/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7/modules"
make[1]: Entering directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7/src'
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math ftypes.f95
make[1]: gfortran: No such file or directory
make[1]: *** [ftypes.o] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7/src'
make: *** [fortran] Error 2
make: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7'
Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_science_shtools/shtools/work/SHTOOLS-4.7" && make -w fortran 
Exit code: 2
```

2020-09-15 20:28 UTC, MarkWieczorek commented
It turns out that there is probably a small problem in our makefile. This will be addressed soon in a minor update, and will also allow for parallel builds. I am just going to close this and reopen a new issue when the next release comes out.

2020-09-15 20:28 UTC, closed without merging

2020-09-16 00:49 UTC, chrstphrchvz commented
> ```make[1]: gfortran: No such file or directory```

This is `make` saying that `gfortran` can't be found, rather than `gfortran` saying it can't find `types.f95`. In MacPorts, `${prefix}/bin/gfortran` only exists after using `port select gcc`.

2020-09-16 08:42 UTC, MarkWieczorek commented
Could you let me know how to install gcc in a Portfile? It seems that I could just add

```
depends_run         port:gcc10
```
but then how would I activate it using the command line `port select gcc10` ?

2020-09-16 11:42 UTC, chrstphrchvz commented
> Could you let me know how to install gcc in a Portfile? It seems that I could just add
> 
> ```
> depends_run         port:gcc10
> ```

`depends_run` is for runtime dependency. I'm not sure if those more knowledgeable about MacPorts think ports can/should depend directly on a compiler this way. But if they can, then here it would at least need it to be specified as a build dependency; if it is still needed at runtime, then it would be a library dependency.

> but then how would I activate it using the command line `port select gcc10` ?

`port select` is for the user to select their own preferences; portfiles can't run it, nor make assumptions about what has been selected. Though if an exact gcc version dependency is specified, it is already known exactly what `gfortran` command to run: for `gcc10`, the command is `${prefix}/bin/gfortran-mp-10`.

2020-09-16 12:29 UTC, MarkWieczorek commented
You are right about `depends_build`, thanks for reminding me!

So, if I understand properly, I need to tell the make file to use the `gfortran-mp-10` by specifying something like:
```
build.cmd           make
build target        fortran F95="${prefix}/bin/gfortran-mp-10"

depends_build   port:gcc10
```

I believe that the alias`gfortran` is only created when using `port select gcc10`