xournalpp: submission
macports/macports-ports pull request #8688
Opened 2020-10-09 09:11 UTC by someuser12

#### Description

Submitting a port for Xournal++ (there is also an existing port for Xournal). This ports builds the bundle Xournal++.app .

###### Type(s)

- [x] enhancement

###### Tested on

macOS 10.15.7 19H2
Xcode 12.0.1 12A7300

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-10-10 12:06 UTC, harens requested changes
Thanks @someuser12. I just suggested some changes to make the spacing consistent.

2020-10-10 12:06 UTC, harens commented on x11/xournalpp/Portfile
> +PortGroup       cmake   1.0
```suggestion
PortSystem      1.0
PortGroup       github 1.0
PortGroup       cmake 1.0
```

2020-10-10 12:06 UTC, harens commented on x11/xournalpp/Portfile
> +                    size    14892459
```suggestion
checksums       rmd160  f407a8391a3683d87c15d3762c9ecacc13d4dbf5 \
                sha256  13e37aef0bc8178d78301c2405e5e463f70069600512a7b61dedec46cf860844 \
                size    14892459
```

2020-10-10 12:06 UTC, harens commented on x11/xournalpp/Portfile
> +depends_lib      port:gtk3 \
```suggestion
depends_build    port:pkgconfig \
                 port:gtk-mac-bundler

depends_lib      port:gtk3 \
```

2020-10-10 13:15 UTC, harens approved these changes
The problem with suggesting changes on GitHub is that even my spacing is a bit off...

Otherwise, lgtm. Thanks @someuser12.

2020-11-05 06:32 UTC, merged

2020-11-08 07:03 UTC, ryandesign commented
@herbygillot You should have used the "Squash & merge" button to combine my trivial fix with the original author's.

2020-11-08 12:24 UTC, herbygillot commented
You're right @ryandesign, my fault missing that.