Handle dependencies from salsa.debian.org
macports/macports-ports pull request #8759
Opened 2020-10-12 16:59 UTC by jasperweiss

#### Description

Whilst making a Portfile for [wormhole-william](https://github.com/psanford/wormhole-william) I ran into this issue:

`Error: go.vendors can't handle dependencies from salsa.debian.org`

This should fix that. salsa.debian.org is a gitlab instance so the url structure should be the same.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

2020-10-12 19:33 UTC, neverpanic requested changes

2020-10-12 19:33 UTC, neverpanic commented on _resources/port1.0/group/golang-1.0.tcl
> +                    }
We should not duplicate the code handling GitLab. Fortunately, Tcl's [switch case](https://www.tcl.tk/man/tcl8.5/TclCmd/switch.htm) supports a fallthrough option for this purpose.

Replacing both the gitlab.com and the salsa.debian.org block in your code with

```suggestion
                    gitlab.com -
                    salsa.debian.org {
                        set distfile ${vproject}-${vversion}.tar.gz
                        set master_site https://${vdomain}/${vauthor}/${vproject}/-/archive/${vversion}
                    }
```

should achieve this.

2020-10-12 23:52 UTC, amake approved these changes
I applied @neverpanic's suggestion and now LGTM

2020-10-13 09:08 UTC, neverpanic approved these changes

2020-10-13 09:08 UTC, merged