add arm64 as a valid architecture for cmake
macports/macports-ports pull request #8787
Opened 2020-10-14 21:16 UTC by urkle

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.0 beta 9
Xcode 12.2 beta 3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-10-14 23:57 UTC, michaelld requested changes
Thanks for your submission. It's not clear what you're trying to do here. In my testing cmake builds fine on macOS 11.0beta ARM64, and executes as expected. Is this change just for +universal? If so, please update the commit comment to note such.

2020-10-14 23:57 UTC, michaelld commented on devel/cmake/Portfile
> +revision            2
this change is not necessary

2020-10-15 00:21 UTC, urkle commented
When I tried building cmake from macports (port install cmake+gui+qt5) it failed with this message

```
Error: cmake cannot be installed for the configured build_arch 'arm64' because it only supports the arch(s) 'x86_64'.
```

Which apparently I didn't test that well as, yes it builds fine w/o the +gui+qt5.

2020-10-15 00:25 UTC, michaelld commented
> When I tried building cmake from macports (port install cmake+gui+qt5) it failed with this message
> 
> ```
> Error: cmake cannot be installed for the configured build_arch 'arm64' because it only supports the arch(s) 'x86_64'.
> ```
> 
> Which apparently I didn't test that well as, yes it builds fine w/o the +gui+qt5.

Yeah that error isn't very useful ... I'm pretty sure it's about qt5, not cmake. I did get qt5 going on ARM64 ... hmmm ... I should test your variants now ... thanks for the prod!

I also am not sure whether +universal works for x86_64 / ARM64 ... your change -might- help fix that; again, needs testing!

I'm going to go ahead and close this PR. Thanks again for submitted & the prod for more / other testing / variants with cmake!

2020-10-15 00:25 UTC, closed without merging

2020-10-19 01:01 UTC, michaelld commented
FYI `cmake +gui + qt5` does build on ARM64 using Qt5 5.15.1 from my PR plus a few ARM64 tweaks that I'll submit a PR for once the basic Qt5 one is merged. Interestingly, Qt5 apps work just fine; the look the same & behave the same on ARM64 as on Intel x86_64. But the CMake GUI errors out quickly on ARM64. Not sure why. CMake GUI on Intel x86_64 works.