py-docutils: added select group (including new docutils_select port)
macports/macports-ports pull request #9276
Opened 2020-11-28 23:39 UTC by catap

#### Description

Let make possibly to enduser to decide which version of `rst2man` should be used by default.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 11.0.1 20B50
Xcode 12.2 12B45b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-11-29 16:15 UTC, mf2k requested changes

2020-11-29 16:15 UTC, mf2k commented on python/py-docutils/Portfile
> +revision            2
The `revision` should only be 1 here.

2020-11-29 16:24 UTC, catap commented on python/py-docutils/Portfile
> +revision            2
@mf2k thanks, fixed!

2020-11-29 16:29 UTC, mf2k requested changes

2020-11-29 16:29 UTC, mf2k commented on python/py-docutils/Portfile
> +                        port:docutils_select
Nitpick. Please sort these alphabetically.

2020-11-29 16:32 UTC, catap commented on python/py-docutils/Portfile
> +                        port:docutils_select
@mf2k fixed

2020-11-29 18:23 UTC, mf2k approved these changes

2020-12-10 21:37 UTC, catap commented
@mf2k that should we do now? :)

2020-12-17 12:09 UTC, catap commented
@mf2k can you merge it? :)

2020-12-17 12:50 UTC, catap commented
Just rebased to last master

2020-12-18 15:15 UTC, catap commented
@ryandesign can I ask your attention here? :) Maybe you can forward it to someone?

2020-12-29 16:57 UTC, catap commented
rebased to last master

2021-01-27 10:47 UTC, catap commented
@kencu and I have one more very old PR that is very useful when you try to develop for example Varnish on machine :) 

May I ask you to check this one? ;)

2021-01-27 15:20 UTC, kencu commented
This looks reasonable.

This port appears to be actively maintained by one of MacPorts top dudes, @jmroot, and he's here many times each day.

I'm not certain what the holdup, if any, might be but can understand my reluctance to get my finger bit...

2021-01-27 17:45 UTC, merged