npm6: depend upon nodejs15
macports/macports-ports pull request #9413
Opened 2020-12-11 14:08 UTC by hexagonal-sun

#### Description

nodejs15 now builds on arm64. Re-target npm6 to work with nodejs15 so
that a usable node system can be installed on that platform.

Note: There may be a good reason that npm6 requires nodejs14, rather than 15.  If so, is there an alternative to getting a fully working node system on arm64?

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-12-17 02:46 UTC, neverpanic commented
@hexagonal-sun Have you tested that npm6 works on nodejs15? If so, I'm inclined to approve and merge this.

2020-12-17 08:47 UTC, hexagonal-sun commented
> @hexagonal-sun Have you tested that npm6 works on nodejs15? If so, I'm inclined to approve and merge this.

I've been using this on my system for the last week and haven't encountered any issues so far.

2020-12-21 17:17 UTC, hexagonal-sun commented
@neverpanic Gentle bump.  If you're happy are we okay to merge this?  Thanks!

2020-12-21 19:23 UTC, neverpanic requested changes
Sorry I didn't see this earlier, but this needs an increase in the revision field, i.e. please add

```
revision 1
```
below the `version` line.

2020-12-23 08:15 UTC, hexagonal-sun commented
@neverpanic thanks for the suggestion.  Now implemented!

2020-12-23 13:29 UTC, neverpanic approved these changes
And approved as requested. Thank you!

2020-12-23 13:29 UTC, merged