openssh: update to 8.4p1, drop keychain patch and hpn variant
macports/macports-ports pull request #9451
Opened 2020-12-17 02:20 UTC by Schamschula

update gsskex and macports-config patches

#### Description

openssh has been updated several times upstream since the last MacPorts update.
MacPorts has tried to maintain the unsupported Apple keychain patch.
Homebrew dropped support for this patch in 2016: https://archive.is/hSB6d#10%25

7.7p1, in 2018, was the last version to support the hpn option in FreeBSD Freshports:
https://www.freshports.org/security/openssh-portable/

###### Type(s)

- [x] update
- [x] security fix

###### Tested on

macOS 10.14.6 18G6042
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-12-17 02:27 UTC, neverpanic commented
Seems there's a bit of a mashup in the commit message now :)

2020-12-17 02:51 UTC, Schamschula commented
Indeed! I should read my local wiki notes all the way though before pushing a squash commit...

I forgot to use --force!

Lots of unnecessary extra work.

2020-12-17 14:21 UTC, Schamschula commented
Removed obsolete ```note``` content.

2020-12-17 16:44 UTC, neverpanic commented
The commit message is still broken.

2020-12-17 16:52 UTC, Schamschula commented
So it is!

I didn't catch that a premature press of the ```y``` key would continue to propagate.

2020-12-17 18:07 UTC, neverpanic requested changes

2020-12-17 18:07 UTC, neverpanic commented on net/openssh/Portfile
>      # We need a couple of patches
This comment needs adjusting – it still references `0002-Apple-keychain-integration-other-changes.patch` that is now gone.

2020-12-19 04:24 UTC, neverpanic approved these changes
lg2m now. Haven't tested all variants, though.

2020-12-19 11:10 UTC, Schamschula commented
I did build all variants. However, I normally install the default variants.

2020-12-19 13:22 UTC, merged