vulture: update to 2.1; switch to Python 3.9
macports/macports-ports pull request #9541
Opened 2020-12-28 11:33 UTC by dliessi

#### Description

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2020-12-28 16:37 UTC, reneeotten requested changes
the update looks good to me, you can do a bit of clean-up as I suggested since some of the defaults are nowadays set by the python PG

2020-12-28 16:37 UTC, reneeotten commented on devel/vulture/Portfile
>  set _n              [string index ${name} 0]
you can remove this line and the `master_sites` and `distname` fields; these are set by the python PG

2020-12-28 22:22 UTC, dliessi commented
I updated the Portfile as @reneeotten suggested. When merging, the commits can be squashed, retaining only the commit message of the first one, i.e. `vulture: update to 2.1; switch to Python 3.9`.

2020-12-29 00:20 UTC, reneeotten approved these changes

2020-12-29 00:20 UTC, merged