submission: Portfile for Munt's library for emulation of Roland MT-32, CM-32L and…
macports/macports-ports pull request #9842
Opened 2021-01-28 13:01 UTC by DominusExult

#### Description

mt32emu is a C/C++ library which allows to emulate (approximately) the Roland MT-32, CM-32L and LAPC-I synthesiser modules.
The Munt project also provides a GUI (QT4/5) app, as well as terminal program. These usually go into a sperate package ("munt") because of the many dependencies (QT, glib2, JACK, Portaudio), the library has no dependencies (other than CMake).

This builds just the shared library for other projects to make use of.

I've made port request the other day:  https://trac.macports.org/ticket/62166

###### Type(s)

- [x] submission

###### Tested on

macOS 11.1 20C69
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-01-28 14:48 UTC, mf2k requested changes

2021-01-28 14:48 UTC, mf2k commented on audio/munt-mt32emu/Portfile
> +homepage			http://munt.sourceforge.net/
Your spacing is not consistent here.

2021-01-28 14:48 UTC, mf2k commented on audio/munt-mt32emu/Portfile
> +distname			munt-${version}
Please fix the spacing here too.

2021-01-28 14:48 UTC, mf2k commented on audio/munt-mt32emu/Portfile
> +maintainers         openmaintainer
`openmaintainer` by itself is not valid. Use `nomaintainer`.

2021-01-28 14:54 UTC, mf2k commented
In the commit message add the following line to automatically close the Trac ticket. 

`Fixes: https://trac.macports.org/ticket/62166`

2021-01-28 16:03 UTC, DominusExult commented
thank you for your review. Everything should be fixed now. If you prefer one commit I can restart the pull request. I messed up when I fixed the spacing and only then after my push remembered the openmaintainer issue.

2021-01-28 16:54 UTC, mf2k requested changes

2021-01-28 16:54 UTC, mf2k commented on audio/munt-mt32emu/Portfile
> +                    -Dmunt_WITH_MT32EMU_QT=FALSE
Looking good! Please also address the lint warning by adding a newline at the end.

2021-01-28 16:55 UTC, mf2k commented
You will also need to squash your commits into 1 and follow the [GitHub commit message guidelines](https://trac.macports.org/wiki/CommitMessages)

2021-01-28 20:08 UTC, DominusExult commented
Thanks for bearing with me, this was the first time I had to do a rebase and the devil is always in the details.

2021-01-28 20:29 UTC, mf2k approved these changes

2021-01-28 20:31 UTC, mf2k commented
The commit message is getting closer. It needs to start with the port name and list changes. In this case, just keep in simple for a submission. 

```
munt-mt32emu: New port

Fixes: https://trac.macports.org/ticket/62166

```

2021-01-29 17:08 UTC, DominusExult commented
Was there a system hiccup or why did those tests fail? AFAICS there is no reason given.
Other than those failed tests, the pull request is ok now, right?

2021-01-29 18:52 UTC, merged