py-cachecontrol: Add missing dependency, py-pkginfo: Update to 1.7.0
macports/macports-ports pull request #9847
Opened 2021-01-28 21:50 UTC by neverpanic

#### Description

py-cachecontrol: Add missing dependency py-lockfile. poetry uses py-cachecontrol and fails without the py-lockfile dependency.

py-pkginfo: Update to 1.7.0. Fixes an issue with poetry because the previous version could not parse installed wheels, i.e., dist-info folders. See also https://github.com/python-poetry/poetry/issues/3362

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G7016
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-01-29 01:43 UTC, reneeotten commented
I am not sure that `py-lockfile` should be added as a dependency in `py-cachecontrol` as is done in this PR. It is an optional dependency and typically we don't add those by default. Looking at `poetry`, it is that one that lists:
```
cachecontrol = { version = "^0.12.4", extras = ["filecache"] }
```
so in my opinion the `py-lockfile`  dependency should be added to `poetry` instead.

2021-01-29 04:29 UTC, dgilman commented
I swear lockfile was in the poetry Portfile and it was, but it was removed as part of the poetry 1.1.4 update. I agree with reneeotten that it should be done in the poetry PR. 

So the other dropped deps in the 1.1.4 Portfile were jsonschema, pyparsing, pyrsistent. Looks like Poetry dropped jsonschema and pyrsistent by the time they got to 1.1.4 - I am not even seeing those in 1.1.4's lockfile. pyparsing is still around but as a dependent of pypackaging. So if lockfile goes back into the poetry Portfile things should be good.

2021-01-30 02:15 UTC, neverpanic commented
@reneeotten You're right, fixed.

2021-01-30 15:06 UTC, jjstickel commented
LGTM for py-pkginfo

2021-01-30 16:12 UTC, neverpanic commented
@dgilman Does this look good to you as well? If so, I can merge.

2021-01-30 17:14 UTC, harens requested changes
Thanks @neverpanic for fixing this. The issue you referenced affected me as well, so thank you very much for your fix 👍.

I thought that whilst we're making changes, now might be the time to correct a few small nitpicks.

#### poetry

Genuine question. Would we need to set a runtime dep on `bash_completion` for the bash completion to function? 

e.g. `depends_run-append  path:etc/bash_completion:bash-completion`

#### py-pkginfo

- `master_sites` and `distname` should no longer be necessary since they're in the Python PG.
- `livecheck.type none` should be added to the `if {${name} ne ${subport}}` block, as is standard in other python ports.
- `supported_archs noarch` should be added since there are no architecture-dependent files that are installed.

2021-01-31 18:33 UTC, neverpanic commented
> Genuine question. Would we need to set a runtime dep on `bash_completion` for the bash completion to function?
> 
> e.g. `depends_run-append path:etc/bash_completion:bash-completion`

No. Users that do not have `bash-completion` installed will just not get bash completion, but there may be users of poetry with different preferred shell choices, so I don't feel like forcing the `bash-completion` dependency on them.

>     * `master_sites` and `distname` should no longer be necessary since they're in the Python PG.
>     * `livecheck.type none` should be added to the `if {${name} ne ${subport}}` block, as is standard in other python ports.
>     * `supported_archs noarch` should be added since there are no architecture-dependent files that are installed.

Thanks, all fixed.

2021-02-01 01:45 UTC, dgilman commented
LGTM

2021-02-01 14:49 UTC, neverpanic commented
Thanks, merging.

2021-02-01 14:49 UTC, merged