inspectrum: update to 0.2.3
macports/macports-ports pull request #9868
Opened 2021-01-30 20:45 UTC by hexagonal-sun

#### Description

Update inspectrum to version 0.2.3.  The current version fails to
build with versions of Qt>5.15.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.1 20C69
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

2021-01-30 21:59 UTC, mf2k requested changes

2021-01-30 21:59 UTC, mf2k commented on science/inspectrum/Portfile
> +version             0.2.3
This is normally done with one line as follows:

`github.setup        miek inspectrum 0.2.3 v
`

2021-02-01 20:25 UTC, hexagonal-sun commented
@mf2k Thanks for the review.  Should now be fixed.

2021-02-01 21:09 UTC, michaelld reviewed
Given how often Inspectrum is updated, we should be using the GIT hash & date, not the release. In this manner we can keep this port updated with current commits instead of waiting for ages for a new release. I have an update ready & will use it instead of this one. Thanks for your efforts!

2021-02-01 21:09 UTC, closed without merging

2021-02-01 21:10 UTC, michaelld commented
e51344dd456339bb8d103151dbc1960ada336745